// Domain 1 — General Security Concepts (12%)
//
// Distractors are adjacent objective-list terms wherever one exists, and the
// discarded real-world word where CompTIA has replaced it (mantrap ->
// access control vestibule). Explanations name the binary test.

export default [

/* ---------------- 1.1 security controls ---------------- */
{
  objective: '1.1',
  stem: 'A company posts signs at the perimeter reading "This area is under 24-hour video surveillance." The signs are not connected to any system. Which control TYPE do the signs represent?',
  options: ['Preventive', 'Deterrent', 'Detective', 'Compensating'],
  answer: 1,
  explanation: 'The binary test is whether it can actually stop someone. A sign cannot. Deterrent discourages before the fact; preventive physically or logically blocks. The cameras themselves would be detective — they record but do not intervene.',
},
{
  objective: '1.1',
  stem: 'An organisation cannot deploy multifactor authentication on a legacy application, so it restricts access to a single hardened jump host and logs every session. What is the jump host acting as?',
  options: ['Compensating control', 'Corrective control', 'Directive control', 'Detective control'],
  answer: 0,
  explanation: 'Compensating is specifically the control you put in when the control you wanted is not feasible. Corrective repairs damage after an event has already happened — nothing has happened here.',
},
{
  objective: '1.1',
  stem: 'Which of the following is a MANAGERIAL control?',
  options: ['A host-based firewall', 'An annual risk assessment', 'A security guard at reception', 'A locked server cabinet'],
  answer: 1,
  explanation: 'Category asks what kind of thing it is. Managerial is the paperwork that governs — policy, planning, risk assessment. The guard is operational (a person, day to day), the cabinet physical, the firewall technical.',
},
{
  objective: '1.1',
  stem: 'Security awareness training delivered to all staff each quarter is BEST classified as which control category?',
  options: ['Managerial', 'Operational', 'Technical', 'Physical'],
  answer: 1,
  explanation: 'Operational controls are executed by people as part of running the business. The policy that requires the training is managerial; the training session itself is operational. This pair is the most common category mix-up.',
},
{
  objective: '1.1',
  stem: 'After a ransomware incident, the team restores affected servers from backup. Restoring from backup is which control type?',
  options: ['Recovery', 'Corrective', 'Compensating', 'Preventive'],
  answer: 1,
  explanation: 'Corrective controls repair damage after an event. "Recovery" feels right because it is an incident response phase — but it is not one of the six control types, which are preventive, deterrent, detective, corrective, compensating and directive.',
},
{
  objective: '1.1',
  stem: 'An acceptable use policy that states employees must not install unapproved software is BEST described as which control type?',
  options: ['Directive', 'Preventive', 'Managerial', 'Deterrent'],
  answer: 0,
  explanation: 'Directive controls tell people what they must do. Managerial is a valid description but it answers the CATEGORY question, not the TYPE question — read which of the two lists the stem is asking for.',
},
{
  objective: '1.1',
  stem: 'A firewall configured to drop traffic from known-malicious IP addresses is BEST classified as which combination?',
  options: ['Detective, technical', 'Preventive, technical', 'Preventive, operational', 'Corrective, technical'],
  answer: 1,
  explanation: 'It blocks the traffic, so it is preventive rather than detective; it is enforced by a machine, so it is technical rather than operational. This exact pairing is the canonical Security+ classification question.',
},
{
  objective: '1.1',
  stem: 'A bollard installed outside a data centre entrance is which control CATEGORY and TYPE?',
  options: ['Physical, preventive', 'Physical, deterrent', 'Operational, preventive', 'Technical, preventive'],
  answer: 0,
  explanation: 'A bollard physically stops a vehicle, so preventive rather than deterrent. Category is physical because it is a barrier rather than a machine, a person or a document.',
},

/* ---------------- 1.2 fundamental concepts ---------------- */
{
  objective: '1.2',
  stem: 'A contract must be signed digitally so that the signer cannot later deny having signed it. Which security concept does this requirement describe?',
  options: ['Integrity', 'Non-repudiation', 'Confidentiality', 'Authentication'],
  answer: 1,
  explanation: 'Integrity proves the document did not change. Non-repudiation proves WHO acted and removes their ability to deny it. The mechanism is a digital signature — reaching for encryption here is the classic upgrade error.',
},
{
  objective: '1.2',
  stem: 'An attacker modifies the account number in a payment file while it is in transit. Which element of the CIA triad has been violated?',
  options: ['Confidentiality', 'Integrity', 'Availability', 'Non-repudiation'],
  answer: 1,
  explanation: 'Integrity is the assurance data has not been altered. Confidentiality would be violated by reading the file; availability by preventing access to it. Non-repudiation is not part of the triad.',
},
{
  objective: '1.2',
  stem: 'In a Zero Trust architecture, which component evaluates policy and makes the decision to grant or deny a request?',
  options: ['Policy Enforcement Point', 'Policy Administrator', 'Policy Engine', 'Policy-driven access control'],
  answer: 2,
  explanation: 'The Policy Engine decides. The Policy Administrator communicates and executes that decision. Both are Control Plane. The Enforcement Point, on the Data Plane, is what actually allows or blocks the traffic.',
},
{
  objective: '1.2',
  stem: 'Which Zero Trust component sits in the traffic path and actually permits or blocks the connection?',
  options: ['Policy Enforcement Point', 'Policy Engine', 'Policy Administrator', 'Adaptive identity'],
  answer: 0,
  explanation: 'The Policy Enforcement Point is the only one of the three "policy" components on the DATA plane. Engine and Administrator are Control Plane. That split is the most-tested Zero Trust distinction in Domain 1.',
},
{
  objective: '1.2',
  stem: 'A Zero Trust design limits what any single compromised credential can reach. Which Control Plane concept does the objectives document use for this?',
  options: ['Least privilege', 'Threat scope reduction', 'Implicit trust zones', 'Segmentation'],
  answer: 1,
  explanation: 'Least privilege and segmentation are real terms but they belong to objectives 2.5 and 4.6. Inside Zero Trust\'s Control Plane the objectives word is threat scope reduction. The objective you are in decides the credited word.',
},
{
  objective: '1.2',
  stem: 'An organisation compares its current controls against the ISO 27001 control set to see what is missing before starting certification. What is this activity called?',
  options: ['Risk assessment', 'Gap analysis', 'Audit', 'Penetration test'],
  answer: 1,
  explanation: 'Gap analysis measures the present state against a chosen target standard. A risk assessment measures exposure to threats — it does not need a standard to compare against.',
},
{
  objective: '1.2',
  stem: 'Security places a document named "executive_salaries_2026.xlsx" on a file share. It contains nothing real, and opening it raises an alert. What is this?',
  options: ['Honeypot', 'Honeyfile', 'Honeytoken', 'Honeynet'],
  answer: 1,
  explanation: 'Scale is the discriminator: honeytoken is one record or credential, honeyfile is one file, honeypot is a whole system, honeynet is a network of honeypots.',
},
{
  objective: '1.2',
  stem: 'A fake set of database credentials is planted that no application uses. Any authentication attempt with them triggers an immediate alert. What is this called?',
  options: ['Honeyfile', 'Honeytoken', 'Honeypot', 'Honeynet'],
  answer: 1,
  explanation: 'A honeytoken is data that should never legitimately be USED — credentials, an API key, a record. A honeyfile is data that should never legitimately be OPENED.',
},
{
  objective: '1.2',
  stem: 'A facility uses two interlocking doors where the second will not open until the first has closed, preventing tailgating. Which objective-list term describes this?',
  options: ['Access control vestibule', 'Mantrap', 'Bollards', 'Fencing'],
  answer: 0,
  explanation: 'Mantrap is the traditional industry word and is deliberately not on the SY0-701 list. When real-world usage and the objectives disagree, answer with the objectives.',
},
{
  objective: '1.2',
  stem: 'Which physical security control is specifically intended to stop a vehicle from reaching a building entrance?',
  options: ['Fencing', 'Bollards', 'Access control vestibule', 'Lighting'],
  answer: 1,
  explanation: 'Bollards are vehicle-specific. Fencing defines a perimeter against people. Both are on the 1.2 physical security list, and the stem naming a vehicle is the discriminator.',
},
{
  objective: '1.2',
  stem: 'A sensor detects an intruder by measuring the reflection of high-frequency sound waves off a moving body. Which sensor type is this?',
  options: ['Infrared', 'Microwave', 'Ultrasonic', 'Pressure'],
  answer: 2,
  explanation: 'Ultrasonic uses sound; microwave uses radio energy; infrared detects heat; pressure detects weight. The objectives list all four and questions distinguish them by the physical phenomenon named.',
},
{
  objective: '1.2',
  stem: 'Which AAA function answers the question "what did this user actually do while logged in"?',
  options: ['Authentication', 'Authorization', 'Accounting', 'Attestation'],
  answer: 2,
  explanation: 'Authentication is who you are, authorization is what you may do, accounting is the record of what you did. Attestation is a 4.6/5.5 term about confirming something is valid, not part of AAA.',
},

/* ---------------- 1.3 change management ---------------- */
{
  objective: '1.3',
  stem: 'A change request is rejected because it does not document how the change would be reversed if it fails. Which element is missing?',
  options: ['Backout plan', 'Disaster recovery plan', 'Maintenance window', 'Impact analysis'],
  answer: 0,
  explanation: 'A backout plan is scoped to one change. A disaster recovery plan is scoped to the whole site or service and is a 5.1 policy, not a change-management artifact.',
},
{
  objective: '1.3',
  stem: 'A change board approves a database upgrade to run between 02:00 and 04:00 on Sunday. What is that agreed period called?',
  options: ['Downtime', 'Maintenance window', 'Service restart', 'Restricted activity'],
  answer: 1,
  explanation: 'The maintenance window is the PERMISSION to cause disruption; downtime is the CONSEQUENCE. The objectives list both separately and questions trade on the difference.',
},
{
  objective: '1.3',
  stem: 'Before approving a firewall rule change, the team documents which business services would be affected and how badly. What is this step?',
  options: ['Test results', 'Impact analysis', 'Approval process', 'Standard operating procedure'],
  answer: 1,
  explanation: 'Impact analysis assesses consequences before approval. Test results are the evidence you bring to that approval — they show the change works, not what it would break.',
},
{
  objective: '1.3',
  stem: 'A configuration management system retains every previous revision of a firewall ruleset so any version can be restored. Which 1.3 element is this?',
  options: ['Version control', 'Backout plan', 'Documentation', 'Change management'],
  answer: 0,
  explanation: 'Version control is the artifact that records what the file looked like before. Change management is the surrounding process. The backout plan is the intent to revert; version control is what makes reverting possible.',
},
{
  objective: '1.3',
  stem: 'An upgrade is blocked because a critical in-house application will not run on the new operating system version. Which technical implication does this illustrate?',
  options: ['Dependencies', 'Legacy applications', 'Restricted activities', 'Downtime'],
  answer: 1,
  explanation: 'The blocker is an old application that cannot move. Dependencies would apply if the change required another change first, or if a service relied on this one — the constraint here is the application\'s age, not an ordering relationship.',
},

/* ---------------- 1.4 cryptography ---------------- */
{
  objective: '1.4',
  stem: 'A random value is added to each password before it is hashed, so that two users with the same password produce different stored hashes. What is this called?',
  options: ['Key stretching', 'Salting', 'Tokenization', 'Obfuscation'],
  answer: 1,
  explanation: 'Salting defeats precomputed rainbow tables by making each hash unique. Key stretching is the different defence of making each individual guess slow — it attacks the attacker\'s time, not their precomputation.',
},
{
  objective: '1.4',
  stem: 'A password storage scheme deliberately applies thousands of hashing iterations so that each guess is computationally expensive. What is this technique called?',
  options: ['Salting', 'Key stretching', 'Hashing', 'Digital signature'],
  answer: 1,
  explanation: 'Key stretching increases the cost per attempt. Salting makes each hash unique. Both are used together in PBKDF2 and bcrypt, and questions test which one addresses which attack.',
},
{
  objective: '1.4',
  stem: 'A payment system replaces each card number with a randomly generated reference. The real number is held in a separate secured vault. What is this?',
  options: ['Data masking', 'Tokenization', 'Steganography', 'Hashing'],
  answer: 1,
  explanation: 'Tokenization removes the real value from the system entirely and is reversible through the vault. Masking leaves the real value in place and only hides characters on display.',
},
{
  objective: '1.4',
  stem: 'A support application displays a customer\'s card number as ************4471. The full number remains in the database. Which technique is this?',
  options: ['Tokenization', 'Data masking', 'Encryption', 'Obfuscation'],
  answer: 1,
  explanation: 'Masking is a display control — the real value is still underneath. If the real value had left the system and been replaced by a meaningless reference, it would be tokenization.',
},
{
  objective: '1.4',
  stem: 'An insider exfiltrates a document by embedding it in the pixel data of a holiday photograph posted to social media. Which technique is this?',
  options: ['Encryption', 'Steganography', 'Data masking', 'Tokenization'],
  answer: 1,
  explanation: 'Encryption hides the MEANING and is obvious — anyone can see there is ciphertext. Steganography hides the EXISTENCE, so it looks like nothing happened at all.',
},
{
  objective: '1.4',
  stem: 'A laptop stores its full-disk encryption key in a dedicated chip soldered to the motherboard, which will release it only if boot integrity checks pass. What is the chip?',
  options: ['Hardware security module (HSM)', 'Trusted Platform Module (TPM)', 'Secure enclave', 'Key management system'],
  answer: 1,
  explanation: 'A TPM is one chip bound to one machine. An HSM is a separate appliance serving many systems — the discriminator is whether the device belongs to one host or to the estate.',
},
{
  objective: '1.4',
  stem: 'A payment processor needs a tamper-resistant appliance to generate and store keys for thousands of transactions per second across many servers. Which tool fits?',
  options: ['Trusted Platform Module (TPM)', 'Hardware security module (HSM)', 'Secure enclave', 'Key escrow'],
  answer: 1,
  explanation: 'Scale and independence from any one host make it an HSM. A TPM would be tied to a single machine and could not serve the fleet.',
},
{
  objective: '1.4',
  stem: 'A browser needs to check whether one specific certificate has been revoked, without downloading a large list. Which mechanism does this?',
  options: ['Certificate revocation list (CRL)', 'Online Certificate Status Protocol (OCSP)', 'Certificate signing request (CSR)', 'Root of trust'],
  answer: 1,
  explanation: 'OCSP is a live query about one certificate. A CRL is a published list you download in full. Same purpose, opposite mechanism — the stem\'s "one specific certificate, without a large list" is the tell.',
},
{
  objective: '1.4',
  stem: 'An administrator generates a key pair and produces a file containing the public key and organisation details to send to a certificate authority. What is that file?',
  options: ['Certificate revocation list', 'Certificate signing request (CSR)', 'Self-signed certificate', 'Key escrow record'],
  answer: 1,
  explanation: 'You generate the CSR; the CA signs it and returns the certificate. The request is not the authority and is not yet a certificate.',
},
{
  objective: '1.4',
  stem: 'A company needs one certificate that will secure mail.example.com, vpn.example.com and any future host under example.com. Which certificate type fits?',
  options: ['Wildcard', 'Self-signed', 'Third-party', 'Root of trust'],
  answer: 0,
  explanation: 'A wildcard covers *.example.com including hosts that do not exist yet. A Subject Alternative Name certificate lists specific names and would need reissuing for a new host — and SAN is in the acronym list, not the 1.4 bullet list.',
},
{
  objective: '1.4',
  stem: 'A regulator requires that a copy of each employee\'s private key be recoverable by the organisation if the employee leaves. What is this arrangement?',
  options: ['Key management system', 'Key escrow', 'Key stretching', 'Key exchange'],
  answer: 1,
  explanation: 'Escrow is about who ELSE holds a copy of the key. A key management system is the tooling that issues, rotates and retires keys — it is where escrow would be implemented, not the concept itself.',
},
{
  objective: '1.4',
  stem: 'Two parties who have never communicated before need to agree a shared secret over an untrusted network. Which cryptographic operation accomplishes this?',
  options: ['Key exchange', 'Digital signature', 'Hashing', 'Key escrow'],
  answer: 0,
  explanation: 'Key exchange establishes a shared symmetric key over an insecure channel — Diffie-Hellman is the classic example. Signatures prove origin; hashing proves integrity; neither creates a shared secret.',
},
{
  objective: '1.4',
  stem: 'An organisation encrypts a specific column of customer identifiers rather than the whole storage volume. Which encryption LEVEL is in use?',
  options: ['Full-disk', 'Volume', 'Database', 'Record'],
  answer: 3,
  explanation: 'The objectives list six levels from full-disk down to record. Encrypting individual rows or fields is record-level; database-level would protect the whole database instance uniformly.',
},
{
  objective: '1.4',
  stem: 'A distributed ledger records transactions in linked blocks that any participant can verify and none can retroactively alter. Which 1.4 terms BEST describe this?',
  options: ['Blockchain and open public ledger', 'Hashing and salting', 'Key escrow and key exchange', 'Obfuscation and tokenization'],
  answer: 0,
  explanation: 'The objectives list blockchain and open public ledger as adjacent terms in 1.4. Hashing is the primitive that makes the chain tamper-evident, but the structure itself is the blockchain.',
},
{
  objective: '1.4',
  stem: 'Which statement correctly distinguishes symmetric from asymmetric encryption?',
  options: [
    'Symmetric uses one shared key; asymmetric uses a public/private key pair',
    'Symmetric uses a key pair; asymmetric uses one shared key',
    'Symmetric is used only for signatures; asymmetric only for bulk data',
    'Symmetric cannot be used over a network; asymmetric can',
  ],
  answer: 0,
  explanation: 'One key both directions is symmetric (AES). A mathematically related pair is asymmetric (RSA, ECC). Because asymmetric is slow, real systems use it to exchange a symmetric key and then encrypt the bulk data symmetrically.',
},
{
  objective: '1.4',
  stem: 'A hardware root of trust is BEST described as which of the following?',
  options: [
    'The certificate authority at the top of a PKI hierarchy',
    'A component inherently trusted to anchor the verification of everything above it',
    'A list of certificates that have been revoked',
    'A backup copy of the private key held by a third party',
  ],
  answer: 1,
  explanation: 'Root of trust is the anchor that verification chains back to and that cannot itself be verified by anything else. A root CA is one example of the idea, but the objectives list root of trust as its own term.',
},
];
