// Domain 2 — Threats, Vulnerabilities, and Mitigations (22%)

export default [

/* ---------------- 2.1 threat actors and motivations ---------------- */
{
  objective: '2.1',
  stem: 'A marketing team signs up for an unapproved SaaS analytics platform and uploads customer data, because procurement was taking too long. Which threat actor category does the objectives document use?',
  options: ['Insider threat', 'Shadow IT', 'Unskilled attacker', 'Organized crime'],
  answer: 1,
  explanation: 'Insider threat implies intent to harm. Shadow IT is well-meaning and still appears on CompTIA\'s threat actor list — that is exactly why it is easy to miss.',
},
{
  objective: '2.1',
  stem: 'An attacker downloads a ready-made exploit kit and runs it without understanding how it works. Which SY0-701 term describes this actor?',
  options: ['Script kiddie', 'Unskilled attacker', 'Hacktivist', 'Insider threat'],
  answer: 1,
  explanation: 'Script kiddie is the traditional word and is deliberately absent from SY0-701. When real-world usage and the objectives disagree, answer with the objectives.',
},
{
  objective: '2.1',
  stem: 'A group breaches a chemical company and leaks internal documents to protest its environmental record. Which motivation BEST fits?',
  options: ['Disruption/chaos', 'Philosophical/political beliefs', 'Revenge', 'Financial gain'],
  answer: 1,
  explanation: 'The motivation list separates having a cause from simply wanting to break things. A stated protest means philosophical/political beliefs; disruption/chaos is damage for its own sake.',
},
{
  objective: '2.1',
  stem: 'A state-sponsored group maintains covert access to a defence contractor for two years, collecting design documents without disrupting anything. Which motivation applies?',
  options: ['Espionage', 'Data exfiltration', 'Service disruption', 'Blackmail'],
  answer: 0,
  explanation: 'Espionage steals in order to KNOW, over time and covertly. Data exfiltration is the broader act of moving data out — it describes the mechanism, while espionage describes the purpose the stem gives.',
},
{
  objective: '2.1',
  stem: 'A security researcher discovers a flaw and reports it to the vendor rather than exploiting it. Which motivation does the objectives document list for this?',
  options: ['Ethical', 'Philosophical/political beliefs', 'Revenge', 'Disruption/chaos'],
  answer: 0,
  explanation: 'Ethical is a motivation on CompTIA\'s list and is routinely forgotten by people reproducing the list from intuition, because it does not feel like an attacker motivation at all.',
},
{
  objective: '2.1',
  stem: 'Which attribute BEST distinguishes a nation-state actor from organized crime?',
  options: [
    'Whether the actor is internal or external',
    'Level of sophistication and resources/funding',
    'Whether the actor is motivated by money',
    'Whether the attack uses malware',
  ],
  answer: 1,
  explanation: 'The three attributes the objectives list are internal/external, resources/funding and level of sophistication/capability. Both actors are external and both may seek money; only funding and sophistication separate them reliably.',
},
{
  objective: '2.1',
  stem: 'A recently dismissed administrator uses credentials that were never revoked to delete production backups. Which combination BEST describes this?',
  options: [
    'Insider threat motivated by revenge',
    'Shadow IT motivated by disruption/chaos',
    'Organized crime motivated by financial gain',
    'Unskilled attacker motivated by ethical concerns',
  ],
  answer: 0,
  explanation: 'The actor had legitimate access, which makes them an insider threat; dismissal followed by destruction points to revenge rather than gain. Shadow IT is never malicious by definition.',
},

/* ---------------- 2.2 threat vectors and attack surfaces ---------------- */
{
  objective: '2.2',
  stem: 'An attacker registers "exarnple.com" — an "rn" in place of the "m" — and hosts a copy of a bank\'s login page. Which threat vector is the domain registration itself?',
  options: ['Brand impersonation', 'Typosquatting', 'Watering hole', 'Pretexting'],
  answer: 1,
  explanation: 'Typosquatting is specifically about the DOMAIN NAME being a near-miss. Brand impersonation is about the content looking like the company — the copied login page is brand impersonation; the domain is typosquatting.',
},
{
  objective: '2.2',
  stem: 'A caller tells the help desk they are the new regional auditor and needs a password reset before a board meeting in ten minutes. Which technique is the invented backstory?',
  options: ['Impersonation', 'Pretexting', 'Vishing', 'Business email compromise'],
  answer: 1,
  explanation: 'Pretexting is the invented STORY that makes the request plausible. Impersonation is claiming to be a specific real person. The phone as the channel makes it vishing — the objectives list all three separately.',
},
{
  objective: '2.2',
  stem: 'An accounts payable clerk receives an email from the CEO\'s genuine-looking address instructing an urgent supplier payment to a new bank account. Which term BEST fits?',
  options: ['Phishing', 'Business email compromise', 'Pretexting', 'Brand impersonation'],
  answer: 1,
  explanation: 'BEC targets a specific business process using a trusted internal identity. Plain phishing is the broad net cast at many recipients — the specificity of the target and the process is the discriminator.',
},
{
  objective: '2.2',
  stem: 'Attackers compromise an industry association website that engineers at a target company read daily, and serve malware from it. Which vector is this?',
  options: ['Supply chain', 'Watering hole', 'Typosquatting', 'Impersonation'],
  answer: 1,
  explanation: 'Watering hole compromises a site the victims VISIT. Supply chain compromises something they BUY or INSTALL. The binary test is whether the malicious thing entered through browsing or through procurement.',
},
{
  objective: '2.2',
  stem: 'An employee receives a text message claiming a parcel is held and linking to a payment page. Which vector is this?',
  options: ['Vishing', 'Smishing', 'Phishing', 'Instant messaging'],
  answer: 1,
  explanation: 'S for SMS, V for voice. The objectives also list Short Message Service (SMS) as a message-based vector in its own right, but the social engineering technique is smishing.',
},
{
  objective: '2.2',
  stem: 'A vulnerability scan finds a development server exposing an unauthenticated database listener that no application uses. Which 2.2 attack surface does this represent?',
  options: ['Misconfiguration', 'Open service ports', 'Default credentials', 'Unsupported systems and applications'],
  answer: 1,
  explanation: 'Open service ports is the 2.2 attack SURFACE. Misconfiguration is a 2.3 VULNERABILITY. Both are defensible in plain English — the objective the question sits in decides which word is credited.',
},
{
  objective: '2.2',
  stem: 'An organisation discovers that a managed service provider with remote access to its network has been breached, and the attacker pivoted inward. Which vector is this?',
  options: ['Supply chain', 'Insider threat', 'Watering hole', 'Shadow IT'],
  answer: 0,
  explanation: 'The objectives list MSPs, vendors and suppliers under supply chain. The attacker entered through a trusted third party you contracted with, not through something staff visited.',
},
{
  objective: '2.2',
  stem: 'A new network appliance is deployed and reachable with the credentials printed in its manual. Which threat vector is this?',
  options: ['Open service ports', 'Default credentials', 'Unsecure networks', 'Vulnerable software'],
  answer: 1,
  explanation: 'Default credentials is its own bullet in 2.2 and the corresponding hardening technique in 2.5 is "default password changes". Naming both halves is a common question pattern.',
},
{
  objective: '2.2',
  stem: 'Malware is delivered inside a QR code printed on a poster in a building lobby. Which threat vector does the objectives document use for this delivery method?',
  options: ['Image-based', 'File-based', 'Message-based', 'Removable device'],
  answer: 0,
  explanation: 'The objectives list image-based as a vector alongside file-based and message-based. A QR code is an image that carries the payload or destination.',
},

/* ---------------- 2.3 vulnerabilities ---------------- */
{
  objective: '2.3',
  stem: 'An application checks that a file is owned by the user, then opens it. An attacker replaces the file between those two operations. Which vulnerability class is this?',
  options: ['Memory injection', 'Race conditions', 'Buffer overflow', 'Malicious update'],
  answer: 1,
  explanation: 'Any gap between the check and the use is a race condition — the objectives name the two halves time-of-check (TOC) and time-of-use (TOU). If a stem describes timing between two operations, this is the answer.',
},
{
  objective: '2.3',
  stem: 'A guest virtual machine exploits a hypervisor flaw to run code directly on the host. Which vulnerability is this?',
  options: ['Resource reuse', 'Virtual machine (VM) escape', 'Cloud-specific', 'Misconfiguration'],
  answer: 1,
  explanation: 'Escape crosses the isolation boundary. Resource reuse is the different problem of memory or storage being handed to a new tenant with the previous tenant\'s data still present.',
},
{
  objective: '2.3',
  stem: 'A cloud provider allocates a block of storage to a new customer without wiping it, and the previous customer\'s data is readable. Which vulnerability is this?',
  options: ['Virtual machine (VM) escape', 'Resource reuse', 'Data sovereignty', 'Side loading'],
  answer: 1,
  explanation: 'Resource reuse is specifically the failure to sanitise a shared resource between tenants. Nothing crossed an isolation boundary by force, which is what would make it an escape.',
},
{
  objective: '2.3',
  stem: 'A user installs an application package obtained from a website rather than the device\'s official app store. Which mobile vulnerability is this?',
  options: ['Jailbreaking', 'Side loading', 'Malicious update', 'Misconfiguration'],
  answer: 1,
  explanation: 'Side loading installs one app AROUND the store while the OS restrictions remain. Jailbreaking removes those restrictions entirely — the discriminator is whether the platform\'s protections were defeated or merely bypassed for one install.',
},
{
  objective: '2.3',
  stem: 'A vulnerability is being actively exploited and the vendor has not yet released a fix because they only learned of it today. What is this?',
  options: ['End-of-life', 'Legacy', 'Zero-day', 'Misconfiguration'],
  answer: 2,
  explanation: 'Zero-day means no patch exists YET. End-of-life means no patch will EVER come because support has ended. Both leave you unpatched; only one can be fixed by waiting.',
},
{
  objective: '2.3',
  stem: 'An organisation continues running a database server whose vendor stopped issuing security updates two years ago. Which hardware/software vulnerability applies?',
  options: ['Zero-day', 'End-of-life', 'Firmware', 'Malicious update'],
  answer: 1,
  explanation: 'End-of-life is the permanent condition of no further patches. The related consideration in 3.1 is "inability to patch" — the same situation viewed as an architecture trade-off.',
},
{
  objective: '2.3',
  stem: 'Attackers compromise a software vendor\'s build pipeline so that a digitally signed update distributes a backdoor. Which 2.3 application vulnerability does the objectives document name?',
  options: ['Malicious update', 'Memory injection', 'Misconfiguration', 'Race conditions'],
  answer: 0,
  explanation: 'Malicious update is listed explicitly under Application vulnerabilities. Supply chain also appears in 2.3, but when the update MECHANISM is the vector the objectives give you a more specific word — use it.',
},
{
  objective: '2.3',
  stem: 'A web application concatenates user input directly into a database query, allowing an attacker to return all rows of a table. Which vulnerability is this?',
  options: ['Cross-site scripting (XSS)', 'Structured Query Language injection (SQLi)', 'Directory traversal', 'Buffer overflow'],
  answer: 1,
  explanation: 'SQLi manipulates the DATABASE QUERY. XSS injects script that runs in another user\'s BROWSER. The target of the injected content is the discriminator.',
},
{
  objective: '2.3',
  stem: 'An attacker stores a script in a forum post so that it executes in the browser of every subsequent visitor. Which vulnerability is this?',
  options: ['SQLi', 'Cross-site scripting (XSS)', 'Forgery', 'Injection'],
  answer: 1,
  explanation: 'XSS executes in another user\'s browser and targets the site\'s visitors. SQLi targets the database. Both are listed under 2.3 web-based vulnerabilities and are separated by where the injected content runs.',
},
{
  objective: '2.3',
  stem: 'An IoT camera runs an embedded operating system whose vendor ships updates only as full binary images, and none have been released since launch. Which 2.3 hardware vulnerability is MOST directly named?',
  options: ['Firmware', 'Legacy', 'Cloud-specific', 'Cryptographic'],
  answer: 0,
  explanation: 'The objectives list firmware, end-of-life and legacy under Hardware. The stem points at the embedded software image itself, which is firmware.',
},

/* ---------------- 2.4 indicators of malicious activity ---------------- */
{
  objective: '2.4',
  stem: 'Malware spreads across the network to hundreds of hosts without any user opening a file. Which malware type is this?',
  options: ['Virus', 'Worm', 'Trojan', 'Logic bomb'],
  answer: 1,
  explanation: 'A worm self-propagates. A virus needs a host file and a user to run it. A trojan needs the user to run it believing it is something else. Autonomy is the discriminator.',
},
{
  objective: '2.4',
  stem: 'A departing developer leaves code in a payroll system that deletes records if their employee ID stops appearing in the staff table. Which malware type is this?',
  options: ['Trojan', 'Logic bomb', 'Rootkit', 'Worm'],
  answer: 1,
  explanation: 'A logic bomb is defined by its TRIGGER — a date, an event, a condition. A trojan is defined by DISGUISE. Nothing here is pretending to be something else; it is waiting for a condition.',
},
{
  objective: '2.4',
  stem: 'Malware modifies operating system kernel structures so that its own processes and files do not appear in any listing. Which type is this?',
  options: ['Spyware', 'Rootkit', 'Keylogger', 'Bloatware'],
  answer: 1,
  explanation: 'A rootkit is defined by CONCEALMENT at a privileged level. Spyware is defined by what it collects. Malware can be both — the stem here describes only the hiding.',
},
{
  objective: '2.4',
  stem: 'New laptops arrive with trial software and vendor utilities nobody requested, increasing the attack surface. Which term does SY0-701 use?',
  options: ['Potentially unwanted program', 'Bloatware', 'Spyware', 'Trojan'],
  answer: 1,
  explanation: 'PUP is the industry word and appears only in the acronym list. Bloatware is the 2.4 malware bullet, and it is the credited answer.',
},
{
  objective: '2.4',
  stem: 'An attacker tries the single password "Autumn2026!" against every account in the directory, once each. Which password attack is this?',
  options: ['Brute force', 'Spraying', 'Credential replay', 'Birthday'],
  answer: 1,
  explanation: 'Spraying is wide and shallow — one password across many accounts, specifically to stay under lockout thresholds. Brute force is deep against one account and triggers lockout quickly.',
},
{
  objective: '2.4',
  stem: 'A researcher demonstrates two different files that produce an identical SHA-1 digest. What is the RESULT called?',
  options: ['Birthday', 'Collision', 'Downgrade', 'Forgery'],
  answer: 1,
  explanation: 'A collision is the RESULT — two inputs, one hash. A birthday attack is the probability METHOD used to find one efficiently. The stem asks what the outcome is called.',
},
{
  objective: '2.4',
  stem: 'An on-path attacker strips the TLS 1.3 offer from a handshake so the session negotiates an obsolete cipher suite. Which cryptographic attack is this?',
  options: ['Collision', 'Downgrade', 'Birthday', 'Replay'],
  answer: 1,
  explanation: 'On-path is the POSITION the attacker holds; downgrade is what they DO from it. The question asks for the cryptographic attack, so the position alone is not the answer.',
},
{
  objective: '2.4',
  stem: 'A single account authenticates from London at 09:14 and from São Paulo at 09:31. Which indicator is this?',
  options: ['Concurrent session usage', 'Impossible travel', 'Account lockout', 'Out-of-cycle logging'],
  answer: 1,
  explanation: 'Impossible travel is about GEOGRAPHY versus elapsed time. Concurrent session usage is two live sessions regardless of location — it would apply even if both were in the same building.',
},
{
  objective: '2.4',
  stem: 'A nightly batch job normally writes its log at 23:00. Entries now appear at 04:00 as well. Which indicator does the objectives document name?',
  options: ['Missing logs', 'Out-of-cycle logging', 'Resource consumption', 'Published/documented'],
  answer: 1,
  explanation: 'Out-of-cycle logging means the log EXISTS but at the wrong time. Missing logs means it is not there at all. Questions trade on which of the two the stem actually describes.',
},
{
  objective: '2.4',
  stem: 'Investigating a suspected breach, an analyst finds that the security event log on a server is empty for the three days around the intrusion. Which indicator is this?',
  options: ['Out-of-cycle logging', 'Missing logs', 'Blocked content', 'Resource inaccessibility'],
  answer: 1,
  explanation: 'Absence is itself the indicator — logs that should exist and do not. This is one of the nine named indicators, and clearing logs is a standard anti-forensic step.',
},
{
  objective: '2.4',
  stem: 'A DDoS attack sends small DNS queries with a spoofed source address to open resolvers, which return much larger responses to the victim. Which characteristic does "much larger responses" describe?',
  options: ['Reflected', 'Amplified', 'On-path', 'Malicious code'],
  answer: 1,
  explanation: 'Reflected means the response goes to the SPOOFED victim rather than the sender. Amplified means the response is far LARGER than the request. This attack is both, but the stem asks about the size multiplier.',
},
{
  objective: '2.4',
  stem: 'A web application accepts a filename parameter and an attacker submits ../../../etc/passwd to read a system file. Which application attack is this?',
  options: ['Injection', 'Directory traversal', 'Forgery', 'Privilege escalation'],
  answer: 1,
  explanation: 'Directory traversal escapes the intended PATH. Injection inserts code or query syntax into an interpreter. Nothing is being executed here — a file outside the web root is simply being read.',
},
{
  objective: '2.4',
  stem: 'An attacker captures a Kerberos ticket from the network and presents it later to authenticate as that user. Which network attack does the objectives document name?',
  options: ['On-path', 'Credential replay', 'Forgery', 'Spraying'],
  answer: 1,
  explanation: 'The objectives list "Replay" under application attacks and "Credential replay" under network attacks. Because what was captured and reused is authentication material, credential replay is the matching bullet.',
},
{
  objective: '2.4',
  stem: 'An attacker clones the identifier from an employee badge by reading it from a short distance in a lift. Which physical attack is this?',
  options: ['Brute force', 'Radio frequency identification (RFID) cloning', 'Environmental', 'Impersonation'],
  answer: 1,
  explanation: 'RFID cloning is listed under physical attacks in 2.4. Brute force in that same list means physically forcing a door or barrier, not guessing a password.',
},
{
  objective: '2.4',
  stem: 'An attacker deliberately raises the temperature in a server room by tampering with HVAC controls until systems shut down. Which physical attack category applies?',
  options: ['Environmental', 'Brute force', 'Resource consumption', 'Service disruption'],
  answer: 0,
  explanation: 'Environmental attacks manipulate the conditions systems depend on — power, cooling, water. Resource consumption is an INDICATOR you would observe, and service disruption is a 2.1 motivation, not an attack type.',
},
{
  objective: '2.4',
  stem: 'A standard user exploits an unpatched local flaw to obtain SYSTEM-level rights on a workstation. Which application attack is this?',
  options: ['Privilege escalation', 'Injection', 'Forgery', 'Replay'],
  answer: 0,
  explanation: 'Privilege escalation is gaining rights beyond those assigned. It is listed under application attacks in 2.4, and the discriminator is that the attacker already had some access and increased it.',
},

/* ---------------- 2.5 mitigation techniques ---------------- */
{
  objective: '2.5',
  stem: 'To limit lateral movement, a network is divided into zones with filtering between them so a compromise in one cannot reach the others. Which mitigation is this?',
  options: ['Isolation', 'Segmentation', 'Access control list (ACL)', 'Least privilege'],
  answer: 1,
  explanation: 'Segmentation divides the network into zones. Isolation cuts one host off entirely. The stem describes a structural division of the whole network, not the removal of a single machine.',
},
{
  objective: '2.5',
  stem: 'Workstations are configured so that only executables on an approved list may run, and everything else is blocked by default. Which mitigation is this?',
  options: ['Configuration enforcement', 'Application allow list', 'Least privilege', 'Application security'],
  answer: 1,
  explanation: 'Application allow list names the specific permitted software. Configuration enforcement is the different control of making settings stick and revert if changed.',
},
{
  objective: '2.5',
  stem: 'A retired file server is formally removed from service, its data destroyed and its entries deleted from the asset register. Which 2.5 mitigation is this?',
  options: ['Sanitization', 'Decommissioning', 'Isolation', 'Segmentation'],
  answer: 1,
  explanation: 'Decommissioning is the 2.5 process for retiring a system. Sanitization is the 4.2 disposal step INSIDE it that destroys the data. The stem describes the whole retirement, not just the wipe.',
},
{
  objective: '2.5',
  stem: 'Which hardening technique does the objectives document name for closing services a server does not need to expose?',
  options: ['Disabling ports/protocols', 'Removal of unnecessary software', 'Host-based firewall', 'Application allow list'],
  answer: 0,
  explanation: 'Disabling ports/protocols turns off the listening service. Removal of unnecessary software takes the package off the machine entirely — one closes a door, the other removes the room.',
},
{
  objective: '2.5',
  stem: 'An endpoint is configured to inspect and block malicious behaviour locally, on the host itself, rather than at the network boundary. Which hardening technique does the objectives document name?',
  options: ['Host-based intrusion prevention system (HIPS)', 'Network-based intrusion detection system (NIDS)', 'Host-based firewall', 'Installation of endpoint protection'],
  answer: 0,
  explanation: 'HIPS is named explicitly in the 2.5 hardening list and it BLOCKS. A host-based firewall filters connections rather than behaviour; endpoint protection is the broader antimalware category.',
},
{
  objective: '2.5',
  stem: 'A helpdesk technician\'s account is changed so it can reset passwords but no longer create domain administrators. Which mitigation does this apply?',
  options: ['Least privilege', 'Access control list (ACL)', 'Permissions', 'Isolation'],
  answer: 0,
  explanation: 'Least privilege is the principle of granting only what the role needs. Permissions and ACLs are the mechanisms that express it — the stem describes the principle being applied by reducing rights to the task.',
},
];
