// Domain 3 — Security Architecture (18%)

export default [

/* ---------------- 3.1 architecture models ---------------- */
{
  objective: '3.1',
  stem: 'Before migrating, a team documents which security tasks the cloud provider performs and which remain the customer\'s. What is this document called?',
  options: ['Service-level agreement (SLA)', 'Responsibility matrix', 'Memorandum of understanding', 'Right-to-audit clause'],
  answer: 1,
  explanation: 'The responsibility matrix divides DUTIES. An SLA commits to PERFORMANCE and is a 5.3 agreement type. Both are cloud contract documents and questions swap them deliberately.',
},
{
  objective: '3.1',
  stem: 'A team defines its entire cloud environment in declarative template files held in a Git repository and applied by a pipeline. Which 3.1 concept is this?',
  options: ['Automation', 'Infrastructure as code (IaC)', 'Serverless', 'Containerization'],
  answer: 1,
  explanation: 'IaC is the 3.1 architecture term for infrastructure defined in version-controlled files. Automation is the 4.7 benefit you get from it — the objective the question sits in decides the credited word.',
},
{
  objective: '3.1',
  stem: 'A control system is kept on a network with no physical connection of any kind to any other network. Which term applies?',
  options: ['Logical segmentation', 'Air-gapped', 'Software-defined networking (SDN)', 'Screened subnet'],
  answer: 1,
  explanation: 'Air gap is PHYSICAL isolation — no cable, no wireless. Logical segmentation is VLANs and routing rules on shared hardware, which can be misconfigured; an air gap cannot.',
},
{
  objective: '3.1',
  stem: 'An application is split into independently deployable components that communicate over APIs, each owning its own data. Which architecture is this?',
  options: ['Serverless', 'Microservices', 'Containerization', 'Virtualization'],
  answer: 1,
  explanation: 'Microservices is about how the APPLICATION is decomposed. Containerization is a packaging and runtime technology often used to deploy them — the stem describes the decomposition, not the packaging.',
},
{
  objective: '3.1',
  stem: 'Several workloads share a single operating system kernel while remaining isolated from each other. Which technology is this?',
  options: ['Virtualization', 'Containerization', 'Serverless', 'Microservices'],
  answer: 1,
  explanation: 'Containers share the host KERNEL; virtual machines each carry a full guest OS. That single sentence is the discriminator, and it is why container escape and VM escape are different risks.',
},
{
  objective: '3.1',
  stem: 'A manufacturing plant runs equipment controllers that must respond to inputs within guaranteed, fixed time limits. Which architecture does the objectives document name?',
  options: ['Embedded systems', 'Real-time operating system (RTOS)', 'ICS/SCADA', 'IoT'],
  answer: 1,
  explanation: 'RTOS is defined by the GUARANTEED TIMING requirement. Embedded systems is the broader category of purpose-built computers; ICS/SCADA is the industrial control application layer above.',
},
{
  objective: '3.1',
  stem: 'An organisation buys cyber insurance to cover the cost of a potential breach. Which 3.1 architecture consideration does this illustrate?',
  options: ['Risk transference', 'Resilience', 'Ease of recovery', 'Cost'],
  answer: 0,
  explanation: 'Risk transference moves the financial loss to another party. It appears in 3.1 as an architecture consideration and again in 5.2 as the "Transfer" risk management strategy — the same idea in two objectives.',
},
{
  objective: '3.1',
  stem: 'A medical device runs a fixed software image that the manufacturer will not permit the hospital to modify, and no updates are offered. Which 3.1 consideration does this MOST directly raise?',
  options: ['Patch availability', 'Inability to patch', 'Ease of deployment', 'Compute'],
  answer: 1,
  explanation: 'The objectives list both. Patch availability asks whether a patch EXISTS; inability to patch is the stronger condition that you cannot apply one even if it does. The stem says modification is not permitted.',
},
{
  objective: '3.1',
  stem: 'Code runs on demand in response to events, with the provider managing all underlying compute. Which model is this?',
  options: ['Serverless', 'Infrastructure as code (IaC)', 'Microservices', 'On-premises'],
  answer: 0,
  explanation: 'Serverless removes the server you manage — you supply only the function. Servers still exist; the point is that patching and capacity are no longer in your responsibility column of the matrix.',
},
{
  objective: '3.1',
  stem: 'Which security implication is the MOST significant difference between a centralized and a decentralized architecture?',
  options: [
    'Centralized offers consistent policy enforcement but is a larger single point of failure',
    'Decentralized is always more secure because there is no single target',
    'Centralized cannot use encryption in transit',
    'Decentralized removes the need for identity management',
  ],
  answer: 0,
  explanation: 'The trade-off is uniformity against blast radius. Decentralized spreads risk but makes consistent policy harder — neither is inherently more secure, which is why the objectives list it as a comparison.',
},

/* ---------------- 3.2 securing enterprise infrastructure ---------------- */
{
  objective: '3.2',
  stem: 'Administrators must connect to a single hardened host, and only from there can they reach production servers. What is that host called?',
  options: ['Proxy server', 'Jump server', 'Load balancer', 'Screened subnet'],
  answer: 1,
  explanation: 'You log INTO a jump server and work from it. A proxy forwards traffic on your behalf and you never authenticate to it as a shell. The stem says administrators connect to it, then onward.',
},
{
  objective: '3.2',
  stem: 'A network appliance receives a copy of traffic from a switch port and analyses it without sitting in the forwarding path. Which device attribute describes this placement?',
  options: ['Active', 'Inline', 'Tap/monitor', 'Fail-open'],
  answer: 2,
  explanation: 'Inline versus tap/monitor is about PLACEMENT in the traffic path. Active versus passive is about whether the device can ACT on what it sees. Questions swap these two axes deliberately.',
},
{
  objective: '3.2',
  stem: 'A security appliance is configured so that if it crashes, all traffic is blocked until it recovers. Which failure mode is this?',
  options: ['Fail-open', 'Fail-closed', 'High availability', 'Active/passive'],
  answer: 1,
  explanation: 'Fail-closed favours security at the cost of availability; fail-open favours availability at the cost of security. Name the property the scenario chose to protect.',
},
{
  objective: '3.2',
  stem: 'Which standard authenticates a device at the switch port before granting it any network access?',
  options: ['802.1X', 'Network access control (NAC)', 'RADIUS', 'EAP'],
  answer: 0,
  explanation: '802.1X is the 3.2 port security standard. EAP is the authentication framework carried inside it, RADIUS is the back-end server, and NAC is the broader 4.5 enterprise capability built on top.',
},
{
  objective: '3.2',
  stem: 'An organisation wants SD-WAN connectivity combined with cloud-delivered secure web gateway, CASB and Zero Trust access in a single service. Which term describes this?',
  options: ['Software-defined wide area network (SD-WAN)', 'Secure access service edge (SASE)', 'Unified threat management (UTM)', 'Virtual private network (VPN)'],
  answer: 1,
  explanation: 'SD-WAN is the networking alone. SASE is SD-WAN with the security stack folded in and delivered from the cloud edge. The stem lists security services on top of connectivity, which is the SASE definition.',
},
{
  objective: '3.2',
  stem: 'Which device inspects HTTP requests specifically to block SQL injection and cross-site scripting before they reach an application?',
  options: ['Next-generation firewall (NGFW)', 'Web application firewall (WAF)', 'Unified threat management (UTM)', 'Proxy server'],
  answer: 1,
  explanation: 'A WAF understands ONE protocol deeply and is placed in front of a specific application. An NGFW inspects many protocols and adds identity and application awareness across the estate.',
},
{
  objective: '3.2',
  stem: 'A firewall makes decisions based only on source and destination IP address and port. At which layer is it operating?',
  options: ['Layer 4', 'Layer 7', 'Layer 2', 'Layer 3 only'],
  answer: 0,
  explanation: 'Layer 4 filtering uses ports and addresses. Layer 7 understands the application protocol and can distinguish, say, one HTTP method from another. The objectives phrase this pairing as "Layer 4/Layer 7".',
},
{
  objective: '3.2',
  stem: 'An organisation places its public web servers in a separate network segment reachable from the internet but unable to initiate connections into the internal LAN. What is this segment called?',
  options: ['Screened subnet', 'Security zone', 'Air gap', 'Jump network'],
  answer: 0,
  explanation: 'Screened subnet is the objectives\' term (4.5, under Firewall) for what used to be called a DMZ. Security zone is the more general 3.2 concept of which a screened subnet is one instance.',
},
{
  objective: '3.2',
  stem: 'Remote workers connect through an encrypted tunnel that carries all their traffic back to the corporate network. Which secure communication method is this?',
  options: ['Virtual private network (VPN)', 'Secure access service edge (SASE)', 'Proxy server', 'Jump server'],
  answer: 0,
  explanation: 'A VPN creates the encrypted tunnel. Tunneling protocols named in the objectives are TLS and IPSec — the VPN is the service, those are the mechanisms.',
},

/* ---------------- 3.3 protecting data ---------------- */
{
  objective: '3.3',
  stem: 'Customer records are currently loaded into an application server\'s memory and being processed. Which data state is this?',
  options: ['Data at rest', 'Data in transit', 'Data in use', 'Data in motion'],
  answer: 2,
  explanation: 'Three states only: at rest on storage, in transit on the network, in use in memory. "Data in motion" is a synonym for in transit and is not the objectives\' wording.',
},
{
  objective: '3.3',
  stem: 'A company\'s proprietary manufacturing process is protected commercially by never being published rather than by registration. Which data type is this?',
  options: ['Intellectual property', 'Trade secret', 'Regulated', 'Legal information'],
  answer: 1,
  explanation: 'Trade secret is the subset of intellectual property whose value depends entirely on secrecy. Both appear in the 3.3 list, and the discriminator is whether disclosure destroys the value.',
},
{
  objective: '3.3',
  stem: 'A European regulator asserts that data held in its jurisdiction is subject to its national law regardless of the owning company\'s headquarters. Which concept is this?',
  options: ['Geolocation', 'Data sovereignty', 'Geographic restrictions', 'Data classification'],
  answer: 1,
  explanation: 'Sovereignty is the LEGAL consequence of where data sits. Geolocation is simply knowing where it is; geographic restrictions is the control you apply to keep it somewhere.',
},
{
  objective: '3.3',
  stem: 'An organisation blocks access to a dataset from any IP address outside its home country. Which method to secure data is this?',
  options: ['Data sovereignty', 'Geographic restrictions', 'Segmentation', 'Permission restrictions'],
  answer: 1,
  explanation: 'Geographic restrictions is the listed CONTROL. Sovereignty is the legal driver that made the control necessary — the stem describes the enforcement, not the reason.',
},
{
  objective: '3.3',
  stem: 'Which data classification does the objectives document use for information whose loss would halt core business operations?',
  options: ['Sensitive', 'Critical', 'Restricted', 'Confidential'],
  answer: 1,
  explanation: 'The six labels are sensitive, confidential, public, restricted, private and critical. Critical is about operational importance, while the others are largely about who may see it.',
},
{
  objective: '3.3',
  stem: 'A log file records events in a format designed for machines to parse and not intended for people to read directly. Which 3.3 data type does the objectives document use?',
  options: ['Human- and non-human-readable', 'Regulated', 'Financial information', 'Legal information'],
  answer: 0,
  explanation: 'The objectives pair these as a single bullet. It is one of the easiest terms to miss on a blank-paper reproduction because it does not sound like a classification at all.',
},

/* ---------------- 3.4 resilience and recovery ---------------- */
{
  objective: '3.4',
  stem: 'An alternate facility is fully equipped, holds current replicated data and can take production traffic within minutes. Which site type is this?',
  options: ['Cold', 'Warm', 'Hot', 'Geographic dispersion'],
  answer: 2,
  explanation: 'Hot is running now with current data. Warm has equipment but needs data restored and time. Cold is space and power only. Time-to-service is the discriminator.',
},
{
  objective: '3.4',
  stem: 'A company runs the same critical workload on two different cloud providers so that an outage at one does not stop the service. Which 3.4 concept is this?',
  options: ['Platform diversity', 'Multi-cloud systems', 'Geographic dispersion', 'Load balancing'],
  answer: 1,
  explanation: 'Multi-cloud is more than one PROVIDER. Platform diversity is more than one TECHNOLOGY stack — using two different firewall vendors is platform diversity even in one data centre.',
},
{
  objective: '3.4',
  stem: 'A database writes a continuous record of every change so that it can be restored to any chosen point in time. Which backup concept is this?',
  options: ['Snapshots', 'Replication', 'Journaling', 'Frequency'],
  answer: 2,
  explanation: 'Journaling logs the CHANGES themselves. A snapshot captures the STATE at one moment. Replication continuously copies to another location but does not by itself let you rewind.',
},
{
  objective: '3.4',
  stem: 'The incident response team meets in a conference room and talks through their response to a simulated ransomware outbreak. No systems are touched. Which test type is this?',
  options: ['Simulation', 'Tabletop exercise', 'Fail over', 'Parallel processing'],
  answer: 1,
  explanation: 'Tabletop is discussion only. Simulation actually exercises the systems or the people. The phrase "no systems are touched" is the discriminator the exam relies on.',
},
{
  objective: '3.4',
  stem: 'A disaster recovery test brings up the secondary site and runs it alongside production, comparing outputs without cutting over. Which test type is this?',
  options: ['Fail over', 'Parallel processing', 'Tabletop exercise', 'Simulation'],
  answer: 1,
  explanation: 'Parallel processing runs both and compares. Fail over actually switches production to the secondary. The stem explicitly says there is no cutover.',
},
{
  objective: '3.4',
  stem: 'Which power component keeps servers running for the few minutes between a mains failure and a generator reaching full output?',
  options: ['Generators', 'Uninterruptible power supply (UPS)', 'Power distribution unit', 'Capacity planning'],
  answer: 1,
  explanation: 'A UPS covers the gap using stored energy; a generator sustains the load for hours but takes time to start. The objectives list both, and the discriminator is duration versus immediacy.',
},
{
  objective: '3.4',
  stem: 'An organisation assesses whether it will have enough trained responders to sustain a 24-hour incident before it happens. Which 3.4 activity is this?',
  options: ['Capacity planning — people', 'Continuity of operations', 'Testing', 'Resilience'],
  answer: 0,
  explanation: 'Capacity planning in the objectives has three named dimensions: people, technology and infrastructure. Headcount is explicitly one of them, which surprises candidates who read capacity as purely technical.',
},
{
  objective: '3.4',
  stem: 'Which statement correctly distinguishes load balancing from clustering?',
  options: [
    'Load balancing distributes requests across independent nodes; clustering makes several nodes act as one system',
    'Load balancing requires shared storage; clustering does not',
    'Clustering only works in the cloud; load balancing only on premises',
    'They are two names for the same technique',
  ],
  answer: 0,
  explanation: 'The objectives pair these deliberately as "load balancing vs. clustering". Balancing spreads work across servers that do not know about each other; a cluster presents itself as a single logical system.',
},
];
