// Domain 4 — Security Operations (28%)
//
// The heaviest domain on the blueprint and the one this bank weights hardest.

export default [

/* ---------------- 4.1 securing computing resources ---------------- */
{
  objective: '4.1',
  stem: 'An organisation defines the approved starting configuration for all new web servers, deploys it via automation, and audits drift monthly. What is this configuration called?',
  options: ['Benchmark', 'Secure baseline', 'Standard operating procedure', 'Guard rail'],
  answer: 1,
  explanation: 'A secure baseline is yours, and the objectives give it three verbs: establish, deploy, maintain. A benchmark is the EXTERNAL standard (4.4) you measure against, such as a CIS benchmark.',
},
{
  objective: '4.1',
  stem: 'Before installing wireless access points across a new floor, engineers walk the space measuring signal strength and interference. What is this activity called?',
  options: ['Heat map', 'Site survey', 'Capacity planning', 'Benchmark'],
  answer: 1,
  explanation: 'The survey is the ACTIVITY; the heat map is the OUTPUT it produces. The objectives list both under wireless installation considerations and questions ask for one while offering the other.',
},
{
  objective: '4.1',
  stem: 'A company purchases and owns all mobile devices but allows employees to use them for personal calls and apps. Which deployment model is this?',
  options: ['Bring your own device (BYOD)', 'Corporate-owned, personally enabled (COPE)', 'Choose your own device (CYOD)', 'Mobile device management (MDM)'],
  answer: 1,
  explanation: 'COPE: the company buys and owns it, personal use permitted. CYOD: the employee picks from an approved list. BYOD: the employee owns it. Ownership plus who chose it is the discriminator.',
},
{
  objective: '4.1',
  stem: 'Which wireless security standard replaces the WPA2 pre-shared key handshake with Simultaneous Authentication of Equals?',
  options: ['WPA', 'WPA2 Enterprise', 'Wi-Fi Protected Access 3 (WPA3)', 'WEP'],
  answer: 2,
  explanation: 'SAE is WPA3\'s headline change and it defeats offline dictionary attacks against captured handshakes. WPA3 is the only wireless standard named in objective 4.1.',
},
{
  objective: '4.1',
  stem: 'An application rejects any submitted date field that is not in ISO format and any name longer than 64 characters, before processing. Which application security technique is this?',
  options: ['Static code analysis', 'Input validation', 'Secure cookies', 'Sandboxing'],
  answer: 1,
  explanation: 'Input validation runs at RUNTIME against data. Static code analysis runs before deployment against source code. Both are 4.1 application security bullets, split by when they act.',
},
{
  objective: '4.1',
  stem: 'A developer applies a cryptographic signature to a compiled application so users can verify it came from the publisher and has not been altered. Which technique is this?',
  options: ['Code signing', 'Static code analysis', 'Hashing', 'Secure cookies'],
  answer: 0,
  explanation: 'Code signing proves ORIGIN and INTEGRITY of a binary. A plain hash proves integrity only — it cannot tell you who produced the file, because anyone can publish a hash.',
},
{
  objective: '4.1',
  stem: 'A web application sets its session cookie with the Secure and HttpOnly attributes. Which 4.1 application security control is this?',
  options: ['Input validation', 'Secure cookies', 'Code signing', 'Sandboxing'],
  answer: 1,
  explanation: 'Secure cookies is a named 4.1 bullet. Secure restricts the cookie to HTTPS; HttpOnly hides it from JavaScript, which limits what an XSS flaw can steal.',
},
{
  objective: '4.1',
  stem: 'A suspicious attachment is executed in an isolated, instrumented environment so analysts can watch its behaviour safely. Which technique is this?',
  options: ['Isolation', 'Sandboxing', 'Quarantine', 'Segmentation'],
  answer: 1,
  explanation: 'Sandboxing exists to OBSERVE safely. Isolation exists to CONTAIN. Quarantine (4.4) is what you do to a file once you have decided it is bad.',
},
{
  objective: '4.1',
  stem: 'Which of the following is named in the objectives as a hardening TARGET rather than a hardening technique?',
  options: ['Host-based firewall', 'ICS/SCADA', 'Disabling ports/protocols', 'Default password changes'],
  answer: 1,
  explanation: 'The 4.1 hardening targets list is the set of THINGS you harden — workstations, switches, routers, servers, ICS/SCADA, embedded systems, RTOS, IoT. The other three options are 2.5 hardening techniques.',
},

/* ---------------- 4.2 asset management ---------------- */
{
  objective: '4.2',
  stem: 'Decommissioned drives are degaussed and overwritten so no data can be recovered, but the drives are then resold. Which disposal step is this?',
  options: ['Destruction', 'Sanitization', 'Certification', 'Data retention'],
  answer: 1,
  explanation: 'Sanitization removes the data but keeps the hardware usable. Destruction makes the hardware unusable. The stem says the drives are resold, which rules out destruction.',
},
{
  objective: '4.2',
  stem: 'A disposal vendor provides a signed document confirming which serial numbers were destroyed and by what method. Which 4.2 element is this?',
  options: ['Attestation', 'Certification', 'Sanitization', 'Enumeration'],
  answer: 1,
  explanation: 'Certification is the 4.2 disposal artifact — proof the destruction happened. Attestation is the 5.4/5.5 compliance statement that a control is in place, a different objective and a different purpose.',
},
{
  objective: '4.2',
  stem: 'An organisation runs an automated discovery scan to find every device attached to its networks, including ones not in the asset register. Which activity is this?',
  options: ['Inventory', 'Enumeration', 'Classification', 'Acquisition'],
  answer: 1,
  explanation: 'The objectives pair inventory and enumeration under monitoring/asset tracking. The inventory is the RECORD you hold; enumeration is the act of DISCOVERING what is actually there.',
},
{
  objective: '4.2',
  stem: 'Each new server is assigned a named business owner and a data classification at the point it is commissioned. Which 4.2 activity is this?',
  options: ['Assignment/accounting', 'Monitoring/asset tracking', 'Acquisition/procurement process', 'Disposal/decommissioning'],
  answer: 0,
  explanation: 'The objectives list ownership and classification as the two components of assignment/accounting. Acquisition is the earlier step of buying it; tracking is the ongoing step of knowing where it is.',
},

/* ---------------- 4.3 vulnerability management ---------------- */
{
  objective: '4.3',
  stem: 'A vulnerability is published with the reference CVE-2026-11842 and a severity of 8.8. Which standard produced the 8.8?',
  options: ['Common Vulnerability Enumeration (CVE)', 'Common Vulnerability Scoring System (CVSS)', 'Security Content Automation Protocol (SCAP)', 'Exposure factor'],
  answer: 1,
  explanation: 'CVE is the IDENTIFIER; CVSS is the SCORE. One names the vulnerability, the other rates it. Questions give you both and ask which produced which.',
},
{
  objective: '4.3',
  stem: 'A scanner reports a critical flaw. Manual testing confirms the affected component is not installed. What is the finding?',
  options: ['False negative', 'False positive', 'Exception', 'Compensating control'],
  answer: 1,
  explanation: '"Positive" always means the scanner SAID something. A false positive is crying wolf. A false negative is silence where there should have been an alert — the more dangerous of the two.',
},
{
  objective: '4.3',
  stem: 'An organisation publishes a policy inviting outside researchers to report flaws safely, and pays them for valid findings. Which term does the objectives document use for the payment element?',
  options: ['Responsible disclosure program', 'Bug bounty program', 'Penetration testing', 'System/process audit'],
  answer: 1,
  explanation: 'Bug bounty sits UNDER responsible disclosure in the objectives and adds the reward. The disclosure programme can exist without any payment at all.',
},
{
  objective: '4.3',
  stem: 'A build pipeline checks every third-party library against a database of known vulnerable versions. Which identification method is this?',
  options: ['Static analysis', 'Dynamic analysis', 'Package monitoring', 'Vulnerability scan'],
  answer: 2,
  explanation: 'Package monitoring checks DEPENDENCIES you imported. Static analysis checks code you WROTE. Dynamic analysis runs the application and watches it behave.',
},
{
  objective: '4.3',
  stem: 'A team decides not to patch a legacy system, documents the business justification, obtains sign-off and adds network restrictions instead. Which two 4.3 responses are in play?',
  options: [
    'Exceptions and exemptions, plus compensating controls',
    'Patching, plus validation of remediation',
    'Insurance, plus segmentation only',
    'Rescanning, plus verification',
  ],
  answer: 0,
  explanation: 'The documented decision not to patch is an exception/exemption; the network restrictions standing in for the patch are a compensating control. Both are named 4.3 vulnerability responses.',
},
{
  objective: '4.3',
  stem: 'After a patch is applied, the team runs the scanner again against the same host to confirm the finding no longer appears. Which validation activity is this?',
  options: ['Verification', 'Rescanning', 'Audit', 'Confirmation'],
  answer: 1,
  explanation: 'Rescanning is the specific act of running the scanner again. Verification is the broader conclusion the objectives list alongside it, and audit is the independent check by someone else.',
},
{
  objective: '4.3',
  stem: 'A threat intelligence source aggregates indicators from publicly available websites, forums and DNS records at no cost. Which feed type is this?',
  options: ['Proprietary/third-party', 'Open-source intelligence (OSINT)', 'Information-sharing organization', 'Dark web'],
  answer: 1,
  explanation: 'OSINT is drawn from public sources. An information-sharing organization is a members-only community such as an ISAC; proprietary feeds are commercial products you buy.',
},

/* ---------------- 4.4 alerting and monitoring ---------------- */
{
  objective: '4.4',
  stem: 'A detection rule fires two thousand times a day on legitimate backup traffic. Analysts adjust its threshold and exclusions. Which activity is this?',
  options: ['Quarantine', 'Alert tuning', 'Archiving', 'Log aggregation'],
  answer: 1,
  explanation: 'Alert tuning changes the RULE so it stops producing noise. Quarantine acts on a FILE or host. Both appear under alert response and remediation, and questions turn on which object is being changed.',
},
{
  objective: '4.4',
  stem: 'Which tool provides a standardised, machine-readable way to express security configuration checks so scanners from different vendors can consume them?',
  options: ['Benchmarks', 'Security Content Automation Protocol (SCAP)', 'NetFlow', 'Simple Network Management Protocol (SNMP) traps'],
  answer: 1,
  explanation: 'SCAP is the FORMAT. A benchmark is CONTENT expressed in that format. The stem asks about interoperability between tools, which is a property of the format.',
},
{
  objective: '4.4',
  stem: 'A monitoring system records summarised metadata about every conversation on the network — source, destination, ports, bytes — but not the contents. Which tool is this?',
  options: ['Packet captures', 'NetFlow', 'SIEM', 'Antivirus'],
  answer: 1,
  explanation: 'NetFlow is metadata about conversations. A packet capture (4.9) holds the payload. "But not the contents" is the discriminator.',
},
{
  objective: '4.4',
  stem: 'A network device sends an unsolicited alert to the management station the moment an interface goes down. Which mechanism is this?',
  options: ['SNMP traps', 'NetFlow', 'Log aggregation', 'Agents/agentless'],
  answer: 0,
  explanation: 'A trap is DEVICE-INITIATED — the device speaks without being asked. Ordinary SNMP polling is the manager asking. The word "unsolicited" is the tell.',
},
{
  objective: '4.4',
  stem: 'Logs from firewalls, servers and applications are collected into one platform where they are normalised and correlated to raise alerts. Which tool is this?',
  options: ['NetFlow', 'Security information and event management (SIEM)', 'Data loss prevention (DLP)', 'Vulnerability scanners'],
  answer: 1,
  explanation: 'A SIEM aggregates and CORRELATES across sources. Log aggregation alone would collect them; the correlation and alerting is what makes it a SIEM.',
},
{
  objective: '4.4',
  stem: 'An organisation must retain security logs for seven years but only needs the last 90 days searchable. Which monitoring activity covers the older data?',
  options: ['Archiving', 'Log aggregation', 'Alerting', 'Reporting'],
  answer: 0,
  explanation: 'Archiving is the named 4.4 activity for long-term retention of data you are no longer actively querying. It is the activity most often forgotten when reproducing the list.',
},

/* ---------------- 4.5 enterprise capabilities ---------------- */
{
  objective: '4.5',
  stem: 'A domain owner publishes a DNS record listing which mail servers are permitted to send mail for that domain. Which email security mechanism is this?',
  options: ['DomainKeys Identified Mail (DKIM)', 'Sender Policy Framework (SPF)', 'Domain-based Message Authentication Reporting and Conformance (DMARC)', 'Gateway'],
  answer: 1,
  explanation: 'SPF authorises the SENDING SERVER. DKIM signs the MESSAGE. DMARC is the policy on top saying what to do when either fails. This three-way split is tested every sitting.',
},
{
  objective: '4.5',
  stem: 'A domain owner publishes a policy instructing receiving servers to quarantine mail that fails authentication, and to send aggregate reports back. Which mechanism is this?',
  options: ['Sender Policy Framework (SPF)', 'DomainKeys Identified Mail (DKIM)', 'Domain-based Message Authentication Reporting and Conformance (DMARC)', 'Secure/Multipurpose Internet Mail Extensions'],
  answer: 2,
  explanation: 'Only DMARC carries a POLICY and a REPORTING address. SPF and DKIM produce results; DMARC decides what those results mean and tells you about them.',
},
{
  objective: '4.5',
  stem: 'A resolver refuses to return an address for domains on a malicious-domain list, so clients cannot reach them. Which capability is this?',
  options: ['Web filter', 'DNS filtering', 'Network access control (NAC)', 'Block rules'],
  answer: 1,
  explanation: 'DNS filtering blocks the LOOKUP, before any connection is attempted. A web filter inspects the HTTP request itself and can categorise the page — it needs the connection to exist.',
},
{
  objective: '4.5',
  stem: 'An agent computes a hash of critical system binaries hourly and alerts when one changes unexpectedly. Which capability is this?',
  options: ['Endpoint detection and response (EDR)', 'File integrity monitoring', 'Data loss prevention (DLP)', 'Antivirus'],
  answer: 1,
  explanation: 'FIM watches specific files for CHANGE. EDR watches BEHAVIOUR and can respond. The stem describes hashing and comparison, not behavioural analysis.',
},
{
  objective: '4.5',
  stem: 'A system blocks an email containing a spreadsheet of customer card numbers from leaving the organisation. Which capability is this?',
  options: ['File integrity monitoring', 'Data loss prevention (DLP)', 'Web filter', 'User behavior analytics'],
  answer: 1,
  explanation: 'DLP inspects data in motion, at rest or in use against content rules and blocks exfiltration. The trigger here is the CONTENT of the attachment, which is DLP\'s defining behaviour.',
},
{
  objective: '4.5',
  stem: 'A platform flags an accountant who suddenly begins accessing engineering file shares at 03:00, behaviour unlike their own history. Which capability is this?',
  options: ['Security information and event management (SIEM)', 'User behavior analytics', 'Endpoint detection and response (EDR)', 'Network access control (NAC)'],
  answer: 1,
  explanation: 'UBA baselines an individual against THEIR OWN history. A SIEM correlates events across sources but does not inherently model one person\'s normal behaviour.',
},
{
  objective: '4.5',
  stem: 'Windows workstations receive their security settings centrally from Active Directory, and local changes are reverted at the next refresh. Which mechanism is this?',
  options: ['SELinux', 'Group Policy', 'Configuration enforcement', 'Secure baseline'],
  answer: 1,
  explanation: 'Group Policy is the named 4.5 operating system security mechanism for Windows; SELinux is its Linux counterpart in the same bullet. Configuration enforcement is the generic 2.5 mitigation.',
},
{
  objective: '4.5',
  stem: 'A device is denied network access until it proves it has current antivirus signatures and an approved OS patch level. Which capability is this?',
  options: ['802.1X', 'Network access control (NAC)', 'Endpoint detection and response (EDR)', 'Screened subnet'],
  answer: 1,
  explanation: 'NAC adds POSTURE ASSESSMENT — checking the device\'s health, not just its identity. 802.1X (3.2) authenticates the device at the port; NAC decides based on its state.',
},
{
  objective: '4.5',
  stem: 'An IDS is configured to alert when traffic matches a known pattern for a specific exploit. Which detection method is this?',
  options: ['Trends', 'Signatures', 'Reputation', 'Content categorization'],
  answer: 1,
  explanation: 'Signatures match KNOWN patterns and cannot see novel attacks. Trends (anomaly) compare against a baseline and can, at the cost of false positives. The objectives list both under IDS/IPS.',
},
{
  objective: '4.5',
  stem: 'A web filter blocks a site because the destination has a poor score derived from its history of hosting malware. Which web filter feature is this?',
  options: ['Content categorization', 'Reputation', 'URL scanning', 'Block rules'],
  answer: 1,
  explanation: 'Reputation is a score derived from HISTORY. Content categorization sorts a site by TOPIC — gambling, social media. Both can block the same site for different reasons.',
},

/* ---------------- 4.6 identity and access management ---------------- */
{
  objective: '4.6',
  stem: 'Access to classified files is determined by the system comparing the file\'s label to the user\'s clearance. Neither the user nor the file owner can override it. Which model is this?',
  options: ['Discretionary', 'Mandatory', 'Role-based', 'Attribute-based'],
  answer: 1,
  explanation: 'Mandatory: the SYSTEM decides by label and nobody can override. Discretionary: the DATA OWNER decides and can grant access at will. The phrase "cannot override" is the tell.',
},
{
  objective: '4.6',
  stem: 'Permissions are assigned to job functions such as "AP Clerk" and users inherit them by being placed in that function. Which model is this?',
  options: ['Rule-based', 'Role-based', 'Attribute-based', 'Mandatory'],
  answer: 1,
  explanation: 'Role is about WHO the person is — their job. Rule is a condition the system evaluates regardless of who they are. Both abbreviate to RBAC, and the acronym list carries both entries.',
},
{
  objective: '4.6',
  stem: 'Access is granted only if the user is in the finance department, on a managed device, and connecting from a corporate network. Which model is this?',
  options: ['Role-based', 'Attribute-based', 'Rule-based', 'Discretionary'],
  answer: 1,
  explanation: 'Attribute-based combines multiple properties of subject, object and environment. A single blanket condition applied to everyone would be rule-based; three combined properties is ABAC.',
},
{
  objective: '4.6',
  stem: 'Before issuing credentials, an organisation checks a new joiner\'s passport and employment records to confirm they are who they claim. Which process is this?',
  options: ['Authentication', 'Identity proofing', 'Attestation', 'Federation'],
  answer: 1,
  explanation: 'Proofing happens ONCE at enrolment and establishes that the identity is real. Authentication happens at every subsequent login and only proves the same person is back.',
},
{
  objective: '4.6',
  stem: 'A university lets students sign in to an external research portal using their university credentials, with the university asserting their identity. Which concept is this?',
  options: ['Single sign-on (SSO)', 'Federation', 'Interoperability', 'Attestation'],
  answer: 1,
  explanation: 'SSO is one login across systems YOU own. Federation crosses an ORGANISATIONAL boundary and requires a trust relationship between the two parties.',
},
{
  objective: '4.6',
  stem: 'Which protocol is designed to grant a third-party application delegated authorisation to a resource without sharing the user\'s password?',
  options: ['Security Assertions Markup Language (SAML)', 'Open authorization (OAuth)', 'Lightweight Directory Access Protocol (LDAP)', 'RADIUS'],
  answer: 1,
  explanation: 'OAuth grants delegated AUTHORISATION. SAML carries authentication ASSERTIONS between an identity provider and a service provider. The word "authorization" is inside the OAuth acronym for a reason.',
},
{
  objective: '4.6',
  stem: 'An administrator requests elevated rights, which are granted automatically for 30 minutes and then removed. Which PAM tool is this?',
  options: ['Password vaulting', 'Just-in-time permissions', 'Ephemeral credentials', 'Least privilege'],
  answer: 1,
  explanation: 'Just-in-time is about the TIME the permission exists. Password vaulting is about checking a shared credential in and out. Ephemeral credentials are secrets that expire after use.',
},
{
  objective: '4.6',
  stem: 'A shared administrator password is held in a central store, checked out for a session, then automatically rotated. Which PAM tool is this?',
  options: ['Just-in-time permissions', 'Password vaulting', 'Passwordless', 'Attestation'],
  answer: 1,
  explanation: 'Vaulting is about custody of a CREDENTIAL — checked out, then rotated. Just-in-time is about the duration of a PERMISSION. The rotation after checkout is the vaulting tell.',
},
{
  objective: '4.6',
  stem: 'A user authenticates with a password and a code from a hardware token. Which two factors are in use?',
  options: [
    'Something you know and something you have',
    'Something you know and something you are',
    'Something you have and somewhere you are',
    'Something you are and something you have',
  ],
  answer: 0,
  explanation: 'A password is knowledge; a token is a physical object. Biometrics would be "something you are", and location would be "somewhere you are" — the fourth factor the objectives list.',
},
{
  objective: '4.6',
  stem: 'Managers are required each quarter to review and confirm that their staff still need the access they hold. Which 4.6 term describes this?',
  options: ['Attestation', 'Identity proofing', 'Provisioning', 'Interoperability'],
  answer: 0,
  explanation: 'Attestation is confirming that an identity or entitlement is still valid. Proofing establishes the identity at the start; attestation re-confirms the entitlement later.',
},
{
  objective: '4.6',
  stem: 'When an employee leaves, an automated workflow disables their accounts and revokes group memberships within minutes. Which 4.6 activity is this?',
  options: ['De-provisioning', 'Attestation', 'Identity proofing', 'Permission assignments'],
  answer: 0,
  explanation: 'The objectives pair provisioning and de-provisioning of user accounts. De-provisioning is the leaver half, and its absence is exactly what makes the dismissed-administrator scenario possible.',
},

/* ---------------- 4.7 automation and orchestration ---------------- */
{
  objective: '4.7',
  stem: 'A deployment pipeline automatically refuses to apply any configuration that would open a storage bucket to the public internet. Which use case does the objectives document name?',
  options: ['Security groups', 'Guard rails', 'Enforcing baselines', 'Continuous integration and testing'],
  answer: 1,
  explanation: 'Guard rails constrain what an automated process is ALLOWED to do. Security groups are the access grouping being managed. Enforcing baselines is a benefit, not a use case.',
},
{
  objective: '4.7',
  stem: 'A SOC automates tier-one triage so three analysts handle the alert volume that previously needed nine. Which benefit does the objectives document name?',
  options: ['Efficiency/time saving', 'Workforce multiplier', 'Reaction time', 'Employee retention'],
  answer: 1,
  explanation: 'Workforce multiplier is about HEADCOUNT capacity — the same people covering more. Efficiency/time saving is about the clock on an individual task. The stem is explicitly about staff numbers.',
},
{
  objective: '4.7',
  stem: 'Years of quick fixes in an automation platform now make every change slow and risky. Which 4.7 consideration is this?',
  options: ['Complexity', 'Technical debt', 'Ongoing supportability', 'Single point of failure'],
  answer: 1,
  explanation: 'Technical debt is what PAST shortcuts cost you later. Complexity is what the system is like NOW. The stem\'s "years of quick fixes" points at accumulated debt.',
},
{
  objective: '4.7',
  stem: 'An organisation automates account creation so that a new hire\'s accounts, groups and mailbox are created from the HR record. Which use case is this?',
  options: ['Resource provisioning', 'User provisioning', 'Ticket creation', 'Escalation'],
  answer: 1,
  explanation: 'User provisioning creates ACCOUNTS. Resource provisioning creates INFRASTRUCTURE — servers, storage, network. The objectives list both separately and the object being created is the discriminator.',
},
{
  objective: '4.7',
  stem: 'A team automates its entire alert pipeline through one orchestration platform. What risk does the objectives document specifically name for this?',
  options: ['Single point of failure', 'Technical debt', 'Cost', 'Complexity'],
  answer: 0,
  explanation: 'Concentrating everything in one platform makes that platform a single point of failure — named explicitly among the 4.7 "other considerations" alongside complexity, cost, technical debt and supportability.',
},

/* ---------------- 4.8 incident response ---------------- */
{
  objective: '4.8',
  stem: 'Ransomware is actively encrypting file shares. The team disconnects the affected servers from the network. Which incident response phase is this?',
  options: ['Eradication', 'Containment', 'Recovery', 'Analysis'],
  answer: 1,
  explanation: 'Containment limits SPREAD while the threat is still present. Eradication REMOVES it. Order matters: you contain before you eradicate, and "patch the vulnerability" is wrong while the attack is live.',
},
{
  objective: '4.8',
  stem: 'The malware has been removed and systems verified clean. The team now restores data and returns services to production. Which phase is this?',
  options: ['Containment', 'Eradication', 'Recovery', 'Lessons learned'],
  answer: 2,
  explanation: 'Recovery restores normal operations after eradication has removed the threat. Lessons learned comes afterwards and changes the process rather than the systems.',
},
{
  objective: '4.8',
  stem: 'Legal counsel instructs that all mailboxes belonging to three employees must be preserved because litigation is anticipated. What is this instruction called?',
  options: ['Preservation', 'Legal hold', 'E-discovery', 'Chain of custody'],
  answer: 1,
  explanation: 'The legal hold is the ORDER that triggers retention. Preservation is the technical act of keeping the data intact. E-discovery is the later production of it for proceedings.',
},
{
  objective: '4.8',
  stem: 'Each person who handles a seized laptop signs and timestamps a form recording when they took and returned it. What does this establish?',
  options: ['Acquisition', 'Chain of custody', 'Legal hold', 'Attestation'],
  answer: 1,
  explanation: 'Acquisition is TAKING the forensic copy. Chain of custody is the documentation proving nobody tampered with the evidence since — without it the evidence may be inadmissible.',
},
{
  objective: '4.8',
  stem: 'With no alert having fired, an analyst forms a hypothesis about how an adversary might be persisting and searches telemetry for evidence of it. Which activity is this?',
  options: ['Detection', 'Threat hunting', 'Root cause analysis', 'Analysis'],
  answer: 1,
  explanation: 'Threat hunting starts from a HYPOTHESIS with no alert at all. Detection is triggered by something. The phrase "no alert having fired" is the discriminator.',
},
{
  objective: '4.8',
  stem: 'After service is restored, the team determines that the intrusion succeeded because a decommissioning process never removed a vendor account. Which activity is this?',
  options: ['Lessons learned', 'Root cause analysis', 'Threat hunting', 'Detection'],
  answer: 1,
  explanation: 'Root cause analysis finds WHY it was possible. Lessons learned is the phase that decides what to CHANGE as a result. RCA produces the finding; lessons learned acts on it.',
},
{
  objective: '4.8',
  stem: 'Which is the correct order of the incident response process as the objectives document lists it?',
  options: [
    'Preparation, detection, analysis, containment, eradication, recovery, lessons learned',
    'Detection, preparation, containment, analysis, eradication, recovery, lessons learned',
    'Preparation, detection, containment, eradication, analysis, recovery, lessons learned',
    'Detection, analysis, preparation, containment, recovery, eradication, lessons learned',
  ],
  answer: 0,
  explanation: 'Analysis comes after detection and before containment — you must understand the scope before you act. Preparation is first and happens before any incident exists.',
},

/* ---------------- 4.9 investigation data sources ---------------- */
{
  objective: '4.9',
  stem: 'An investigator must establish exactly what commands an attacker typed during an unencrypted session. Which data source can prove this?',
  options: ['Network logs', 'Packet captures', 'Firewall logs', 'NetFlow'],
  answer: 1,
  explanation: 'Network logs, firewall logs and NetFlow all prove a conversation HAPPENED. Only a packet capture holds the PAYLOAD and can show what was said.',
},
{
  objective: '4.9',
  stem: 'An analyst needs to know which accounts logged on to a Windows server and which attempts failed. Which source is MOST directly relevant?',
  options: ['Application logs', 'OS-specific security logs', 'Endpoint logs', 'Network logs'],
  answer: 1,
  explanation: 'The operating system\'s own audit trail records logon success and failure. Endpoint logs are what a security agent produced — related, but a different source in the objectives list.',
},
{
  objective: '4.9',
  stem: 'A leaked photograph is analysed and found to contain the camera model, timestamp and GPS coordinates of where it was taken. What is this data called?',
  options: ['Metadata', 'Application logs', 'Endpoint logs', 'Automated reports'],
  answer: 0,
  explanation: 'Metadata travels INSIDE the artifact. Logs are written ABOUT an artifact from outside it. That is the test when a question offers both.',
},
{
  objective: '4.9',
  stem: 'A manager asks for a single view showing open vulnerabilities, patch compliance and alert volume trending over 90 days. Which data source does the objectives document name?',
  options: ['Dashboards', 'Automated reports', 'Vulnerability scans', 'Packet captures'],
  answer: 0,
  explanation: 'Dashboards present a live consolidated view. Automated reports are generated and distributed on a schedule. Both appear in 4.9 and the discriminator is whether it is viewed or delivered.',
},
];
