// Domain 5 — Security Program Management and Oversight (20%)

export default [

/* ---------------- 5.1 governance ---------------- */
{
  objective: '5.1',
  stem: 'A document states that passwords must be at least 14 characters. It is mandatory and implements a broader information security policy. Which governance artifact is it?',
  options: ['Policy', 'Standard', 'Procedure', 'Guideline'],
  answer: 1,
  explanation: 'Policy says WHAT and WHY. Standard says the SPECIFIC requirement. Procedure says the STEPS. Guideline is ADVISORY. A concrete measurable requirement is a standard.',
},
{
  objective: '5.1',
  stem: 'A document recommends, but does not require, that teams enable disk encryption on development laptops. Which artifact is it?',
  options: ['Standard', 'Guideline', 'Policy', 'Procedure'],
  answer: 1,
  explanation: 'Guidelines are the only one of the four that is advisory. The word "recommends, but does not require" is the discriminator the exam relies on.',
},
{
  objective: '5.1',
  stem: 'A SOC has a step-by-step document covering exactly how to respond to a confirmed phishing report. Which artifact does the objectives document name?',
  options: ['Playbooks', 'Standard operating procedure', 'Incident response policy', 'Guideline'],
  answer: 0,
  explanation: 'The objectives list playbooks under Procedures in 5.1. A playbook is a procedure scoped to ONE specific incident type; the incident response policy is the higher-level mandate.',
},
{
  objective: '5.1',
  stem: 'Under privacy law, which party decides the purposes and means of processing personal data?',
  options: ['Processor', 'Controller', 'Custodian/steward', 'Data subject'],
  answer: 1,
  explanation: 'The controller DECIDES why and how. The processor acts on the controller\'s instructions. The custodian/steward provides day-to-day care, and the data subject is the person the data is about.',
},
{
  objective: '5.1',
  stem: 'An organisation forms a standing group of senior leaders that meets quarterly to approve security strategy and review risk. Which governance structure is this?',
  options: ['Boards', 'Committees', 'Government entities', 'Centralized/decentralized'],
  answer: 1,
  explanation: 'The objectives list boards, committees, government entities and centralized/decentralized as governance structures. A committee is convened for a purpose; a board is the top governing body of the organisation.',
},
{
  objective: '5.1',
  stem: 'Which policy does the objectives document name as the one defining what employees may and may not do with company systems?',
  options: ['Information security policy', 'Acceptable use policy (AUP)', 'Business continuity policy', 'Change management policy'],
  answer: 1,
  explanation: 'The AUP is specifically about permitted USE by people. The information security policy is the broader mandate covering how the organisation protects information overall.',
},

/* ---------------- 5.2 risk management ---------------- */
{
  objective: '5.2',
  stem: 'A server is worth £80,000. A fire would destroy 50% of its value, and such a fire is expected once every four years. What is the ALE?',
  options: ['£10,000', '£20,000', '£40,000', '£160,000'],
  answer: 0,
  explanation: 'SLE = asset value x exposure factor = 80,000 x 0.5 = £40,000. ARO = 1/4 = 0.25. ALE = SLE x ARO = 40,000 x 0.25 = £10,000. £40,000 is the SLE and is the distractor for stopping one step early.',
},
{
  objective: '5.2',
  stem: 'In the quantitative risk formulas, what does the exposure factor represent?',
  options: [
    'The number of times per year an event is expected',
    'The proportion of the asset\'s value lost in a single event',
    'The total annual cost of the risk',
    'The organisation\'s willingness to accept risk',
  ],
  answer: 1,
  explanation: 'Exposure factor is the PROPORTION lost per event and feeds the SLE. The count per year is the ARO; the annual cost is the ALE; willingness to accept is risk appetite.',
},
{
  objective: '5.2',
  stem: 'A board states the organisation will pursue aggressive growth and accept materially higher risk to do so. Which term describes this stance?',
  options: ['Risk tolerance', 'Risk appetite — expansionary', 'Risk threshold', 'Risk acceptance'],
  answer: 1,
  explanation: 'Appetite is the strategic hunger, and the objectives give it three values: expansionary, conservative, neutral. Tolerance is the acceptable variance around the appetite once set.',
},
{
  objective: '5.2',
  stem: 'A risk is documented, its business justification recorded and senior management signs off that no treatment will be applied. Which strategy is this?',
  options: ['Mitigate', 'Transfer', 'Accept', 'Avoid'],
  answer: 2,
  explanation: 'Accept is the documented decision to live with the risk, recorded as an exemption or an exception. Avoid would mean not doing the activity at all; transfer would move the loss to a third party.',
},
{
  objective: '5.2',
  stem: 'A company decides not to launch a product line at all because the regulatory risk is unacceptable. Which risk strategy is this?',
  options: ['Avoid', 'Accept', 'Mitigate', 'Transfer'],
  answer: 0,
  explanation: 'Avoidance eliminates the risk by not undertaking the activity. Mitigation would reduce it while still proceeding — the discriminator is whether the activity happens at all.',
},
{
  objective: '5.2',
  stem: 'A business impact analysis states the payroll system must be running again within 4 hours of an outage. Which metric is this?',
  options: ['Recovery point objective (RPO)', 'Recovery time objective (RTO)', 'Mean time to repair (MTTR)', 'Mean time between failures (MTBF)'],
  answer: 1,
  explanation: 'RTO looks FORWARD — time until service is restored. RPO looks BACKWARD — how much data you can afford to lose. MTTR is an observed average, not a target you set.',
},
{
  objective: '5.2',
  stem: 'A business impact analysis states that no more than 15 minutes of transactions may be lost in a disaster. Which metric is this?',
  options: ['Recovery time objective (RTO)', 'Recovery point objective (RPO)', 'Mean time between failures (MTBF)', 'Risk threshold'],
  answer: 1,
  explanation: 'RPO is measured in DATA, expressed as time since the last recoverable point. It drives backup frequency; RTO drives standby capacity.',
},
{
  objective: '5.2',
  stem: 'A document records each identified risk with its owner, current score and the level at which it must be escalated. What is this document?',
  options: ['Business impact analysis', 'Risk register', 'Risk appetite statement', 'Compliance report'],
  answer: 1,
  explanation: 'The register holds key risk indicators, risk owners and risk thresholds — all three are named in the objectives as its contents.',
},
{
  objective: '5.2',
  stem: 'A cloud platform continuously evaluates configuration against risk criteria and updates scores automatically as changes occur. Which risk assessment cadence is this?',
  options: ['Ad hoc', 'Recurring', 'One-time', 'Continuous'],
  answer: 3,
  explanation: 'The four cadences are ad hoc (triggered by an event), recurring (on a schedule), one-time (for a specific decision) and continuous (always running). Automation is what makes continuous possible.',
},

/* ---------------- 5.3 third-party risk ---------------- */
{
  objective: '5.3',
  stem: 'A contract with a payment processor grants the customer the right to inspect the processor\'s security controls on 30 days\' notice. Which element is this?',
  options: ['Independent assessments', 'Right-to-audit clause', 'Evidence of internal audits', 'Vendor monitoring'],
  answer: 1,
  explanation: 'The right-to-audit is YOUR right, written into the contract. An independent assessment is a third party\'s report handed to you — you are the reader, not the auditor.',
},
{
  objective: '5.3',
  stem: 'Two organisations sign a non-binding document recording their shared intention to collaborate on a security programme. Which agreement type is this?',
  options: ['Memorandum of agreement (MOA)', 'Memorandum of understanding (MOU)', 'Master service agreement (MSA)', 'Business partners agreement (BPA)'],
  answer: 1,
  explanation: 'MOU expresses INTENT and is generally non-binding. MOA sets out agreed responsibilities and is closer to binding. The word "non-binding" in the stem decides it.',
},
{
  objective: '5.3',
  stem: 'An organisation signs one overarching contract setting standard terms, then issues separate documents for each individual project. What are the second documents?',
  options: ['Master service agreements', 'Work orders/statements of work', 'Memoranda of understanding', 'Service-level agreements'],
  answer: 1,
  explanation: 'The MSA is the umbrella covering many future engagements; the SOW or work order describes ONE specific job beneath it. The stem gives you both halves.',
},
{
  objective: '5.3',
  stem: 'Before a penetration test begins, both parties agree in writing which systems are in scope, which techniques are forbidden and the testing window. What is this document?',
  options: ['Statement of work', 'Rules of engagement', 'Non-disclosure agreement', 'Service-level agreement'],
  answer: 1,
  explanation: 'Rules of engagement say what the tester may DO. The SOW says what they will DELIVER. Both exist for the same engagement and questions ask you to separate them.',
},
{
  objective: '5.3',
  stem: 'During vendor selection, an organisation investigates a supplier\'s financial stability, ownership and past breach history. Which activity is this?',
  options: ['Due diligence', 'Conflict of interest', 'Supply chain analysis', 'Vendor monitoring'],
  answer: 0,
  explanation: 'Due diligence is the investigation BEFORE selection. Vendor monitoring is what you do afterwards. Conflict of interest is a specific disqualifying finding, not the process.',
},
{
  objective: '5.3',
  stem: 'It emerges that the manager choosing a security vendor holds shares in that vendor. Which vendor selection concern is this?',
  options: ['Due diligence', 'Conflict of interest', 'Right-to-audit clause', 'Rules of engagement'],
  answer: 1,
  explanation: 'A conflict of interest exists when a decision-maker has a personal stake in the outcome. The objectives list it alongside due diligence as the two vendor selection considerations.',
},
{
  objective: '5.3',
  stem: 'An organisation sends each supplier an annual security self-assessment form covering their controls. Which ongoing activity is this?',
  options: ['Questionnaires', 'Vendor monitoring', 'Independent assessments', 'Penetration testing'],
  answer: 0,
  explanation: 'Questionnaires are the named 5.3 instrument. Vendor monitoring is the broader ongoing oversight of which a questionnaire is one method.',
},

/* ---------------- 5.4 compliance ---------------- */
{
  objective: '5.4',
  stem: 'A regulator withdraws a company\'s authorisation to operate in a market after repeated compliance failures. Which consequence does the objectives document name?',
  options: ['Sanctions', 'Loss of license', 'Contractual impacts', 'Reputational damage'],
  answer: 1,
  explanation: 'The five consequences are fines, sanctions, reputational damage, loss of license and contractual impacts. Losing authorisation to operate is specifically loss of license.',
},
{
  objective: '5.4',
  stem: 'An individual demands that a company erase all personal data it holds about them. Which privacy concept is this?',
  options: ['Data retention', 'Right to be forgotten', 'Data sovereignty', 'Ownership'],
  answer: 1,
  explanation: 'Right to be forgotten is the SUBJECT\'S demand for erasure. Data retention is YOUR schedule for how long you keep things — the two can be in direct conflict, which is why both are listed.',
},
{
  objective: '5.4',
  stem: 'In privacy terminology, what is the "data subject"?',
  options: [
    'The individual the personal data is about',
    'The role accountable for the data inside the organisation',
    'The organisation that decides the purpose of processing',
    'The third party that processes data on instruction',
  ],
  answer: 0,
  explanation: 'The data subject is the PERSON. The accountable internal role is the owner; the one who decides purpose is the controller; the one acting on instruction is the processor.',
},
{
  objective: '5.4',
  stem: 'A company formally signs a statement each year confirming that its stated security controls are in place and operating. Which compliance activity is this?',
  options: ['Attestation and acknowledgement', 'Compliance reporting', 'Due diligence/care', 'Automation'],
  answer: 0,
  explanation: 'Attestation is a formal statement that something is true. The objectives pair it with acknowledgement under compliance monitoring — it is a declaration, not a report of findings.',
},
{
  objective: '5.4',
  stem: 'What is the difference between due diligence and due care?',
  options: [
    'Due diligence is the investigation; due care is acting on what it found',
    'Due care is the investigation; due diligence is acting on what it found',
    'They are legally identical',
    'Due diligence applies only to vendors; due care only to employees',
  ],
  answer: 0,
  explanation: 'Diligence is the INVESTIGATING; care is the ACTING. The objectives list them as a pair under compliance monitoring precisely because the distinction matters in a negligence argument.',
},

/* ---------------- 5.5 audits and assessments ---------------- */
{
  objective: '5.5',
  stem: 'A penetration tester is given full network diagrams, source code and credentials before starting. Which SY0-701 term describes this engagement?',
  options: ['White box', 'Known environment', 'Partially known environment', 'Integrated'],
  answer: 1,
  explanation: 'White, grey and black box are the older vocabulary and are deliberately absent from SY0-701. Answer known / partially known / unknown environment.',
},
{
  objective: '5.5',
  stem: 'A tester gathers information about a target using only public DNS records, job adverts and social media, sending nothing to the target. Which reconnaissance type is this?',
  options: ['Active', 'Passive', 'Unknown environment', 'Offensive'],
  answer: 1,
  explanation: 'Passive uses public sources only. The moment you send a packet at the target — even a ping — it becomes active reconnaissance.',
},
{
  objective: '5.5',
  stem: 'An organisation\'s own staff evaluate their controls against a framework and produce an internal report. Which assessment type is this?',
  options: ['Independent third-party audit', 'Self-assessments', 'Regulatory examination', 'Attestation'],
  answer: 1,
  explanation: 'Self-assessment is the least independent option on the 5.5 list. The objectives split audits into internal (compliance, audit committee, self-assessments) and external.',
},
{
  objective: '5.5',
  stem: 'In a penetration testing engagement, which term describes an exercise where the attacking and defending teams work together and share information throughout?',
  options: ['Offensive', 'Defensive', 'Integrated', 'Physical'],
  answer: 2,
  explanation: 'Offensive is the attacking side, defensive is the responding side, and integrated is the two working together. The objectives list all three plus physical.',
},
{
  objective: '5.5',
  stem: 'A committee of the board, independent of management, oversees the internal audit function. Which 5.5 element is this?',
  options: ['Audit committee', 'Compliance', 'Self-assessments', 'Independent third-party audit'],
  answer: 0,
  explanation: 'The audit committee is named under Internal in 5.5. It is internal to the organisation but independent of the management it oversees — that independence is its point.',
},

/* ---------------- 5.6 security awareness ---------------- */
{
  objective: '5.6',
  stem: 'Security sends simulated phishing emails to all staff monthly and measures who clicks. Which 5.6 element is this?',
  options: ['Recognizing a phishing attempt', 'Campaigns', 'Responding to reported suspicious messages', 'Reporting and monitoring'],
  answer: 1,
  explanation: 'The campaign is what YOU run. Recognising is the skill you are trying to build in the user, and responding is the process after a report arrives.',
},
{
  objective: '5.6',
  stem: 'An employee knowingly bypasses a security control to finish work faster. Which category of anomalous behaviour does the objectives document use?',
  options: ['Unintentional', 'Unexpected', 'Risky', 'Insider threat'],
  answer: 2,
  explanation: 'Risky is knowing and deliberate but not malicious. Unintentional is a mistake. Unexpected is simply out of pattern. Insider threat is a 2.1 actor, not a 5.6 behaviour category.',
},
{
  objective: '5.6',
  stem: 'Training tells staff not to discuss project details in public places or on social media. Which training topic does the objectives document name?',
  options: ['Situational awareness', 'Operational security', 'Insider threat', 'Policy/handbooks'],
  answer: 1,
  explanation: 'Operational security is about not leaking YOUR OWN information. Situational awareness is about noticing threats around you. Both are named 5.6 training topics and are easily swapped.',
},
{
  objective: '5.6',
  stem: 'An awareness programme covers the risk of plugging in found USB drives and unknown charging cables. Which training topic is this?',
  options: ['Removable media and cables', 'Operational security', 'Social engineering', 'Situational awareness'],
  answer: 0,
  explanation: 'The objectives name "removable media and cables" as its own training topic — the cables half covers malicious charging cables, which candidates often forget is in scope.',
},
{
  objective: '5.6',
  stem: 'An organisation delivers awareness training at onboarding and then annually thereafter. Which 5.6 element does the annual repetition represent?',
  options: ['Initial', 'Recurring', 'Development', 'Execution'],
  answer: 1,
  explanation: 'Reporting and monitoring in 5.6 splits into initial and recurring. Onboarding is initial; the annual repeat is recurring. Development and execution describe building and running the programme itself.',
},
];
