// Coverage bank — Domain 1. One item per objective-list term that the main
// authored bank never credited. Recall-shaped by design: the job here is to
// make every term producible, not to build another scenario.

const q = (objective, stem, options, answer, explanation) =>
  ({ objective, stem, options, answer, explanation });

export default [

/* 1.1 */
q('1.1', 'A quarterly risk assessment performed by the security governance team is which control category?',
  ['Operational', 'Managerial', 'Technical', 'Physical'], 1,
  'Managerial controls are the paperwork that governs — policy, planning, risk assessment. Operational controls are executed by people as part of daily work, which a periodic governance activity is not.'),
q('1.1', 'An intrusion detection system that logs and alerts on suspicious traffic but takes no action is which control type?',
  ['Preventive', 'Detective', 'Corrective', 'Deterrent'], 1,
  'Detective controls notice and record; they do not intervene. An IPS that blocked the traffic would be preventive — the discriminator is whether the device acts or only reports.'),

/* 1.2 */
q('1.2', 'Requiring a user to present a password and a fingerprint before granting access is an example of which AAA activity?',
  ['Authenticating people', 'Authenticating systems', 'Authorization models', 'Accounting'], 0,
  'The objectives split authentication into people and systems. A human presenting credentials is authenticating people; a server presenting a certificate to another server is authenticating systems.'),
q('1.2', 'A server presents a client certificate to prove its identity to another server with no human involved. Which AAA activity is this?',
  ['Authenticating people', 'Authenticating systems', 'Accounting', 'Authorization models'], 1,
  'Authenticating systems covers machine-to-machine identity — certificates, service accounts, API keys. No person is involved, which is the discriminator against authenticating people.'),
q('1.2', 'Deciding whether access is granted by role, by attribute or by rule is a question about which AAA element?',
  ['Authentication', 'Authorization models', 'Accounting', 'Non-repudiation'], 1,
  'Authorization models describe HOW the decision of what you may do is structured. Authentication establishes who you are first; accounting records what you did afterwards.'),
q('1.2', 'A Zero Trust system raises the authentication requirement when a user connects from an unusual location or device. Which Control Plane concept is this?',
  ['Adaptive identity', 'Threat scope reduction', 'Policy-driven access control', 'Implicit trust zones'], 0,
  'Adaptive identity varies the assurance demanded based on context and risk. Policy-driven access control is the broader idea that policy rather than network position decides.'),
q('1.2', 'A Zero Trust architecture bases every access decision on written policy rather than on which network segment the request came from. Which Control Plane concept is this?',
  ['Adaptive identity', 'Policy-driven access control', 'Implicit trust zones', 'Policy Engine'], 1,
  'Policy-driven access control is the principle. The Policy Engine is the component that implements it — the stem describes the approach, not the box.'),
q('1.2', 'Which Zero Trust Control Plane component communicates the decision and establishes or terminates the session?',
  ['Policy Engine', 'Policy Administrator', 'Policy Enforcement Point', 'Subject/System'], 1,
  'The Engine decides; the Administrator carries the decision out and manages the session. Both are Control Plane, which is why they are so easily swapped.'),
q('1.2', 'In the Zero Trust Data Plane, what term describes an area where traffic is trusted simply because of where it is?',
  ['Implicit trust zones', 'Security zones', 'Segmentation', 'Threat scope reduction'], 0,
  'Implicit trust zones are exactly what Zero Trust exists to eliminate — trust granted by location rather than by verification. The objectives list it as a Data Plane term.'),
q('1.2', 'In Zero Trust terminology, what is the entity requesting access to a resource called?',
  ['Subject/System', 'Policy Enforcement Point', 'Implicit trust zone', 'Data Plane'], 0,
  'Subject/System is the requester — the user or the machine. The Policy Enforcement Point is what stands between it and the resource. Both are Data Plane terms.'),
q('1.2', 'A perimeter barrier defines the property boundary and channels people toward a controlled entrance. Which physical control is this?',
  ['Bollards', 'Fencing', 'Access control vestibule', 'Lighting'], 1,
  'Fencing defines a perimeter against people and directs foot traffic. Bollards are vehicle-specific, and a vestibule controls one doorway rather than a boundary.'),
q('1.2', 'Cameras record activity in a car park so that incidents can be reviewed afterwards. Which physical control is this?',
  ['Video surveillance', 'Sensors', 'Lighting', 'Security guard'], 0,
  'Video surveillance is the objectives\' term. It is detective by nature — it records rather than prevents, although a visible camera also has a deterrent effect.'),
q('1.2', 'Which physical security control can exercise judgement and respond to a situation it has never seen before?',
  ['Video surveillance', 'Security guard', 'Access badge', 'Bollards'], 1,
  'A guard is the only physical control on the list capable of discretion. That flexibility is its advantage over automated controls and its cost is that it is the most expensive.'),
q('1.2', 'Employees present a contactless card to a reader to open the office door. Which physical control is this?',
  ['Access badge', 'Access control vestibule', 'Security guard', 'Sensors'], 0,
  'The access badge is the credential itself. The vestibule is the double-door structure that would stop someone following the badge holder through.'),
q('1.2', 'Illuminating a car park at night to discourage loitering and improve camera coverage is which physical control?',
  ['Lighting', 'Video surveillance', 'Fencing', 'Sensors'], 0,
  'Lighting is listed as a physical control in its own right. It is primarily deterrent, and it also makes video surveillance usable — the two are commonly deployed together.'),
q('1.2', 'A motion sensor detects an intruder by the heat their body radiates. Which sensor type is this?',
  ['Microwave', 'Infrared', 'Ultrasonic', 'Pressure'], 1,
  'Infrared detects heat. Microwave uses radio energy, ultrasonic uses sound, and pressure detects weight — the objectives list all four and separate them by the physical property measured.'),
q('1.2', 'A sensor under a floor mat triggers when someone stands on it. Which sensor type is this?',
  ['Infrared', 'Pressure', 'Ultrasonic', 'Microwave'], 1,
  'Pressure sensors detect weight or force. They are the only one of the four that requires physical contact with the sensor rather than sensing at a distance.'),
q('1.2', 'A sensor emits radio energy and detects movement by measuring how the reflected signal shifts. Which type is this?',
  ['Ultrasonic', 'Microwave', 'Infrared', 'Pressure'], 1,
  'Microwave uses radio-frequency energy; ultrasonic uses sound waves. Both work by measuring reflection, which is why they are the pair most often confused.'),
q('1.2', 'A deliberately vulnerable server is placed on the network to attract attackers and observe their methods. What is it?',
  ['Honeyfile', 'Honeypot', 'Honeytoken', 'Honeynet'], 1,
  'A honeypot is a whole SYSTEM. A honeyfile is one file and a honeytoken one record — the ladder runs token, file, pot, net, and scale is the discriminator.'),
q('1.2', 'An entire decoy network of interconnected vulnerable systems is built to study attacker behaviour at length. What is it?',
  ['Honeypot', 'Honeynet', 'Honeyfile', 'Sandbox'], 1,
  'A honeynet is a NETWORK of honeypots, allowing an attacker to move laterally and reveal more of their methodology than a single host could.'),

/* 1.3 */
q('1.3', 'Every change must be reviewed and authorised by a change advisory board before implementation. Which 1.3 business process is this?',
  ['Approval process', 'Impact analysis', 'Ownership', 'Stakeholders'], 0,
  'The approval process is the authorisation gate itself. Impact analysis is the assessment brought TO that gate, and stakeholders are the people consulted along the way.'),
q('1.3', 'Each change request must name the individual accountable for the system being changed. Which 1.3 element is this?',
  ['Stakeholders', 'Ownership', 'Approval process', 'Standard operating procedure'], 1,
  'Ownership names the single accountable person. Stakeholders are the wider set with an interest — one is accountable, the others are consulted.'),
q('1.3', 'A change to a shared authentication service requires consultation with every team whose applications depend on it. Those teams are the:',
  ['Owners', 'Stakeholders', 'Approvers', 'Custodians'], 1,
  'Stakeholders are everyone affected by or interested in the change. The owner is the single accountable party — a change usually has one owner and many stakeholders.'),
q('1.3', 'A change board requires evidence from a staging environment that the change works before approving it. Which 1.3 element is this?',
  ['Impact analysis', 'Test results', 'Backout plan', 'Version control'], 1,
  'Test results are the evidence the change WORKS. Impact analysis is the assessment of what it would BREAK. Both feed the approval, and questions swap them.'),
q('1.3', 'A documented, repeatable set of instructions for performing a routine operational task is called a:',
  ['Standard operating procedure', 'Playbook', 'Guideline', 'Backout plan'], 0,
  'The objectives name standard operating procedure in 1.3. A playbook (5.1) is the narrower form scoped to one specific incident type.'),
q('1.3', 'A change adds new entries to a firewall\'s permitted-traffic configuration and removes others. Which technical implication does the objectives document name?',
  ['Allow lists/deny lists', 'Restricted activities', 'Dependencies', 'Downtime'], 0,
  'Allow lists and deny lists are named together as a technical implication of change. Restricted activities are things the change process forbids doing at all.'),
q('1.3', 'A change freeze forbids production changes during the end-of-year financial close. Which technical implication is this?',
  ['Downtime', 'Restricted activities', 'Maintenance window', 'Allow lists/deny lists'], 1,
  'Restricted activities are things the process forbids in certain circumstances. A maintenance window is the opposite — the period during which disruption is permitted.'),
q('1.3', 'A change requires the service to be unavailable for 40 minutes. What is the objectives\' term for that unavailability?',
  ['Maintenance window', 'Downtime', 'Service restart', 'Backout plan'], 1,
  'Downtime is the CONSEQUENCE — the period the service is unavailable. The maintenance window is the PERMISSION to cause it. The objectives list both separately.'),
q('1.3', 'After editing a configuration file, the administrator must stop and start the daemon for the change to take effect. Which technical implication is this?',
  ['Application restart', 'Service restart', 'Downtime', 'Dependencies'], 1,
  'A service restart affects a background daemon; an application restart affects the user-facing program. The objectives list both, and the stem naming a daemon is the tell.'),
q('1.3', 'Users must close and reopen the client program before a configuration change reaches them. Which technical implication is this?',
  ['Service restart', 'Application restart', 'Legacy applications', 'Downtime'], 1,
  'Application restart is the user-facing half of the pair. Service restart is the server-side daemon — the objectives distinguish them because their user impact differs.'),
q('1.3', 'A database upgrade cannot proceed until the middleware tier has been upgraded first. Which technical implication is this?',
  ['Dependencies', 'Legacy applications', 'Restricted activities', 'Downtime'], 0,
  'Dependencies are ordering or reliance relationships between components. Legacy applications is the different problem of software too old to move at all.'),
q('1.3', 'After a change adds a new network segment, the team updates the topology drawings. Which documentation activity is this?',
  ['Updating diagrams', 'Updating policies/procedures', 'Version control', 'Impact analysis'], 0,
  'The objectives list two documentation activities. Updating diagrams keeps the technical picture accurate; updating policies and procedures keeps the written rules accurate.'),
q('1.3', 'A change to password requirements means the written standard and the helpdesk instructions must both be revised. Which documentation activity is this?',
  ['Updating diagrams', 'Updating policies/procedures', 'Standard operating procedure', 'Approval process'], 1,
  'This is the second of the two documentation activities. Diagrams describe the architecture; policies and procedures describe the rules and the steps.'),

/* 1.4 */
q('1.4', 'In asymmetric cryptography, which key can be distributed freely and is used by others to encrypt to you or verify your signature?',
  ['Private key', 'Public key', 'Session key', 'Key encryption key'], 1,
  'The public key is published; the private key never leaves the owner. Encryption to you uses your public key, and verification of your signature uses your public key too.'),
q('1.4', 'A laptop encrypts its entire drive including the operating system, so the machine cannot boot without the key. Which encryption level is this?',
  ['Partition', 'Full-disk', 'Volume', 'File'], 1,
  'Full-disk covers the whole device including the OS. Partition or volume encryption protects only a defined section, leaving the rest — often including the OS — readable.'),
q('1.4', 'Only the section of the drive holding user data is encrypted, while the system section is not. Which encryption level is this?',
  ['Full-disk', 'Partition', 'Record', 'Database'], 1,
  'Partition-level encryption protects one defined region of the disk. Full-disk would include the system area as well — the stem explicitly excludes it.'),
q('1.4', 'Individual documents are encrypted so each can be shared or moved with its protection intact. Which encryption level is this?',
  ['Volume', 'File', 'Full-disk', 'Partition'], 1,
  'File-level encryption travels with the object. Disk, partition and volume encryption protect data only while it sits on that storage — copy the file off and the protection is gone.'),
q('1.4', 'A logical storage unit that may span several physical disks is encrypted as a single unit. Which encryption level is this?',
  ['Partition', 'Volume', 'Database', 'Full-disk'], 1,
  'A volume is a logical unit that may cross physical devices, which is what separates it from a partition — a partition is a division of one physical disk.'),
q('1.4', 'An entire database instance is encrypted at rest by the database engine itself. Which encryption level is this?',
  ['Record', 'Database', 'File', 'Volume'], 1,
  'Database-level encryption protects the whole instance uniformly. Record-level protects individual rows or fields, allowing different sensitivity within one database.'),
q('1.4', 'Applying TLS so that data is protected while it moves across the network is which category of encryption in the objectives?',
  ['Transport/communication', 'Asymmetric', 'Key exchange', 'Full-disk'], 0,
  'Transport/communication is the objectives\' term for encryption of data in transit. TLS and IPSec are the named mechanisms in objective 3.2.'),
q('1.4', 'AES, RSA and ChaCha20 are examples of which component of a cryptographic solution?',
  ['Key length', 'Algorithms', 'Key exchange', 'Certificates'], 1,
  'The algorithm is the mathematical method. Key length is the separate parameter of how many bits the key has — both are listed, and strength depends on the pair.'),
q('1.4', 'Moving from AES-128 to AES-256 changes which property of the cryptographic solution?',
  ['Algorithms', 'Key length', 'Key exchange', 'Key stretching'], 1,
  'The algorithm is unchanged — it is still AES. Only the key length changed. Questions use this pair to test whether you can separate the method from its parameter.'),
q('1.4', 'A centralised platform generates, distributes, rotates and retires cryptographic keys across an organisation. What is it?',
  ['Hardware security module (HSM)', 'Key management system', 'Key escrow', 'Trusted Platform Module (TPM)'], 1,
  'A key management system is the SOFTWARE lifecycle platform. An HSM is the tamper-resistant HARDWARE that may sit underneath it — the stem describes lifecycle operations.'),
q('1.4', 'A processor contains an isolated region that protects sensitive data and code even from the operating system. What is this?',
  ['Trusted Platform Module (TPM)', 'Secure enclave', 'Hardware security module (HSM)', 'Key management system'], 1,
  'A secure enclave is a protected region INSIDE the main processor. A TPM is a separate chip on the board — the discriminator is whether it is part of the CPU or beside it.'),
q('1.4', 'A one-way function produces a fixed-length digest that changes completely if a single bit of input changes. What is this?',
  ['Encryption', 'Hashing', 'Salting', 'Tokenization'], 1,
  'Hashing is one-way and cannot be reversed, which is what separates it from encryption. Salting is an input added before hashing, not the operation itself.'),
q('1.4', 'A sender applies their private key to a hash of a message so that any recipient can verify origin and integrity. What is this?',
  ['Digital signature', 'Hashing', 'Key exchange', 'Encryption'], 0,
  'A digital signature is the sender\'s PRIVATE key over a HASH of the message. Hashing alone proves integrity but not origin, because anyone can compute a hash.'),
q('1.4', 'Which entity issues and vouches for digital certificates within a public key infrastructure?',
  ['Registration authority', 'Certificate authorities', 'Root of trust', 'Certificate signing request'], 1,
  'The certificate authority signs and issues. A registration authority may verify identity on its behalf but does not sign — that distinction is the point of the two roles.'),
q('1.4', 'A CA publishes a file listing the serial numbers of certificates it has invalidated before their expiry. What is this file?',
  ['Online Certificate Status Protocol response', 'Certificate revocation lists (CRLs)', 'Certificate signing request', 'Wildcard certificate'], 1,
  'A CRL is a published LIST you download in full. OCSP is a live query about one certificate. The word "file listing" is the discriminator.'),
q('1.4', 'A development team generates a certificate signed with its own private key rather than by a recognised authority. What is this certificate?',
  ['Third-party', 'Self-signed', 'Wildcard', 'Root of trust'], 1,
  'Self-signed certificates are signed by their own key, so nothing external vouches for them. They provide encryption but no verified identity, which is why browsers warn.'),
q('1.4', 'A public-facing website uses a certificate issued by a commercial CA already trusted by browsers. Which certificate type is this?',
  ['Self-signed', 'Third-party', 'Wildcard', 'Root of trust'], 1,
  'Third-party certificates come from an external CA whose root is already in client trust stores, which is precisely why they work without warnings.'),
q('1.4', 'Which component is inherently trusted and anchors the verification of every certificate in a chain above it?',
  ['Certificate signing request', 'Root of trust', 'Certificate revocation list', 'Key escrow'], 1,
  'The root of trust cannot itself be verified by anything else — verification has to stop somewhere, and that stopping point is the anchor the whole chain depends on.'),
];
