// Coverage bank — Domain 2.

const q = (objective, stem, options, answer, explanation) =>
  ({ objective, stem, options, answer, explanation });

export default [

/* 2.1 */
q('2.1', 'A well-funded group operating on behalf of a government targets a power grid over eighteen months. Which threat actor is this?',
  ['Organized crime', 'Nation-state', 'Hacktivist', 'Insider threat'], 1,
  'Nation-state actors have the highest funding and sophistication of any actor on the list. Organized crime is also well resourced but is motivated by money rather than strategic advantage.'),
q('2.1', 'A group breaches a company and publishes internal emails to advance a social cause. Which threat actor is this?',
  ['Hacktivist', 'Nation-state', 'Unskilled attacker', 'Organized crime'], 0,
  'Hacktivists are defined by their cause. The same technical act by a nation-state would be espionage or disruption; the motivation is what classifies the actor.'),
q('2.1', 'A criminal syndicate runs ransomware as a business, with support desks and affiliate programmes. Which threat actor is this?',
  ['Nation-state', 'Organized crime', 'Hacktivist', 'Shadow IT'], 1,
  'Organized crime is structured, professional and financially motivated. The commercial apparatus in the stem — support and affiliates — is the tell against a lone actor.'),
q('2.1', 'Which actor attribute distinguishes a disgruntled employee from an external criminal group?',
  ['Internal/external', 'Resources/funding', 'Level of sophistication/capability', 'Motivation'], 0,
  'Internal/external is one of the three named attributes and is the one the stem turns on. Funding and sophistication vary independently of where the actor sits.'),
q('2.1', 'An actor develops custom zero-day exploits and novel evasion techniques rather than using public tools. Which attribute does this describe?',
  ['Resources/funding', 'Level of sophistication/capability', 'Internal/external', 'Espionage'], 1,
  'Sophistication is about technical capability. Funding may enable it but is a separate attribute — a well-funded actor can still buy off-the-shelf tooling.'),
q('2.1', 'An attacker copies a database of customer records out of the network to an external server. Which motivation does the objectives document name?',
  ['Espionage', 'Data exfiltration', 'Blackmail', 'Service disruption'], 1,
  'Data exfiltration is the motivation of taking data out. Espionage is the narrower purpose of gathering intelligence covertly over time — the stem describes only the theft.'),
q('2.1', 'An attacker\'s aim is to make a competitor\'s online store unavailable during a sales period. Which motivation is this?',
  ['Disruption/chaos', 'Service disruption', 'Revenge', 'Financial gain'], 1,
  'Service disruption targets a specific service for a purpose. Disruption/chaos is damage for its own sake with no particular objective — the commercial timing here gives it a purpose.'),
q('2.1', 'An attacker threatens to publish stolen data unless a payment is made. Which motivation is this?',
  ['Financial gain', 'Blackmail', 'Extortion', 'Revenge'], 1,
  'Blackmail is the named motivation for coercion through threatened disclosure. Financial gain is broader and covers theft or fraud where no threat is made.'),
q('2.1', 'An attacker steals and resells credit card data purely for profit. Which motivation is this?',
  ['Financial gain', 'Data exfiltration', 'Blackmail', 'Organized crime'], 0,
  'Financial gain is the motivation; data exfiltration describes the mechanism used to achieve it. Organized crime is an actor, not a motivation.'),
q('2.1', 'An attacker defaces websites at random with no demand, no cause and no gain. Which motivation is this?',
  ['Disruption/chaos', 'Philosophical/political beliefs', 'Revenge', 'War'], 0,
  'Disruption/chaos is damage for its own sake. Philosophical/political belief requires a cause; revenge requires a grievance. The absence of both is the discriminator.'),
q('2.1', 'Cyber operations are conducted against another state\'s infrastructure as part of an armed conflict. Which motivation does the objectives document name?',
  ['War', 'Service disruption', 'Espionage', 'Disruption/chaos'], 0,
  'War is one of the ten motivations and is routinely omitted when the list is reproduced from memory, because it feels like a context rather than a motivation.'),

/* 2.2 */
q('2.2', 'An attacker sends a text message containing a malicious link. Which message-based threat vector does the objectives document name?',
  ['Instant messaging (IM)', 'Short Message Service (SMS)', 'Email', 'Voice call'], 1,
  'SMS is the named message-based vector; smishing is the social engineering technique delivered over it. The objectives list the channel and the technique separately.'),
q('2.2', 'Malware is spread through a corporate chat platform by an attacker who has compromised one account. Which message-based vector is this?',
  ['Short Message Service (SMS)', 'Instant messaging (IM)', 'Email', 'File-based'], 1,
  'Instant messaging is listed alongside email and SMS as a message-based vector. The trust users place in an internal chat tool is what makes it effective.'),
q('2.2', 'A user opens a macro-enabled spreadsheet attachment that installs a downloader. Which threat vector does the objectives document name?',
  ['Image-based', 'File-based', 'Message-based', 'Removable device'], 1,
  'File-based is the vector when the payload is carried by the document itself. Email was the delivery channel, but the objectives list both and the stem emphasises the file.'),
q('2.2', 'An attacker telephones an employee directly and talks them into disclosing a one-time code. Which threat vector does the objectives document list?',
  ['Voice call', 'Instant messaging (IM)', 'Message-based', 'Impersonation'], 0,
  'Voice call is listed as its own threat vector. Vishing is the social engineering technique that uses it — the objectives separate the channel from the technique.'),
q('2.2', 'A USB drive left in a car park is picked up and plugged into a workstation. Which threat vector is this?',
  ['File-based', 'Removable device', 'Image-based', 'Default credentials'], 1,
  'Removable device is the named vector. The related 5.6 awareness training topic is "removable media and cables", which is how the same risk appears in Domain 5.'),
q('2.2', 'A vulnerability scanner runs without installing anything on the target hosts, authenticating over the network instead. Which approach is this?',
  ['Client-based', 'Client-based vs. agentless', 'Agent-based', 'Package monitoring'], 1,
  'The objectives phrase this pairing as "client-based vs. agentless" under vulnerable software. Agentless needs no software on the target; client-based installs an agent.'),
q('2.2', 'An organisation still runs an operating system that stopped receiving security updates two years ago. Which 2.2 attack surface is this?',
  ['Vulnerable software', 'Unsupported systems and applications', 'Open service ports', 'Misconfiguration'], 1,
  'Unsupported systems and applications is the specific 2.2 bullet for software past its support life. Vulnerable software is the broader category that includes patchable products.'),
q('2.2', 'An attacker pairs with an unattended device over a short-range wireless link to extract data. Which unsecure network vector is this?',
  ['Wireless', 'Bluetooth', 'Wired', 'Removable device'], 1,
  'Bluetooth is listed separately from wireless under unsecure networks, because its pairing and proximity model creates different risks from Wi-Fi.'),
q('2.2', 'A company outsources its IT helpdesk to a firm that holds administrative access to all workstations. That firm is which supply chain element?',
  ['Vendors', 'Managed service providers (MSPs)', 'Suppliers', 'Third-party vendors'], 1,
  'An MSP actively operates part of your environment and holds privileged access. Vendors sell you products and suppliers provide components — the level of access is the discriminator.'),
q('2.2', 'A company buys a commercial software product from a firm that has no access to its network. That firm is which supply chain element?',
  ['Managed service providers (MSPs)', 'Vendors', 'Suppliers', 'Service provider'], 1,
  'Vendors sell products. MSPs operate your systems with privileged access — the stem specifying no network access rules out an MSP.'),
q('2.2', 'A manufacturer sources electronic components from a firm that provides parts used in its products. That firm is which supply chain element?',
  ['Vendors', 'Suppliers', 'Managed service providers (MSPs)', 'Hardware provider'], 1,
  'Suppliers provide the components that go INTO what you build. Vendors sell you a finished product to use — the objectives list all three roles separately in 2.2.'),
q('2.2', 'An attacker sends thousands of emails impersonating a delivery company, hoping a fraction will click. Which technique is this?',
  ['Business email compromise', 'Phishing', 'Pretexting', 'Watering hole'], 1,
  'Phishing is the broad, untargeted net. Business email compromise targets one process using a trusted internal identity — volume and lack of targeting is the tell.'),
q('2.2', 'An attacker calls an employee pretending to be from IT support to obtain their password. Which technique is this?',
  ['Smishing', 'Vishing', 'Phishing', 'Impersonation'], 1,
  'Vishing is phishing over voice. Impersonation is also present — claiming to be IT support — but the question asks for the technique named by its delivery channel.'),
q('2.2', 'An attacker floods social media with fabricated claims about a company to damage its share price. Which technique does the objectives document name?',
  ['Misinformation/disinformation', 'Brand impersonation', 'Pretexting', 'Watering hole'], 0,
  'Misinformation/disinformation makes false content the attack itself rather than a lure to something else. That is what separates it from phishing.'),
q('2.2', 'An attacker convinces a receptionist they are a named senior manager from another office. Which technique is this?',
  ['Pretexting', 'Impersonation', 'Brand impersonation', 'Phishing'], 1,
  'Impersonation is claiming to be a specific PERSON. Pretexting is the invented story around the request. Brand impersonation is claiming to be a company.'),
q('2.2', 'An email is sent using a well-known bank\'s exact logo, fonts and layout to appear genuine. Which technique is this?',
  ['Typosquatting', 'Brand impersonation', 'Impersonation', 'Misinformation'], 1,
  'Brand impersonation copies the COMPANY\'S identity. Impersonation copies a specific PERSON. Typosquatting is about the domain name rather than the content.'),

/* 2.3 */
q('2.3', 'An attacker writes data into a region of process memory to alter the behaviour of a running application. Which vulnerability class is this?',
  ['Buffer overflow', 'Memory injection', 'Race conditions', 'Malicious update'], 1,
  'Memory injection places code or data into a running process. A buffer overflow is the specific case of writing past an allocated buffer\'s boundary.'),
q('2.3', 'An application copies user input into a fixed-size array without checking the length, overwriting adjacent memory. Which vulnerability is this?',
  ['Memory injection', 'Buffer overflow', 'Race conditions', 'Injection'], 1,
  'Buffer overflow is specifically writing beyond an allocation\'s boundary. Memory injection is the broader class of placing content into a process\'s memory.'),
q('2.3', 'In a race condition, what does the objectives document call the moment the application verifies a condition?',
  ['Time-of-use (TOU)', 'Time-of-check (TOC)', 'Time-of-day restriction', 'Validation'], 1,
  'Time-of-check is the verification; time-of-use is when the verified resource is actually used. The vulnerability lives in the gap between the two.'),
q('2.3', 'In a race condition, what does the objectives document call the moment the application acts on the resource it verified earlier?',
  ['Time-of-check (TOC)', 'Time-of-use (TOU)', 'Race window', 'Dependency'], 1,
  'Time-of-use is when the resource is consumed. If the resource changed since the time-of-check, the application acts on a stale assumption.'),
q('2.3', 'A business still runs a bespoke application written twenty years ago that no one can rebuild but that still receives occasional fixes. Which hardware/software vulnerability term applies?',
  ['End-of-life', 'Legacy', 'Firmware', 'Zero-day'], 1,
  'Legacy means old and difficult to change but not necessarily unsupported. End-of-life means support has definitively ended — the stem says fixes still arrive.'),
q('2.3', 'A cloud platform your application depends on suffers a breach that exposes your customers\' data. Which supply chain vulnerability does the objectives document name?',
  ['Software provider', 'Service provider', 'Hardware provider', 'Cloud-specific'], 1,
  'The objectives split supply chain into service, hardware and software providers. A platform you consume as a running service is a service provider.'),
q('2.3', 'Counterfeit network cards containing an undocumented chip are found in newly delivered servers. Which supply chain vulnerability is this?',
  ['Service provider', 'Hardware provider', 'Software provider', 'Firmware'], 1,
  'The compromise entered through physical components, which makes it a hardware provider issue. Firmware is the vulnerability class the implant might exploit, not the supply route.'),
q('2.3', 'A commercial application vendor ships a release containing a backdoor inserted by an attacker in their build system. Which supply chain vulnerability is this?',
  ['Hardware provider', 'Software provider', 'Service provider', 'Misconfiguration'], 1,
  'The compromise came through purchased software, so the software provider is the supply chain element. "Malicious update" is the matching application vulnerability term.'),
q('2.3', 'A user removes the manufacturer\'s restrictions from their phone\'s operating system to gain root access. Which mobile vulnerability is this?',
  ['Side loading', 'Jailbreaking', 'Malicious update', 'Misconfiguration'], 1,
  'Jailbreaking defeats the platform\'s protections entirely. Side loading installs one app around the store while those protections remain intact.'),
q('2.3', 'A privilege escalation flaw exists in the Windows kernel itself rather than in any installed application. Which vulnerability class is this?',
  ['Web-based', 'Operating system (OS)-based', 'Application', 'Firmware'], 1,
  'OS-based vulnerabilities are in the operating system rather than in software running on it. Firmware sits below the OS, in the device itself.'),
q('2.3', 'A misconfigured storage bucket in a public cloud exposes data to the internet, a risk that does not arise in the same way on premises. Which vulnerability class is this?',
  ['Misconfiguration', 'Cloud-specific', 'Supply chain', 'Virtualization'], 1,
  'Cloud-specific covers risks arising from the cloud model itself — shared responsibility, tenancy, exposed management planes. Misconfiguration is the broader class it belongs to.'),
q('2.3', 'An application uses a hashing algorithm with known collision weaknesses to protect stored passwords. Which vulnerability class is this?',
  ['Misconfiguration', 'Cryptographic', 'Application', 'Zero-day'], 1,
  'Cryptographic vulnerabilities are weaknesses in the choice or use of cryptography — weak algorithms, bad key management, poor randomness.'),
q('2.3', 'A database server is deployed with its administrative interface exposed and authentication disabled. Which vulnerability class is this?',
  ['Zero-day', 'Misconfiguration', 'Cryptographic', 'End-of-life'], 1,
  'Misconfiguration is a settings failure — the software is capable of being secure and was not set up that way. That distinguishes it from a flaw in the software itself.'),

/* 2.4 */
q('2.4', 'Malware encrypts an organisation\'s files and demands payment for the decryption key. Which malware type is this?',
  ['Trojan', 'Ransomware', 'Logic bomb', 'Worm'], 1,
  'Ransomware is defined by the extortion. It may be delivered by a trojan or spread by a worm — the objectives classify it by what it does once it arrives.'),
q('2.4', 'A user downloads what appears to be a free PDF utility; it works, but also installs a remote access backdoor. Which malware type is this?',
  ['Worm', 'Trojan', 'Virus', 'Bloatware'], 1,
  'A trojan is defined by DISGUISE — it pretends to be something useful. A virus needs a host file to infect; a worm needs no user action at all.'),
q('2.4', 'Software silently records browsing habits and transmits them to an advertiser without consent. Which malware type is this?',
  ['Bloatware', 'Spyware', 'Keylogger', 'Rootkit'], 1,
  'Spyware is defined by what it COLLECTS. A keylogger is the narrower case that captures keystrokes specifically — the stem describes browsing behaviour, not typing.'),
q('2.4', 'Malicious code attaches itself to a legitimate executable and spreads when users run and share that file. Which malware type is this?',
  ['Worm', 'Virus', 'Trojan', 'Logic bomb'], 1,
  'A virus needs a HOST FILE and a user action. A worm propagates by itself across the network. The requirement for a host is the discriminator.'),
q('2.4', 'Malware captures everything typed on a workstation, including credentials entered into a banking site. Which malware type is this?',
  ['Spyware', 'Keylogger', 'Rootkit', 'Trojan'], 1,
  'A keylogger specifically captures keystrokes. Spyware is the broader surveillance category — the objectives list both, and the stem naming typing is the tell.'),
q('2.4', 'An attacker physically attempts to force open a secured door to reach a server room. Which physical attack does the objectives document name?',
  ['Environmental', 'Brute force', 'RFID cloning', 'Impersonation'], 1,
  'Brute force appears twice in 2.4 — as a PHYSICAL attack meaning forcing a barrier, and as a PASSWORD attack meaning exhaustive guessing. The context decides which is meant.'),
q('2.4', 'A botnet of 50,000 compromised devices simultaneously floods a web service until it stops responding. Which network attack is this?',
  ['Denial of service', 'Distributed denial-of-service (DDoS)', 'Amplified', 'Resource consumption'], 1,
  'The word distributed means the traffic comes from many sources, which is what makes filtering hard. Resource consumption is the INDICATOR you would observe.'),
q('2.4', 'An attacker spoofs the victim\'s address so that responses from third-party servers are delivered to the victim rather than the attacker. Which DDoS characteristic is this?',
  ['Amplified', 'Reflected', 'On-path', 'Malicious code'], 1,
  'Reflected is about WHERE the response goes — bounced off an intermediary to the spoofed victim. Amplified is about the response being much LARGER than the request.'),
q('2.4', 'An attacker poisons a resolver\'s cache so users requesting a bank\'s site are sent to an attacker-controlled address. Which network attack does the objectives document name?',
  ['On-path', 'Domain Name System (DNS) attacks', 'Credential replay', 'Forgery'], 1,
  'DNS attacks is the named 2.4 category covering cache poisoning, hijacking and spoofing. The victim is redirected before any connection to the real site is attempted.'),
q('2.4', 'An attacker sets up a rogue access point with the same SSID as the corporate network to capture traffic. Which network attack category is this?',
  ['On-path', 'Wireless', 'Credential replay', 'DNS attacks'], 1,
  'Wireless is a named network attack category in 2.4. The rogue AP is also positioning the attacker on-path, but the attack category the objectives credit is wireless.'),
q('2.4', 'An attacker positions themselves between a client and server, relaying and able to alter traffic in both directions. Which attack is this?',
  ['Replay', 'On-path', 'Forgery', 'Downgrade'], 1,
  'On-path is the POSITION. Downgrade and replay are things the attacker can then do from it — the objectives replaced the older term "man-in-the-middle" with on-path.'),
q('2.4', 'An attacker injects executable content into a legitimate web page so it runs on visitors\' machines. Which network attack term does the objectives document list?',
  ['Malicious code', 'Injection', 'Forgery', 'Malicious update'], 0,
  'Malicious code is listed under network attacks in 2.4. Injection appears separately under application attacks — the objective\'s own grouping decides which is credited.'),
q('2.4', 'An attacker supplies input that an interpreter executes as a command rather than treating as data. Which application attack is this?',
  ['Directory traversal', 'Injection', 'Forgery', 'Buffer overflow'], 1,
  'Injection makes an interpreter execute attacker-supplied content. SQLi and XSS are specific instances listed in 2.3; injection is the general 2.4 application attack.'),
q('2.4', 'A crafted request causes an application to write past the end of an allocated memory region and execute attacker-supplied code. Which application attack is this?',
  ['Injection', 'Buffer overflow', 'Privilege escalation', 'Replay'], 1,
  'Buffer overflow appears both as a 2.3 vulnerability and a 2.4 attack. As an attack it is the act of exploiting the missing bounds check.'),
q('2.4', 'An attacker crafts a request that causes a victim\'s browser to submit an action to a site where the victim is already authenticated. Which application attack does the objectives document name?',
  ['Replay', 'Forgery', 'Injection', 'Privilege escalation'], 1,
  'Forgery is the 2.4 term covering request forgery attacks such as CSRF. The victim\'s existing session is what the attacker abuses, without ever stealing the credential.'),
q('2.4', 'An attacker exploits the mathematics of the birthday paradox to find two inputs producing the same hash far faster than brute force. Which attack is this?',
  ['Collision', 'Birthday', 'Downgrade', 'Brute force'], 1,
  'The birthday attack is the METHOD that exploits probability. A collision is the RESULT it produces. The stem describes the technique, not the outcome.'),
q('2.4', 'An attacker systematically tries every possible password against one account until it succeeds. Which password attack is this?',
  ['Spraying', 'Brute force', 'Credential replay', 'Birthday'], 1,
  'Brute force is exhaustive against one target and triggers lockout quickly. Spraying is one password across many accounts specifically to avoid that.'),
q('2.4', 'A helpdesk sees a surge of users unable to sign in because their accounts have been disabled by repeated failed attempts. Which indicator is this?',
  ['Concurrent session usage', 'Account lockout', 'Blocked content', 'Impossible travel'], 1,
  'Account lockout as an INDICATOR means you are seeing the side effect of an attack — most often password spraying or brute force hitting many accounts.'),
q('2.4', 'A single user account is found to have four simultaneous active sessions from four different devices. Which indicator is this?',
  ['Impossible travel', 'Concurrent session usage', 'Account lockout', 'Resource consumption'], 1,
  'Concurrent session usage is multiple LIVE sessions regardless of location. Impossible travel requires the geography-versus-time contradiction, which the stem does not give.'),
q('2.4', 'A security tool repeatedly prevents a workstation from reaching a known malicious domain, and the attempts continue. Which indicator is this?',
  ['Missing logs', 'Blocked content', 'Resource inaccessibility', 'Out-of-cycle logging'], 1,
  'Blocked content as an indicator means the control worked but something on the host keeps trying — persistent blocked attempts suggest malware is still resident.'),
q('2.4', 'A server\'s CPU and network utilisation sit at 100% with no legitimate workload to explain it. Which indicator is this?',
  ['Resource inaccessibility', 'Resource consumption', 'Blocked content', 'Account lockout'], 1,
  'Resource consumption is abnormal USE of resources — cryptomining, exfiltration, a bot. Resource inaccessibility is the different indicator that resources cannot be reached at all.'),
q('2.4', 'Staff report that a file share they use daily is suddenly unreachable and the files appear renamed. Which indicator is this?',
  ['Resource consumption', 'Resource inaccessibility', 'Blocked content', 'Missing logs'], 1,
  'Resource inaccessibility means legitimate users cannot reach what they should — a classic early ransomware indicator. Resource consumption is abnormally high usage instead.'),
q('2.4', 'A vendor publishes an advisory that its product is being actively exploited, and your organisation runs that product. Which indicator does the objectives document name?',
  ['Published/documented', 'Missing logs', 'Blocked content', 'Out-of-cycle logging'], 0,
  'Published/documented means the indicator comes from public reporting rather than your own telemetry. It is the one indicator on the list that originates outside your environment.'),

/* 2.5 */
q('2.5', 'A compromised laptop is immediately cut off from all network access while it is investigated. Which mitigation is this?',
  ['Segmentation', 'Isolation', 'Decommissioning', 'Monitoring'], 1,
  'Isolation removes ONE host from communication. Segmentation is the structural division of the whole network into zones and is a design decision rather than a response.'),
q('2.5', 'An organisation applies vendor security updates to all servers within 14 days of release. Which mitigation is this?',
  ['Configuration enforcement', 'Patching', 'Hardening', 'Monitoring'], 1,
  'Patching applies vendor fixes to remove known vulnerabilities. Configuration enforcement makes SETTINGS stick — it does not change the software version.'),
q('2.5', 'Data on backup tapes is protected so that a stolen tape reveals nothing. Which 2.5 mitigation is this?',
  ['Monitoring', 'Encryption', 'Isolation', 'Permissions'], 1,
  'Encryption appears as a 2.5 mitigation, a 1.4 cryptographic solution, a 3.3 method to secure data and a 5.1 standard. The objective the question sits in decides the credited word.'),
q('2.5', 'Security continuously reviews log and alert data across the estate to detect abnormal activity. Which 2.5 mitigation is this?',
  ['Monitoring', 'Patching', 'Segmentation', 'Configuration enforcement'], 0,
  'Monitoring is listed as a mitigation technique in 2.5 and again as an activity in 4.4. As a mitigation it is the ongoing observation that makes detection possible.'),
q('2.5', 'A management platform detects that a server\'s audit policy has been changed and automatically restores the approved setting. Which mitigation is this?',
  ['Patching', 'Configuration enforcement', 'Application allow list', 'Monitoring'], 1,
  'Configuration enforcement makes settings STICK and revert drift. An allow list controls which programs may run, which is a different object entirely.'),
q('2.5', 'A router is configured with an ordered set of rules permitting or denying traffic by address and port. What is this construct?',
  ['Permissions', 'Access control list (ACL)', 'Application allow list', 'Segmentation'], 1,
  'An ACL is the ordered ruleset attached to a resource or interface. Permissions are the rights granted to a principal over an object — one describes traffic, the other describes people.'),
q('2.5', 'A shared folder is configured so that the finance group can read and write while everyone else has no access. Which mitigation is this?',
  ['Access control list (ACL)', 'Permissions', 'Least privilege', 'Isolation'], 1,
  'Permissions are the rights assigned to principals over an object. Least privilege is the PRINCIPLE that would justify keeping them minimal; permissions are the mechanism.'),
q('2.5', 'Antimalware software with behavioural detection is deployed to every workstation. Which hardening technique does the objectives document name?',
  ['Host-based firewall', 'Installation of endpoint protection', 'Host-based intrusion prevention system (HIPS)', 'Monitoring'], 1,
  'Installation of endpoint protection is the named hardening technique for antimalware. HIPS is the narrower control that blocks behaviour at the host, listed separately.'),
q('2.5', 'Each workstation runs software that filters inbound and outbound connections on that machine only. Which hardening technique is this?',
  ['Host-based intrusion prevention system (HIPS)', 'Host-based firewall', 'Network access control', 'Installation of endpoint protection'], 1,
  'A host-based firewall filters CONNECTIONS on one machine. HIPS inspects BEHAVIOUR and blocks exploit activity — both are host controls but they act on different things.'),
q('2.5', 'A newly deployed switch is configured to replace the vendor\'s built-in administrator credentials before going into service. Which hardening technique is this?',
  ['Removal of unnecessary software', 'Default password changes', 'Disabling ports/protocols', 'Configuration enforcement'], 1,
  'Default password changes is the named hardening technique. It directly answers the 2.2 attack surface "default credentials" — the objectives pair the risk and the control.'),
q('2.5', 'A server build removes the sample web applications, games and development tools shipped with the operating system. Which hardening technique is this?',
  ['Disabling ports/protocols', 'Removal of unnecessary software', 'Application allow list', 'Patching'], 1,
  'Removal of unnecessary software takes the package OFF the machine. Disabling ports/protocols leaves the software installed but stops it listening — one removes the room, the other closes the door.'),
];
