// Coverage bank — Domain 3.

const q = (objective, stem, options, answer, explanation) =>
  ({ objective, stem, options, answer, explanation });

export default [

/* 3.1 */
q('3.1', 'An organisation keeps sensitive workloads in its own data centre while running public-facing services in a public cloud. Which 3.1 consideration does the objectives document name for this arrangement?',
  ['Hybrid considerations', 'Multi-cloud systems', 'On-premises', 'Third-party vendors'], 0,
  'Hybrid considerations covers running across both models at once — identity, connectivity and data flow between them. Multi-cloud (3.4) means more than one cloud PROVIDER, not cloud plus on-premises.'),
q('3.1', 'A cloud deployment depends on several external companies for logging, identity and backup. Which 3.1 cloud consideration does the objectives document name?',
  ['Responsibility matrix', 'Third-party vendors', 'Hybrid considerations', 'Supply chain'], 1,
  'Third-party vendors is a named cloud consideration in 3.1 — each additional provider adds its own trust and dependency. The responsibility matrix divides duties with the primary provider.'),
q('3.1', 'A company runs all its own servers in a facility it owns and operates. Which architecture model is this?',
  ['On-premises', 'Centralized', 'Private cloud', 'Air-gapped'], 0,
  'On-premises means you own and operate the infrastructure and the facility. It is listed in 3.1 as a peer of cloud, and it changes who holds every row of the responsibility matrix.'),
q('3.1', 'An organisation must choose between one central security team enforcing uniform policy and each division running its own. Which 3.1 consideration is this?',
  ['Centralized vs. decentralized', 'On-premises', 'High availability', 'Segmentation'], 0,
  'Centralized gives consistency but a larger blast radius; decentralized spreads risk but makes uniform policy hard. The objectives phrase it exactly as this comparison.'),
q('3.1', 'A physical server runs several guest operating systems, each with its own kernel, managed by a hypervisor. Which technology is this?',
  ['Containerization', 'Virtualization', 'Serverless', 'Microservices'], 1,
  'Virtualization gives each guest a full OS. Containers share the HOST kernel — that single difference is why VM escape and container escape are different problems.'),
q('3.1', 'Networked sensors, cameras and thermostats with limited processing power and infrequent updates are which architecture category?',
  ['Embedded systems', 'IoT', 'ICS/SCADA', 'RTOS'], 1,
  'IoT is the objectives\' term for consumer and building network-connected devices. ICS/SCADA is industrial process control, and embedded systems is the broader hardware category.'),
q('3.1', 'Systems that monitor and control physical processes in a water treatment plant, often over legacy protocols, are which architecture category?',
  ['IoT', 'Industrial control systems (ICS)/supervisory control and data acquisition (SCADA)', 'Real-time operating system (RTOS)', 'Embedded systems'], 1,
  'ICS/SCADA covers industrial process control. Availability and safety outrank confidentiality in these environments, which inverts the usual CIA priority.'),
q('3.1', 'A purpose-built computer is integrated into a larger device to perform one dedicated function, such as the controller in a medical pump. What is this?',
  ['IoT', 'Embedded systems', 'ICS/SCADA', 'Microservices'], 1,
  'Embedded systems are dedicated computers inside a larger product. The security implication is that they are frequently unpatchable, which links to the 3.1 consideration "inability to patch".'),
q('3.1', 'An architecture is designed so that the failure of any single component does not interrupt the service. Which 3.1 concept is this?',
  ['Resilience', 'High availability', 'Scalability', 'Continuity of operations'], 1,
  'High availability targets continuous uptime through redundancy. Resilience is the broader ability to absorb and recover from disruption, including events that do cause an outage.'),
q('3.1', 'A network separates traffic into isolated broadcast domains using VLANs on shared switching hardware. Which concept is this?',
  ['Physical isolation', 'Logical segmentation', 'Air-gapped', 'Software-defined networking (SDN)'], 1,
  'Logical segmentation uses configuration on shared hardware and can be misconfigured. Physical isolation uses separate hardware and cabling, and cannot be undone by a config error.'),
q('3.1', 'Two networks share no cabling, switches or wireless path of any kind. Which concept does the objectives document name?',
  ['Logical segmentation', 'Physical isolation', 'Security zones', 'Screened subnet'], 1,
  'Physical isolation is the parent concept; air-gapped is the specific term the objectives nest beneath it. Neither can be defeated by a configuration mistake.'),
q('3.1', 'Network forwarding decisions are centralised into a controller that programs the switches, separating control from forwarding. Which technology is this?',
  ['Software-defined networking (SDN)', 'Software-defined wide area network (SD-WAN)', 'Logical segmentation', 'Infrastructure as code (IaC)'], 0,
  'SDN separates the control plane from the data plane inside the network. SD-WAN (3.2) applies similar ideas to connecting sites over wide-area links.'),
q('3.1', 'A vendor still supports a product and issues fixes, but the organisation must check whether a fix exists for a given flaw before planning remediation. Which 3.1 consideration is this?',
  ['Inability to patch', 'Patch availability', 'Ease of deployment', 'Responsiveness'], 1,
  'Patch availability asks whether a fix EXISTS. Inability to patch is the stronger condition that you cannot apply one even when it does — for example on a certified medical device.'),

/* 3.2 */
q('3.2', 'Deciding whether a firewall belongs at the internet edge, between internal zones, or in front of one application is a question about which 3.2 consideration?',
  ['Device placement', 'Security zones', 'Connectivity', 'Attack surface'], 0,
  'Device placement is where a control sits in the topology. Security zones are the trust regions the placement creates boundaries between — one is the box, the other is the region.'),
q('3.2', 'A network is divided into regions of differing trust, each with defined rules for what may cross between them. What are these regions called?',
  ['Screened subnets', 'Security zones', 'Implicit trust zones', 'Segmentation'], 1,
  'Security zones are the trust regions. A screened subnet is one specific zone type for internet-facing services, and implicit trust zones (1.2) are what Zero Trust exists to remove.'),
q('3.2', 'Reducing the number of listening services, open ports and exposed interfaces on a system reduces which property?',
  ['Attack surface', 'Security zones', 'Connectivity', 'Failure modes'], 0,
  'Attack surface is the total set of points an attacker could interact with. Every hardening technique in 2.5 exists to reduce it, which is why it appears as a 3.2 design consideration.'),
q('3.2', 'Deciding whether a remote site reaches head office over a dedicated circuit, a VPN over the internet, or a cellular link is a question about which consideration?',
  ['Device placement', 'Connectivity', 'Security zones', 'Attack surface'], 1,
  'Connectivity is how components reach each other and over what path. Each option carries a different exposure, which is why the objectives list it as a security consideration rather than a networking one.'),
q('3.2', 'A network security device is configured so that if it loses power, traffic continues to flow unfiltered. Which failure mode is this?',
  ['Fail-closed', 'Fail-open', 'High availability', 'Active/passive'], 1,
  'Fail-open keeps traffic flowing and favours availability. Fail-closed blocks everything and favours security. Neither is universally right — a hospital and a bank would choose differently.'),
q('3.2', 'A monitoring device receives copied traffic and can raise alerts but cannot drop packets. Which device attribute describes this?',
  ['Inline', 'Passive', 'Active', 'Fail-open'], 1,
  'Active versus passive is about whether the device can ACT. An IDS is passive, an IPS active. Inline versus tap is the separate question of where it sits in the path.'),
q('3.2', 'Which device forwards requests on a client\'s behalf, can cache responses and hides the client\'s address from the destination?',
  ['Jump server', 'Proxy server', 'Load balancer', 'Sensors'], 1,
  'A proxy acts on your behalf without you logging into it. A jump server is a host you authenticate to and work from — the difference is whether you get a session on the box.'),
q('3.2', 'Which appliance pair detects suspicious traffic, with one variant able to block it and the other only to alert?',
  ['WAF and NGFW', 'Intrusion prevention system (IPS)/intrusion detection system (IDS)', 'Proxy and jump server', 'UTM and SASE'], 1,
  'The objectives list them as one bullet because they are the same technology in two postures. IPS is inline and blocks; IDS is out of band and alerts.'),
q('3.2', 'Which appliance distributes incoming requests across a pool of servers and stops sending traffic to any that fail a health check?',
  ['Proxy server', 'Load balancer', 'Jump server', 'Sensors'], 1,
  'A load balancer spreads work and removes unhealthy members. It contributes to availability, which is why it appears in 3.2 appliances and again in 3.4 high availability.'),
q('3.2', 'Devices placed at points across the network to collect traffic and telemetry for analysis are called what in the objectives?',
  ['Sensors', 'Load balancers', 'Proxy servers', 'Jump servers'], 0,
  'Sensors is the objectives\' term for collection points, listed under network appliances in 3.2 and again as a tool in 4.4. Their placement determines what you can see.'),
q('3.2', 'Which framework does 802.1X carry to transport the actual authentication exchange between a device and the authentication server?',
  ['RADIUS', 'Extensible Authentication Protocol (EAP)', 'TACACS+', 'SAML'], 1,
  'EAP is the framework carried inside 802.1X; RADIUS is the back-end server the authenticator talks to. The objectives list 802.1X and EAP together under port security.'),
q('3.2', 'A single appliance provides firewalling, antivirus, intrusion prevention, content filtering and VPN in one product. Which firewall type is this?',
  ['Next-generation firewall (NGFW)', 'Unified threat management (UTM)', 'Web application firewall (WAF)', 'Layer 4 firewall'], 1,
  'UTM is defined by CONSOLIDATION of many functions into one box, historically for smaller sites. NGFW is defined by DEPTH — application and identity awareness in the filtering itself.'),
q('3.2', 'A firewall makes decisions using application awareness, user identity and integrated threat intelligence rather than ports alone. Which type is this?',
  ['Unified threat management (UTM)', 'Next-generation firewall (NGFW)', 'Layer 4 firewall', 'Web application firewall (WAF)'], 1,
  'NGFW adds identity and application awareness to filtering. UTM is about bundling many separate functions together — the discriminator is depth of inspection versus breadth of features.'),
q('3.2', 'An engineer needs to administer servers from home over the internet. Which 3.2 secure communication category does this fall under?',
  ['Tunneling', 'Remote access', 'Software-defined wide area network (SD-WAN)', 'Port security'], 1,
  'Remote access is the named category for reaching internal resources from outside. VPN and tunneling are the mechanisms that make it safe — the objectives list all three separately.'),
q('3.2', 'Which protocol is commonly used to secure a VPN tunnel at the application layer, and also secures HTTPS?',
  ['Internet protocol security (IPSec)', 'Transport Layer Security (TLS)', 'Secure Shell', 'Generic Routing Encapsulation'], 1,
  'The objectives name TLS and IPSec as the two tunneling protocols. TLS operates higher in the stack and traverses NAT easily; IPSec operates at the network layer.'),
q('3.2', 'Which protocol suite secures traffic at the network layer using ESP and AH, and requires NAT traversal to cross an address-translating device?',
  ['Transport Layer Security (TLS)', 'Internet protocol security (IPSec)', 'Secure Shell', 'Point-to-Point Tunneling Protocol'], 1,
  'IPSec works at the network layer, which is exactly why NAT breaks it and NAT-T exists. ESP and AH are IP protocol numbers rather than ports, so there is no port for a firewall to permit.'),
q('3.2', 'An organisation replaces expensive private circuits between branches with policy-driven connections across multiple internet links. Which technology is this?',
  ['Secure access service edge (SASE)', 'Software-defined wide area network (SD-WAN)', 'Virtual private network (VPN)', 'Software-defined networking (SDN)'], 1,
  'SD-WAN is the connectivity technology alone. SASE is SD-WAN with a cloud-delivered security stack folded in — the stem mentions no security services.'),
q('3.2', 'Given a set of candidate controls, choosing the combination that best addresses the identified risks within the available budget is which 3.2 activity?',
  ['Selection of effective controls', 'Device placement', 'Attack surface', 'Security zones'], 0,
  'Selection of effective controls is its own 3.2 bullet. It is the judgement step that turns a list of possible controls into a design, and it is where cost and risk are traded off.'),

/* 3.3 */
q('3.3', 'Data whose handling is dictated by an external law or standard, such as cardholder or health data, is which data type?',
  ['Trade secret', 'Regulated', 'Legal information', 'Financial information'], 1,
  'Regulated data is defined by an EXTERNAL obligation governing it. The other types describe what the data is about, not who compels you to protect it.'),
q('3.3', 'Patents, copyrights and trademarks belonging to a company are which data type?',
  ['Trade secret', 'Intellectual property', 'Regulated', 'Legal information'], 1,
  'Intellectual property is the broad category of protected creations. A trade secret is the subset whose value depends on never being disclosed — a patent is published by design.'),
q('3.3', 'Contracts, case files and privileged correspondence held by a company are which data type?',
  ['Financial information', 'Legal information', 'Regulated', 'Intellectual property'], 1,
  'Legal information is its own data type in 3.3, and it often carries additional obligations such as legal hold and privilege that other categories do not.'),
q('3.3', 'Ledgers, payroll records and management accounts are which data type?',
  ['Legal information', 'Financial information', 'Regulated', 'Critical'], 1,
  'Financial information is a named data type. It frequently overlaps with regulated data — SOX for public companies — but the objectives list the two separately.'),
q('3.3', 'Which classification does the objectives document list for data that requires protection but is not the most tightly controlled tier?',
  ['Public', 'Sensitive', 'Critical', 'Restricted'], 1,
  'Sensitive is a general protective label. The six classifications all overlap in ordinary English, which is why the exam expects the exact word rather than a judgement about severity.'),
q('3.3', 'Which classification applies to information intended to be kept private within the organisation and shared only with those who need it?',
  ['Public', 'Confidential', 'Critical', 'Regulated'], 1,
  'Confidential is a named classification in the 3.3 list. Regulated is a data TYPE rather than a classification — the objectives keep the two lists separate.'),
q('3.3', 'Which classification applies to information that may be freely disclosed with no harm?',
  ['Sensitive', 'Public', 'Private', 'Restricted'], 1,
  'Public is the lowest tier and the only one requiring no confidentiality control — although integrity still matters, since defacement of public data is still a breach.'),
q('3.3', 'Which classification denotes the most tightly controlled tier, where access is limited to a named few?',
  ['Confidential', 'Restricted', 'Sensitive', 'Private'], 1,
  'Restricted is the tightest access tier in the 3.3 list. Confidential and sensitive are broader protective labels — the exam wants the specific word.'),
q('3.3', 'Which classification is used for information relating to an identifiable individual?',
  ['Confidential', 'Private', 'Sensitive', 'Restricted'], 1,
  'Private is the classification associated with personal information. The individual it describes is the data subject, which is the 5.4 privacy term for the same person.'),
q('3.3', 'Customer records sitting in a database on disk, not currently being read or transmitted, are in which data state?',
  ['Data in transit', 'Data at rest', 'Data in use', 'Data sovereignty'], 1,
  'At rest means stored and idle. The control that matches is encryption at rest — full-disk, database or record-level from the 1.4 encryption levels.'),
q('3.3', 'Data moving between a browser and a web server is in which state?',
  ['Data at rest', 'Data in transit', 'Data in use', 'Data in memory'], 1,
  'In transit means crossing a network. The matching control is transport encryption — TLS or IPSec from the 3.2 tunneling list.'),
q('3.3', 'A service determines which country a user is connecting from in order to apply the correct handling rules. Which 3.3 consideration is this?',
  ['Data sovereignty', 'Geolocation', 'Geographic restrictions', 'Data states'], 1,
  'Geolocation is simply KNOWING where something or someone is. Sovereignty is the legal consequence of location, and geographic restrictions is the control you enforce as a result.'),
q('3.3', 'A field containing a national insurance number is stored in a form that cannot be read without a key. Which method to secure data is this?',
  ['Masking', 'Encryption', 'Tokenization', 'Obfuscation'], 1,
  'Encryption is reversible with the key and protects the value itself. Masking hides characters on display; tokenization substitutes a reference and removes the original.'),
q('3.3', 'A system stores only an irreversible digest of each password so the original cannot be recovered even by administrators. Which method to secure data is this?',
  ['Encryption', 'Hashing', 'Tokenization', 'Masking'], 1,
  'Hashing is one-way and is used where you never need the original back — only to compare. Encryption would be the wrong choice here precisely because it is reversible.'),
q('3.3', 'A test environment is populated with production data in which names and addresses have been replaced by realistic but false values. Which method is this?',
  ['Tokenization', 'Masking', 'Encryption', 'Segmentation'], 1,
  'Masking replaces or hides values while keeping the data usable for testing. Tokenization keeps a reversible mapping in a vault, which a test environment does not need.'),
q('3.3', 'A retailer stores a meaningless surrogate value in its order system and keeps the real card number in a separate vault. Which method is this?',
  ['Masking', 'Tokenization', 'Hashing', 'Obfuscation'], 1,
  'Tokenization removes the real value from the system and can retrieve it through the vault. This is why it reduces PCI DSS scope in a way that masking does not.'),
q('3.3', 'Source code is deliberately transformed so that it remains functional but is difficult for a human to understand. Which method is this?',
  ['Encryption', 'Obfuscation', 'Masking', 'Hashing'], 1,
  'Obfuscation makes data or code hard to interpret without making it unusable. It is not a confidentiality control in the cryptographic sense — a determined analyst can still reverse it.'),
q('3.3', 'Cardholder data is confined to a dedicated network zone with strict controls on what may reach it. Which method to secure data is this?',
  ['Permission restrictions', 'Segmentation', 'Geographic restrictions', 'Isolation'], 1,
  'Segmentation confines data to a controlled zone and is the standard way to reduce PCI DSS scope. Permission restrictions control WHO may access it rather than WHERE it lives.'),
q('3.3', 'Access to a document library is limited so that only members of the legal team can open its contents. Which method to secure data is this?',
  ['Segmentation', 'Permission restrictions', 'Encryption', 'Masking'], 1,
  'Permission restrictions control who may access the data. Segmentation controls where it can be reached from — one is about identity, the other about network position.'),

/* 3.4 */
q('3.4', 'A recovery site consists of space, power and network connectivity but no installed servers or data. Which site type is this?',
  ['Warm', 'Cold', 'Hot', 'Geographic dispersion'], 1,
  'Cold is the cheapest and slowest — an empty room. Warm has equipment installed but needs data restored; hot is running with current data and can take traffic immediately.'),
q('3.4', 'A recovery site has hardware installed and configured but requires data to be restored before it can take production traffic. Which site type is this?',
  ['Cold', 'Warm', 'Hot', 'Multi-cloud'], 1,
  'Warm sits between cold and hot: the equipment is ready but the data is not current. Time-to-service is the discriminator across all three.'),
q('3.4', 'Recovery sites are deliberately located hundreds of miles apart so that one regional event cannot affect both. Which concept is this?',
  ['Platform diversity', 'Geographic dispersion', 'Multi-cloud systems', 'Continuity of operations'], 1,
  'Geographic dispersion is about DISTANCE, protecting against regional events. Platform diversity is about using different technologies, which protects against a shared vulnerability instead.'),
q('3.4', 'An organisation deliberately uses firewalls from two different vendors so that a single vulnerability cannot compromise every device. Which concept is this?',
  ['Multi-cloud systems', 'Platform diversity', 'Geographic dispersion', 'High availability'], 1,
  'Platform diversity uses different TECHNOLOGY so a common flaw cannot affect everything. Multi-cloud uses different PROVIDERS — the discriminator is what is being varied.'),
q('3.4', 'A plan defines how essential business functions will keep running during a prolonged disruption, including manual workarounds. Which concept is this?',
  ['Continuity of operations', 'Capacity planning', 'High availability', 'Recovery'], 0,
  'Continuity of operations is about keeping the BUSINESS FUNCTION going by any means, including non-technical ones. High availability is a technical property of the infrastructure.'),
q('3.4', 'A disaster recovery test actually switches production traffic to the secondary site and runs there. Which test type is this?',
  ['Parallel processing', 'Fail over', 'Simulation', 'Tabletop exercise'], 1,
  'Fail over actually CUTS OVER. Parallel processing runs both and compares without cutting over — the presence or absence of a real switch is the discriminator.'),
q('3.4', 'A test injects a realistic scenario and has staff carry out their actual response steps against real systems. Which test type is this?',
  ['Tabletop exercise', 'Simulation', 'Fail over', 'Parallel processing'], 1,
  'Simulation exercises the people and systems for real. A tabletop is discussion only — the exam relies on whether anything is actually touched.'),
q('3.4', 'Backups are written to a local appliance for fast restore and replicated to a distant facility for disaster protection. Which backup consideration is this?',
  ['Frequency', 'Onsite/offsite', 'Replication', 'Snapshots'], 1,
  'Onsite/offsite is the named consideration for where copies live. Onsite gives speed, offsite gives protection from a site-level event — most designs need both.'),
q('3.4', 'A decision to run backups hourly rather than nightly is driven mainly by which backup consideration?',
  ['Onsite/offsite', 'Frequency', 'Journaling', 'Recovery'], 1,
  'Frequency determines how much data can be lost, which is exactly what the recovery point objective specifies. RPO drives frequency, and frequency drives cost.'),
q('3.4', 'Backup media is protected so that a stolen tape or intercepted cloud transfer reveals nothing. Which backup consideration is this?',
  ['Snapshots', 'Encryption', 'Replication', 'Onsite/offsite'], 1,
  'Encryption is listed explicitly as a backup consideration. Backups concentrate an organisation\'s entire dataset in one portable object, which is why it is called out separately here.'),
q('3.4', 'An administrator takes a point-in-time image of a virtual machine before applying a risky patch, so it can be reverted. What is this?',
  ['Replication', 'Snapshots', 'Journaling', 'Backups'], 1,
  'A snapshot captures STATE at one moment and is ideal for short-term rollback. It is not a substitute for backup, because it usually depends on the same storage as the original.'),
q('3.4', 'The process of restoring data and returning a service to operation from backup media is which named backup consideration?',
  ['Replication', 'Recovery', 'Snapshots', 'Frequency'], 1,
  'Recovery is listed as its own backup consideration — a backup that has never been restored is unproven, which is why the objectives name the restore as well as the copy.'),
q('3.4', 'Data is continuously copied to a second location so that the copy stays current with the primary. Which backup consideration is this?',
  ['Snapshots', 'Replication', 'Journaling', 'Onsite/offsite'], 1,
  'Replication is CONTINUOUS copying and keeps the RPO near zero. Its weakness is that it faithfully replicates corruption and ransomware too, which snapshots and backups protect against.'),
q('3.4', 'Which power component supplies sustained electricity for hours or days during an extended outage?',
  ['Uninterruptible power supply (UPS)', 'Generators', 'Power distribution unit', 'Capacity planning'], 1,
  'A generator sustains the load for a long period but takes time to start. A UPS covers the seconds or minutes until it does — duration versus immediacy is the discriminator.'),
q('3.4', 'Which statement about clustering is correct?',
  ['It presents multiple nodes as a single logical system', 'It only distributes requests without shared state', 'It requires all nodes to be in the same rack', 'It is another name for load balancing'], 0,
  'A cluster acts as one logical system with coordinated state and failover. Load balancing distributes requests across independent servers that need not know about each other.'),
];
