// Coverage bank — Domain 4, the 28% domain.

const q = (objective, stem, options, answer, explanation) =>
  ({ objective, stem, options, answer, explanation });

export default [

/* 4.1 */
q('4.1', 'Which hardening target does the objectives document name for phones and tablets carried by staff?',
  ['Workstations', 'Mobile devices', 'IoT devices', 'Embedded systems'], 1,
  'Mobile devices head the 4.1 hardening targets list. They are hardened largely through MDM, which is why the objectives pair the target and the tool in the same objective.'),
q('4.1', 'Applying a secure baseline to staff desktops and laptops addresses which hardening target?',
  ['Servers', 'Workstations', 'Mobile devices', 'Cloud infrastructure'], 1,
  'Workstations is the named target for end-user computers. The techniques applied come from the 2.5 hardening list — endpoint protection, host firewall, removing unnecessary software.'),
q('4.1', 'Disabling unused ports and turning off legacy management protocols on layer 2 network devices addresses which hardening target?',
  ['Routers', 'Switches', 'Cloud infrastructure', 'Servers'], 1,
  'Switches are named separately from routers in the 4.1 target list. Port security and 802.1X from objective 3.2 are the controls most associated with them.'),
q('4.1', 'Securing the devices that forward traffic between networks, including their management planes and routing protocols, addresses which hardening target?',
  ['Switches', 'Routers', 'Servers', 'Embedded systems'], 1,
  'Routers are listed separately from switches. Their distinct risks are routing protocol manipulation and exposed management interfaces reachable from other networks.'),
q('4.1', 'Applying baselines to storage buckets, security groups and identity policies in a public cloud addresses which hardening target?',
  ['Servers', 'Cloud infrastructure', 'Workstations', 'IoT devices'], 1,
  'Cloud infrastructure is its own hardening target. The controls are configuration rather than agents, which is why misconfiguration is the dominant cloud vulnerability in 2.3.'),
q('4.1', 'Removing unnecessary roles and services from machines that host applications and databases addresses which hardening target?',
  ['Workstations', 'Servers', 'Switches', 'RTOS'], 1,
  'Servers are named separately from workstations because their baselines differ — a server baseline strips interactive features a workstation needs.'),
q('4.1', 'Hardening a purpose-built controller inside a manufacturing machine, which cannot run an agent, addresses which target?',
  ['IoT devices', 'Embedded systems', 'Workstations', 'Cloud infrastructure'], 1,
  'Embedded systems are dedicated computers inside larger products. Because they usually cannot run security software, the practical control is network isolation.'),
q('4.1', 'A system whose operating system guarantees response within fixed time bounds must be hardened without affecting timing. Which hardening target is this?',
  ['Embedded systems', 'RTOS', 'ICS/SCADA', 'IoT devices'], 1,
  'RTOS is named as its own hardening target. Its defining constraint is that any control adding latency may break the guarantee the system exists to provide.'),
q('4.1', 'Changing default credentials and disabling universal plug and play on networked cameras and sensors addresses which hardening target?',
  ['Embedded systems', 'IoT devices', 'Mobile devices', 'Servers'], 1,
  'IoT devices is a named target. Default credentials are their signature weakness, which is why the 2.5 technique "default password changes" is the first control applied.'),
q('4.1', 'A wireless engineer produces a colour-coded floor plan showing signal coverage and dead spots. What is this output called?',
  ['Site survey', 'Heat maps', 'Benchmark', 'Dashboard'], 1,
  'The heat map is the OUTPUT; the site survey is the ACTIVITY that produced it. The objectives list both under wireless installation considerations.'),
q('4.1', 'Which solution centrally enforces encryption, passcode policy and remote wipe on employee phones?',
  ['Unified Endpoint Management', 'Mobile device management (MDM)', 'Network access control', 'Group Policy'], 1,
  'MDM is the named 4.1 mobile solution. It is the enforcement point for whichever deployment model — BYOD, COPE or CYOD — the organisation has chosen.'),
q('4.1', 'Employees use their own personally purchased phones for work email, and the company does not own the hardware. Which deployment model is this?',
  ['Corporate-owned, personally enabled (COPE)', 'Bring your own device (BYOD)', 'Choose your own device (CYOD)', 'Mobile device management (MDM)'], 1,
  'BYOD means the EMPLOYEE owns it, which is why it creates the hardest privacy and wipe questions — the company cannot simply erase a device it does not own.'),
q('4.1', 'Employees select a device from an approved catalogue, and the company purchases and owns it. Which deployment model is this?',
  ['Bring your own device (BYOD)', 'Choose your own device (CYOD)', 'Corporate-owned, personally enabled (COPE)', 'Corporate-owned business-only'], 1,
  'CYOD gives the employee the CHOICE from an approved list while the company still owns the device. COPE is company-chosen and company-owned with personal use allowed.'),
q('4.1', 'A RADIUS server authenticates each wireless user individually against the directory rather than using a shared passphrase. Which wireless security setting is this?',
  ['WPA3', 'AAA/Remote Authentication Dial-In User Service (RADIUS)', 'Cryptographic protocols', 'Authentication protocols'], 1,
  'The objectives name AAA/RADIUS as a wireless security setting. It is what makes enterprise wireless per-user rather than per-network, so revoking one user does not require rekeying everyone.'),
q('4.1', 'Choosing CCMP with AES rather than TKIP for a wireless network is a decision about which wireless security setting?',
  ['Authentication protocols', 'Cryptographic protocols', 'AAA/RADIUS', 'WPA3'], 1,
  'Cryptographic protocols govern how the traffic is ENCRYPTED. Authentication protocols govern how users PROVE identity — the objectives list them as two separate settings.'),
q('4.1', 'Selecting EAP-TLS rather than PEAP for an enterprise wireless network is a decision about which wireless security setting?',
  ['Cryptographic protocols', 'Authentication protocols', 'WPA3', 'Site surveys'], 1,
  'Authentication protocols determine how identity is proven. EAP-TLS requires certificates on both sides and is the strongest of the EAP methods.'),

/* 4.2 */
q('4.2', 'A formal process governs how new hardware and software are evaluated, approved and purchased, including security requirements. Which 4.2 activity is this?',
  ['Assignment/accounting', 'Acquisition/procurement process', 'Monitoring/asset tracking', 'Disposal/decommissioning'], 1,
  'Acquisition/procurement is the first stage of the asset lifecycle and the cheapest point to impose security requirements — after purchase you are negotiating from a weaker position.'),
q('4.2', 'A maintained register lists every device the organisation owns, with its location, owner and configuration. What is this register?',
  ['Enumeration', 'Inventory', 'Classification', 'Attestation'], 1,
  'The inventory is the RECORD you hold. Enumeration is the act of DISCOVERING what is actually connected — the gap between them is where shadow IT lives.'),
q('4.2', 'A company defines how long each category of record must be kept before it may be destroyed. Which 4.2 element is this?',
  ['Sanitization', 'Data retention', 'Certification', 'Destruction'], 1,
  'Data retention sets how long you must keep data. It can conflict directly with a data subject\'s right to be forgotten in 5.4, which is why both are examinable.'),
q('4.2', 'Failed drives containing classified data are shredded so that no portion of the platters remains readable. Which disposal method is this?',
  ['Sanitization', 'Destruction', 'Certification', 'Decommissioning'], 1,
  'Destruction makes the hardware permanently unusable. Sanitization removes the data but leaves the device serviceable — whether the hardware survives is the discriminator.'),

/* 4.3 */
q('4.3', 'An automated tool probes hosts for known vulnerable software versions and misconfigurations. Which identification method is this?',
  ['Penetration testing', 'Vulnerability scan', 'System/process audit', 'Package monitoring'], 1,
  'A vulnerability scan identifies known weaknesses at breadth. A penetration test attempts to EXPLOIT them and demonstrate impact — coverage versus proof is the discriminator.'),
q('4.3', 'A tool analyses application source code for insecure patterns without running the program. Which method is this?',
  ['Dynamic analysis', 'Static analysis', 'Package monitoring', 'Vulnerability scan'], 1,
  'Static analysis reads the code at rest. Dynamic analysis runs the application and observes it — the give-away is whether the program executes.'),
q('4.3', 'A tool exercises a running web application with unexpected inputs to find flaws that appear only at runtime. Which method is this?',
  ['Static analysis', 'Dynamic analysis', 'Package monitoring', 'Penetration testing'], 1,
  'Dynamic analysis requires the application to be RUNNING. It finds configuration and runtime issues that static analysis cannot see, and misses code paths it never exercises.'),
q('4.3', 'A commercial threat feed is purchased from a security vendor and is not publicly available. Which feed type is this?',
  ['Open-source intelligence (OSINT)', 'Proprietary/third-party', 'Information-sharing organization', 'Dark web'], 1,
  'Proprietary feeds are commercial products. OSINT is public and free; an information-sharing organization is a members-only community such as an ISAC.'),
q('4.3', 'A bank participates in a sector body where member institutions exchange indicators of compromise with each other. Which threat feed type is this?',
  ['Proprietary/third-party', 'Information-sharing organization', 'Open-source intelligence (OSINT)', 'Dark web'], 1,
  'An information-sharing organization is a trusted member community, such as an ISAC. Participation is reciprocal, which distinguishes it from a feed you simply buy.'),
q('4.3', 'Analysts monitor criminal marketplaces for mentions of the company\'s stolen credentials. Which threat feed source is this?',
  ['Open-source intelligence (OSINT)', 'Dark web', 'Proprietary/third-party', 'Responsible disclosure program'], 1,
  'Dark web monitoring is named as its own intelligence source. It gives the earliest warning of a breach you have not yet detected internally.'),
q('4.3', 'An engagement attempts to exploit discovered weaknesses to demonstrate what an attacker could actually achieve. Which identification method is this?',
  ['Vulnerability scan', 'Penetration testing', 'System/process audit', 'Static analysis'], 1,
  'Penetration testing proves EXPLOITABILITY and impact. A vulnerability scan reports possibilities without confirming that any of them can be chained into real access.'),
q('4.3', 'A structured review checks whether documented security processes are actually being followed and controls are operating. Which method is this?',
  ['Penetration testing', 'System/process audit', 'Vulnerability scan', 'Attestation'], 1,
  'A system/process audit examines PROCESS compliance rather than technical weakness — it can find a well-patched estate with no change control, which a scanner never would.'),
q('4.3', 'A scanner fails to report a vulnerability that is genuinely present on the host. What is this?',
  ['False positive', 'False negative', 'Exception', 'Exposure factor'], 1,
  'A false negative is silence where there should have been an alert, and it is the more dangerous of the two because nobody knows to look.'),
q('4.3', 'A vulnerability is grouped as "remote code execution" rather than "information disclosure" so it can be prioritised by kind. Which analysis activity is this?',
  ['Vulnerability classification', 'Prioritize', 'Exposure factor', 'Environmental variables'], 0,
  'Vulnerability classification sorts findings by TYPE. Prioritisation then orders them by urgency, using classification alongside CVSS and business context.'),
q('4.3', 'When scoring a vulnerability, the proportion of the asset\'s value that would be lost if it were exploited is called what?',
  ['Environmental variables', 'Exposure factor', 'Risk tolerance', 'Impact'], 1,
  'Exposure factor appears in both 4.3 and 5.2 with the same meaning — the proportion of value lost per event. It is the multiplier in the SLE formula.'),
q('4.3', 'A vulnerability with a high base score is downgraded because the affected service is not reachable from the internet in this deployment. Which analysis factor is this?',
  ['Exposure factor', 'Environmental variables', 'Risk tolerance', 'Vulnerability classification'], 1,
  'Environmental variables adjust a generic score for YOUR deployment. They are why an identical CVE can be critical in one organisation and negligible in another.'),
q('4.3', 'A regulator treats an unpatched flaw in a medical device as far more serious than the same flaw in a marketing website. Which analysis factor is this?',
  ['Industry/organizational impact', 'Environmental variables', 'Exposure factor', 'Risk tolerance'], 0,
  'Industry/organizational impact recognises that the same technical flaw carries different consequences by sector. It is the bridge between a CVSS score and a business decision.'),
q('4.3', 'An organisation accepts vulnerabilities scoring below 4.0 without remediation, based on its stated position on risk. Which analysis factor is this?',
  ['Risk tolerance', 'Exposure factor', 'Prioritize', 'Exceptions and exemptions'], 0,
  'Risk tolerance appears in 4.3 and 5.2. It is the acceptable variance that sets the threshold below which no action is taken.'),
q('4.3', 'Rather than patch a vulnerable legacy system, an organisation buys a policy to cover the financial loss if it is exploited. Which vulnerability response is this?',
  ['Compensating controls', 'Insurance', 'Exceptions and exemptions', 'Segmentation'], 1,
  'Insurance is named as a vulnerability response in 4.3 and matches the 5.2 strategy "transfer". It moves the financial loss without reducing the technical likelihood at all.'),
q('4.3', 'The security team formally documents and communicates open vulnerabilities, remediation progress and residual risk to management. Which 4.3 activity is this?',
  ['Validation of remediation', 'Reporting', 'Analysis', 'Attestation'], 1,
  'Reporting is the final named activity of the vulnerability management cycle. Without it the programme cannot demonstrate progress or justify its resources.'),
q('4.3', 'After remediation, an independent party reviews evidence to confirm the fix was applied as claimed. Which validation activity is this?',
  ['Rescanning', 'Audit', 'Verification', 'Reporting'], 1,
  'Audit is the INDEPENDENT check by someone other than the team that did the work. Rescanning is the automated re-test and verification is the general confirmation.'),

/* 4.4 */
q('4.4', 'A benchmark comparing a host\'s settings to a published CIS standard is applied. Which 4.4 tool category does the benchmark belong to?',
  ['SCAP', 'Benchmarks', 'Agents/agentless', 'Vulnerability scanners'], 1,
  'A benchmark is the CONTENT — the specific hardening standard. SCAP is the machine-readable FORMAT that lets different tools consume the same benchmark.'),
q('4.4', 'A monitoring approach installs software on each host to report telemetry, rather than polling hosts over the network. Which 4.4 tool consideration is this?',
  ['Agents/agentless', 'Benchmarks', 'SCAP', 'SNMP traps'], 0,
  'The objectives phrase the choice as "agents/agentless". Agents give deeper visibility and offline collection; agentless avoids deployment overhead and unsupported platforms.'),
q('4.4', 'Software on each endpoint detects and quarantines known malicious files by signature and heuristics. Which 4.4 tool is this?',
  ['Data loss prevention (DLP)', 'Antivirus', 'SIEM', 'Vulnerability scanners'], 1,
  'Antivirus is named as its own 4.4 tool. EDR (4.5) is the more capable successor that adds behavioural detection and response rather than file matching alone.'),
q('4.4', 'A tool inspects outbound email and file transfers for content matching sensitive data patterns and blocks it. Which 4.4 tool is this?',
  ['Antivirus', 'Data loss prevention (DLP)', 'NetFlow', 'SIEM'], 1,
  'DLP is listed both as a 4.4 monitoring tool and a 4.5 enterprise capability. It is defined by acting on the CONTENT of the data rather than on its source or destination.'),
q('4.4', 'A tool authenticates to hosts and reports which are missing patches and which have insecure settings. Which 4.4 tool is this?',
  ['SIEM', 'Vulnerability scanners', 'Antivirus', 'NetFlow'], 1,
  'Vulnerability scanners appear both here as a monitoring tool and in 4.3 as an identification method — the same tool serving continuous monitoring and point-in-time assessment.'),
q('4.4', 'A suspected malicious file is automatically moved to an isolated location where it cannot execute, pending analysis. Which alert response is this?',
  ['Alert tuning', 'Quarantine', 'Archiving', 'Isolation'], 1,
  'Quarantine acts on the FILE or host. Alert tuning changes the RULE — both appear under alert response and remediation, and the object being acted on is the discriminator.'),

/* 4.5 */
q('4.5', 'A firewall is configured with an ordered list of permit and deny statements evaluated top to bottom. What does the objectives document call these?',
  ['Access lists', 'Rules', 'Block rules', 'Screened subnets'], 1,
  'Rules is the general 4.5 firewall term for the ordered logic. Access lists is listed alongside it as the specific construct on routers and switches.'),
q('4.5', 'A router is configured with a named ACL permitting only certain source networks toward a management subnet. Which firewall element is this?',
  ['Rules', 'Access lists', 'Ports/protocols', 'Screened subnets'], 1,
  'Access lists is the objectives\' term for ACL-based filtering, listed separately from rules because the construct and its behaviour differ from a stateful firewall policy.'),
q('4.5', 'Permitting TCP 443 inbound while denying TCP 23 is a decision about which firewall element?',
  ['Rules', 'Ports/protocols', 'Access lists', 'Screened subnets'], 1,
  'Ports/protocols is the named element describing what traffic is identified by. It links directly to 4.5\'s "implementation of secure protocols" — choose 443 over 80, 22 over 23.'),
q('4.5', 'Public-facing servers are placed in a network segment separated from both the internet and the internal LAN by firewalls. What does the objectives document call it?',
  ['Security zone', 'Screened subnets', 'Air gap', 'Logical segmentation'], 1,
  'Screened subnet is the objectives\' replacement for the older term DMZ. It is a specific instance of the more general 3.2 concept of a security zone.'),
q('4.5', 'An IDS raises an alert because traffic volume to a host deviates sharply from its established baseline. Which detection method is this?',
  ['Signatures', 'Trends', 'Reputation', 'Content categorization'], 1,
  'Trends is the objectives\' term for anomaly-based detection. It can catch novel attacks that signatures cannot, at the cost of more false positives.'),
q('4.5', 'Web filtering is enforced by software installed on each laptop so that policy applies wherever the device connects. Which approach is this?',
  ['Centralized proxy', 'Agent-based', 'DNS filtering', 'Universal Resource Locator (URL) scanning'], 1,
  'Agent-based filtering travels WITH the device, which is what makes it work for remote staff. A centralized proxy only filters traffic that reaches it.'),
q('4.5', 'All web traffic is routed through a single on-premises appliance that inspects and filters it. Which web filter approach is this?',
  ['Agent-based', 'Centralized proxy', 'Reputation', 'Block rules'], 1,
  'A centralized proxy is a single chokepoint — easy to manage and to bypass by simply not being on the network, which is why agent-based deployment exists.'),
q('4.5', 'A web filter examines the full address of each requested page, including its path, against a threat database. Which feature is this?',
  ['Content categorization', 'Universal Resource Locator (URL) scanning', 'Reputation', 'Block rules'], 1,
  'URL scanning inspects the specific address requested. Reputation scores the whole site by history, and categorization sorts it by topic — three different bases for the same block.'),
q('4.5', 'A web filter blocks a site because it is classified as gambling, a category the policy forbids. Which feature is this?',
  ['Reputation', 'Content categorization', 'URL scanning', 'Block rules'], 1,
  'Content categorization sorts sites by TOPIC. Reputation scores them by security HISTORY — a reputable gambling site would pass reputation and fail categorization.'),
q('4.5', 'An administrator adds a specific domain to a list that the web filter must always deny regardless of category. Which feature is this?',
  ['Content categorization', 'Block rules', 'Reputation', 'Access lists'], 1,
  'Block rules are explicit administrator-defined denials that override the automated classification mechanisms — the manual layer on top of categorization and reputation.'),
q('4.5', 'Mandatory access control is enforced on a Linux server through kernel-level policy labels on processes and files. Which mechanism is this?',
  ['Group Policy', 'SELinux', 'Configuration enforcement', 'Host-based firewall'], 1,
  'SELinux is the objectives\' named Linux operating system security mechanism, paired with Group Policy for Windows. It implements the mandatory access control model from 4.6.'),
q('4.5', 'An organisation decides to use SSH rather than Telnet for device administration. Which element of implementing secure protocols is this?',
  ['Port selection', 'Protocol selection', 'Transport method', 'Ports/protocols'], 1,
  'Protocol selection is choosing the secure protocol itself. Port selection is then choosing which port it listens on — the objectives list the two as separate decisions.'),
q('4.5', 'After choosing HTTPS, a team decides the service will listen on 8443 rather than 443 for an internal application. Which element is this?',
  ['Protocol selection', 'Port selection', 'Transport method', 'Access lists'], 1,
  'Port selection is the second decision after the protocol is chosen. Changing the port is not a security control in itself — it is obscurity, not protection.'),
q('4.5', 'Deciding whether traffic will be carried over TCP or UDP, and whether it will be tunnelled, is which element of implementing secure protocols?',
  ['Protocol selection', 'Port selection', 'Transport method', 'Tunneling'], 2,
  'Transport method is the third of the three named decisions. Syslog over UDP 514 versus TLS-wrapped TCP 6514 is exactly this choice.'),
q('4.5', 'A sending mail server attaches a cryptographic signature to each outgoing message, which recipients verify using a published DNS key. Which mechanism is this?',
  ['Sender Policy Framework (SPF)', 'DomainKeys Identified Mail (DKIM)', 'DMARC', 'Gateway'], 1,
  'DKIM signs the MESSAGE, which survives forwarding. SPF authorises the SENDING SERVER by address, which does not survive forwarding — that is why both exist.'),
q('4.5', 'An appliance sits in front of the mail servers scanning inbound messages for spam, malware and phishing before delivery. Which email security element is this?',
  ['DMARC', 'Gateway', 'DKIM', 'Web filter'], 1,
  'The objectives list Gateway as an email security element alongside the three authentication mechanisms. It is the inspection point; SPF, DKIM and DMARC are the verification standards it applies.'),
q('4.5', 'A platform records process, file and network activity on every endpoint, detects malicious behaviour and can isolate the host remotely. Which capability is this?',
  ['Antivirus', 'Endpoint detection and response (EDR)/extended detection and response (XDR)', 'File integrity monitoring', 'Network access control'], 1,
  'EDR records and responds on the endpoint; XDR extends the same correlation across network, email and cloud. Antivirus matches known files and cannot isolate a host.'),

/* 4.6 */
q('4.6', 'A review finds a user has accumulated rights from four previous roles they no longer perform. Which 4.6 concept does this illustrate?',
  ['Identity proofing', 'Permission assignments and implications', 'Attestation', 'Federation'], 1,
  'Permission assignments and implications covers how rights are granted and what they accumulate into. The condition in the stem is privilege creep, which regular attestation is designed to catch.'),
q('4.6', 'Two organisations must ensure their identity systems can exchange assertions despite using different products. Which 4.6 concept is this?',
  ['Federation', 'Interoperability', 'Attestation', 'Single sign-on'], 1,
  'Interoperability is the ability of different systems to work together, usually through shared standards like SAML and OIDC. Federation is the trust relationship those standards carry.'),
q('4.6', 'Which protocol is used to query and modify a directory of users, groups and organisational units?',
  ['Security Assertions Markup Language (SAML)', 'Lightweight Directory Access Protocol (LDAP)', 'Open authorization (OAuth)', 'RADIUS'], 1,
  'LDAP is the directory access protocol underneath many SSO implementations. SAML and OAuth carry assertions and grants between services; LDAP reads and writes the directory itself.'),
q('4.6', 'An XML-based standard passes an authentication assertion from an identity provider to a service provider. Which standard is this?',
  ['Open authorization (OAuth)', 'Security Assertions Markup Language (SAML)', 'Lightweight Directory Access Protocol (LDAP)', 'Kerberos'], 1,
  'SAML carries authentication assertions and is XML-based. OAuth grants delegated authorization and is token-based — the word inside each acronym gives the answer.'),
q('4.6', 'The owner of a shared folder can grant any colleague access to it at their own discretion. Which access control model is this?',
  ['Mandatory', 'Discretionary', 'Role-based', 'Rule-based'], 1,
  'Discretionary means the DATA OWNER decides and can delegate. Mandatory means the system decides by label and no owner can override — who holds the decision is the discriminator.'),
q('4.6', 'A firewall grants access based on a condition evaluated at request time — any request from this subnet during business hours is permitted. Which model is this?',
  ['Role-based', 'Rule-based', 'Attribute-based', 'Discretionary'], 1,
  'Rule-based applies a condition regardless of WHO the requester is. Role-based decides by the person\'s job function — identity-independent versus identity-driven is the test.'),
q('4.6', 'Contractors may sign in only between 08:00 and 18:00 on weekdays. Which access control does the objectives document name?',
  ['Rule-based', 'Time-of-day restrictions', 'Attribute-based', 'Least privilege'], 1,
  'Time-of-day restrictions is named explicitly in the 4.6 access controls list. It is a specific control rather than an abstract model, which is why it sits alongside the five models.'),
q('4.6', 'A database administrator is given rights to administer databases but not to read the application data those databases hold. Which principle is this?',
  ['Attribute-based access control', 'Least privilege', 'Discretionary access control', 'Time-of-day restrictions'], 1,
  'Least privilege grants only what the role requires and nothing more. It appears in 2.5 as a mitigation and in 4.6 as an access control — the same principle in two objectives.'),
q('4.6', 'A user authenticates with a fingerprint reader on their laptop. Which MFA implementation is this?',
  ['Hard/soft authentication tokens', 'Biometrics', 'Security keys', 'Something you have'], 1,
  'Biometrics is the IMPLEMENTATION; "something you are" is the FACTOR it satisfies. The objectives list implementations and factors as two separate sub-lists.'),
q('4.6', 'An application on a user\'s phone generates a six-digit code that changes every thirty seconds. Which MFA implementation is this?',
  ['Biometrics', 'Hard/soft authentication tokens', 'Security keys', 'Password managers'], 1,
  'A soft token is software-based; a hard token is a dedicated physical device. The objectives pair them in a single bullet because they differ only in their form factor.'),
q('4.6', 'A user inserts a USB device that performs cryptographic authentication with the site and resists phishing. Which MFA implementation is this?',
  ['Hard/soft authentication tokens', 'Security keys', 'Biometrics', 'Passwordless'], 1,
  'Security keys are named separately from tokens because they bind the authentication to the site\'s origin, which is what makes them phishing-resistant where a typed code is not.'),
q('4.6', 'A retina scan satisfies which authentication factor?',
  ['Something you know', 'Something you have', 'Something you are', 'Somewhere you are'], 2,
  'Something you are is the biometric factor — a property of the body. Something you have is a physical object you carry, which a body part is not treated as.'),
q('4.6', 'A system requires that an administrative login originate from inside the corporate network. Which authentication factor is this?',
  ['Something you have', 'Somewhere you are', 'Something you know', 'Something you are'], 1,
  'Somewhere you are is the location factor, the fourth on the objectives list and the one most often forgotten. It is inferred from IP address, GPS or network position.'),
q('4.6', 'A policy requires passwords of at least 14 characters. Which password best practice is this?',
  ['Complexity', 'Length', 'Age', 'Reuse'], 1,
  'Length is the character count. Complexity is the requirement to mix character classes. Modern guidance favours length over complexity, but the objectives list both.'),
q('4.6', 'A policy requires passwords to contain upper case, lower case, digits and symbols. Which password best practice is this?',
  ['Length', 'Complexity', 'Expiration', 'Age'], 1,
  'Complexity governs the character classes required. It is distinct from length, and the two together determine the size of the search space an attacker must cover.'),
q('4.6', 'A system refuses a new password if it matches any of the user\'s previous twelve. Which password best practice is this?',
  ['Expiration', 'Reuse', 'Age', 'Complexity'], 1,
  'Reuse governs whether old passwords may return, enforced through password history. Expiration is the separate rule forcing a change after a period.'),
q('4.6', 'A policy forces every user to change their password every 90 days. Which password best practice is this?',
  ['Age', 'Expiration', 'Reuse', 'Length'], 1,
  'Expiration is the maximum lifetime before a forced change. Minimum age is the different rule stopping a user from cycling straight back to a favourite password.'),
q('4.6', 'A system prevents a user from changing their password again within 24 hours of the last change. Which password best practice is this?',
  ['Expiration', 'Age', 'Reuse', 'Complexity'], 1,
  'Minimum age stops a user cycling rapidly through the history to return to their original password. It exists specifically to make the reuse rule effective.'),
q('4.6', 'An application generates, stores and fills unique strong credentials for every site a user visits. What is this tool?',
  ['Password vaulting', 'Password managers', 'Privileged access management', 'Passwordless'], 1,
  'Password managers serve END USERS across many sites. Password vaulting is the PAM function for shared privileged accounts, with checkout and rotation — different users, different purpose.'),
q('4.6', 'Users sign in using a device-bound cryptographic credential and a biometric, with no password stored anywhere. Which concept is this?',
  ['Multifactor authentication', 'Passwordless', 'Federation', 'Single sign-on'], 1,
  'Passwordless removes the shared secret entirely, so there is nothing to phish, spray or reuse. It is listed as its own password concept in 4.6.'),
q('4.6', 'A pipeline receives a database credential valid for five minutes and unusable afterwards. Which PAM tool is this?',
  ['Password vaulting', 'Ephemeral credentials', 'Just-in-time permissions', 'Passwordless'], 1,
  'Ephemeral credentials are secrets that EXPIRE after brief use. Just-in-time governs when a PERMISSION exists; vaulting governs custody of a long-lived shared secret.'),

/* 4.7 */
q('4.7', 'A pipeline automatically creates virtual machines, storage and network configuration for a new environment. Which use case is this?',
  ['User provisioning', 'Resource provisioning', 'Guard rails', 'Standard infrastructure configurations'], 1,
  'Resource provisioning creates INFRASTRUCTURE. User provisioning creates ACCOUNTS — the objectives list both and the object being created decides the answer.'),
q('4.7', 'Automation adds and removes users from access groups as their HR record changes. Which 4.7 use case does the objectives document name?',
  ['User provisioning', 'Security groups', 'Guard rails', 'Escalation'], 1,
  'Security groups is named as its own automation use case — the ongoing management of group membership, distinct from creating the account in the first place.'),
q('4.7', 'When an alert fires, an automated workflow raises a case in the service desk system with the relevant context attached. Which use case is this?',
  ['Escalation', 'Ticket creation', 'Alerting', 'Reporting'], 1,
  'Ticket creation opens the record. Escalation is the separate step of routing it upward when criteria are met — both are named 4.7 use cases.'),
q('4.7', 'If a critical alert is not acknowledged within fifteen minutes, automation notifies the on-call manager. Which use case is this?',
  ['Ticket creation', 'Escalation', 'Alerting', 'Reaction time'], 1,
  'Escalation moves an issue UP when a condition is met. Ticket creation merely records it — the time-based routing in the stem is what makes this escalation.'),
q('4.7', 'On an employee\'s last day, automation disables their accounts and revokes VPN access at a scheduled time. Which use case does the objectives document name?',
  ['User provisioning', 'Enabling/disabling services and access', 'Security groups', 'Guard rails'], 1,
  'Enabling/disabling services and access is a named use case covering activation and revocation. It is what makes same-day de-provisioning reliable rather than dependent on someone remembering.'),
q('4.7', 'Every code commit automatically triggers a build, a test suite and a security scan before merge is permitted. Which use case is this?',
  ['Continuous integration and testing', 'Guard rails', 'Enforcing baselines', 'Integrations and APIs'], 0,
  'Continuous integration and testing is the named use case. Guard rails would be the constraints that block an unsafe result — CI is the pipeline, guard rails are its limits.'),
q('4.7', 'A SOAR platform connects to the firewall, the EDR and the ticketing system programmatically to execute a response. Which use case is this?',
  ['Continuous integration and testing', 'Integrations and Application programming interfaces (APIs)', 'Guard rails', 'Resource provisioning'], 1,
  'Integrations and APIs are what make orchestration possible — automation is only as capable as the interfaces the surrounding tools expose.'),
q('4.7', 'Automating a task that took an analyst twenty minutes so it now completes in seconds illustrates which benefit?',
  ['Workforce multiplier', 'Efficiency/time saving', 'Reaction time', 'Employee retention'], 1,
  'Efficiency/time saving is about the CLOCK on a task. Workforce multiplier is about total headcount capacity — the stem measures one task\'s duration.'),
q('4.7', 'Automation reapplies the approved configuration whenever a server drifts from it. Which 4.7 benefit does the objectives document name?',
  ['Standard infrastructure configurations', 'Enforcing baselines', 'Guard rails', 'Scaling in a secure manner'], 1,
  'Enforcing baselines keeps systems AT the approved state over time. Standard infrastructure configurations is the related benefit of every system starting from the same definition.'),
q('4.7', 'Because every environment is built from the same templates, a control proven in one applies identically in all. Which benefit is this?',
  ['Enforcing baselines', 'Standard infrastructure configurations', 'Efficiency/time saving', 'Workforce multiplier'], 1,
  'Standard infrastructure configurations is about UNIFORMITY at build time. Enforcing baselines is about maintaining that state afterwards — build versus drift.'),
q('4.7', 'An environment grows from ten to four hundred servers without weakening its controls, because provisioning applies them automatically. Which benefit is this?',
  ['Scaling in a secure manner', 'Efficiency/time saving', 'Enforcing baselines', 'Reaction time'], 0,
  'Scaling in a secure manner is the named benefit that security keeps pace with growth. Manual processes are exactly what breaks at this point.'),
q('4.7', 'Automating repetitive alert triage means analysts spend their time on investigation instead. Which benefit does the objectives document name?',
  ['Workforce multiplier', 'Employee retention', 'Efficiency/time saving', 'Reaction time'], 1,
  'Employee retention is a named benefit of automation — removing tedious work reduces burnout. It is easy to omit when reproducing the list because it is not a technical outcome.'),
q('4.7', 'An automated playbook contains a compromised host within seconds of detection rather than the twenty minutes an analyst would take. Which benefit is this?',
  ['Efficiency/time saving', 'Reaction time', 'Workforce multiplier', 'Scaling in a secure manner'], 1,
  'Reaction time is specifically about SPEED OF RESPONSE to an event, where minutes change the outcome. Efficiency is about routine task duration generally.'),
q('4.7', 'A team worries that only one engineer understands the automation platform, and they are leaving. Which 4.7 consideration is this?',
  ['Technical debt', 'Ongoing supportability', 'Single point of failure', 'Complexity'], 1,
  'Ongoing supportability asks whether the organisation can maintain what it built. A single point of failure is about the SYSTEM; supportability is about the people and skills behind it.'),

/* 4.8 */
q('4.8', 'The incident response team discusses their handling of a hypothetical breach around a conference table. Which 4.8 test type is this?',
  ['Simulation', 'Tabletop exercise', 'Training', 'Root cause analysis'], 1,
  'The objectives list tabletop exercise and simulation as the two IR test types. Tabletop is discussion only; simulation exercises the systems or the people for real.'),
q('4.8', 'A realistic phishing scenario is injected and staff carry out their genuine response procedures end to end. Which 4.8 test type is this?',
  ['Tabletop exercise', 'Simulation', 'Training', 'Testing'], 1,
  'Simulation puts real procedures into motion. It reveals gaps a tabletop cannot — a plan can read perfectly and still fail when a tool is unreachable.'),
q('4.8', 'Responders are taught how to use the forensic toolkit and follow the escalation path before any incident occurs. Which 4.8 activity is this?',
  ['Testing', 'Training', 'Preparation', 'Lessons learned'], 1,
  'Training is named as its own 4.8 activity and builds the capability; testing then verifies it. Both sit inside the preparation phase of the process.'),
q('4.8', 'An investigator creates a bit-for-bit forensic image of a suspect drive using a write blocker. Which digital forensics activity is this?',
  ['Preservation', 'Acquisition', 'Chain of custody', 'E-discovery'], 1,
  'Acquisition is TAKING the forensic copy. Preservation is keeping the original and the copy unaltered afterwards — the objectives list both.'),
q('4.8', 'An investigator documents findings, methods and conclusions in a form suitable for legal proceedings. Which forensics activity is this?',
  ['E-discovery', 'Reporting', 'Acquisition', 'Attestation'], 1,
  'Reporting in a forensic context must record method and reasoning so a third party could reproduce it. Reporting also appears in 4.3 and 4.4 with different meanings.'),
q('4.8', 'Original evidence is stored in a sealed, access-controlled location with environmental protection so it is not altered. Which activity is this?',
  ['Acquisition', 'Preservation', 'Legal hold', 'Chain of custody'], 1,
  'Preservation is the technical and physical act of keeping evidence intact. The legal hold is the instruction that requires it; preservation is the compliance with that instruction.'),
q('4.8', 'A legal team requests all electronically stored information relevant to a dispute be identified and produced. Which activity is this?',
  ['Legal hold', 'E-discovery', 'Preservation', 'Reporting'], 1,
  'E-discovery is the identification, collection and PRODUCTION of electronic evidence for proceedings. The legal hold precedes it by stopping deletion.'),

/* 4.9 */
q('4.9', 'An analyst needs to confirm whether a connection to a suspicious external address was permitted or dropped at the perimeter. Which log source is this?',
  ['Application logs', 'Firewall logs', 'Endpoint logs', 'Metadata'], 1,
  'Firewall logs record allow and deny decisions at the boundary. They prove whether traffic was permitted; only a packet capture would show what it contained.'),
q('4.9', 'An analyst needs to know which records a user viewed inside a business system. Which log source is this?',
  ['OS-specific security logs', 'Application logs', 'Network logs', 'Firewall logs'], 1,
  'Application logs record what the application itself did, including business-level actions. The OS security log would show the logon but not which record was opened.'),
q('4.9', 'An analyst needs to see which processes a security agent observed spawning on a workstation. Which log source is this?',
  ['OS-specific security logs', 'Endpoint logs', 'Application logs', 'IPS/IDS logs'], 1,
  'Endpoint logs are what the security AGENT produced. OS-specific security logs are the operating system\'s own audit trail — the objectives list them separately.'),
q('4.9', 'An analyst needs to know which detection signature triggered on inbound traffic and what action was taken. Which log source is this?',
  ['Firewall logs', 'IPS/IDS logs', 'Network logs', 'Endpoint logs'], 1,
  'IPS/IDS logs record which rule matched and whether it alerted or blocked. Firewall logs record policy decisions but carry no detection signature context.'),
q('4.9', 'An analyst needs to establish which internal hosts communicated with each other and for how long. Which log source is this?',
  ['Packet captures', 'Network logs', 'Application logs', 'Metadata'], 1,
  'Network logs establish that conversations happened and their duration. Only a packet capture proves what was said, and captures are rarely retained at that scale.'),
q('4.9', 'An investigator needs to know which hosts were vulnerable to the exploited flaw at the time of the incident. Which data source is this?',
  ['Dashboards', 'Vulnerability scans', 'Automated reports', 'Network logs'], 1,
  'Historical vulnerability scan data establishes the exposure at a point in time — it answers whether the attacker could have used this path, and how far it extended.'),
q('4.9', 'A scheduled job compiles patch compliance figures each Monday and emails them to system owners. Which data source is this?',
  ['Dashboards', 'Automated reports', 'Vulnerability scans', 'Metadata'], 1,
  'Automated reports are generated and DELIVERED on a schedule. Dashboards are a live view you go and look at — push versus pull is the discriminator.'),
];
