// Coverage bank — Domain 5.

const q = (objective, stem, options, answer, explanation) =>
  ({ objective, stem, options, answer, explanation });

export default [

/* 5.1 */
q('5.1', 'Governance documents are reviewed annually and updated when regulation or the business changes. Which 5.1 element is this?',
  ['Guidelines', 'Monitoring and revision', 'Procedures', 'Compliance monitoring'], 1,
  'Monitoring and revision is the named 5.1 element keeping governance current. A policy nobody has revisited in five years fails this whether or not it was once correct.'),
q('5.1', 'A document sets out the organisation\'s overall commitments and responsibilities for protecting information. Which policy is this?',
  ['Acceptable use policy (AUP)', 'Information security policies', 'Business continuity', 'Change management'], 1,
  'Information security policies are the overarching mandate. The AUP is narrower and governs what PEOPLE may do with systems.'),
q('5.1', 'A policy defines how essential business functions will continue during a prolonged disruption. Which policy is this?',
  ['Disaster recovery', 'Business continuity', 'Incident response', 'Continuity of operations'], 1,
  'Business continuity keeps the BUSINESS FUNCTION running, including manual workarounds. Disaster recovery is the narrower technical restoration of systems and data.'),
q('5.1', 'A policy defines how systems and data will be restored at an alternate site after a major outage. Which policy is this?',
  ['Business continuity', 'Disaster recovery', 'Incident response', 'Change management'], 1,
  'Disaster recovery is the TECHNICAL restoration of infrastructure. Business continuity is the broader question of how the business keeps operating meanwhile.'),
q('5.1', 'A policy defines how the organisation detects, contains and recovers from security events, and who has authority to act. Which policy is this?',
  ['Disaster recovery', 'Incident response', 'Business continuity', 'Acceptable use policy'], 1,
  'The incident response policy grants authority and sets the framework. The 4.8 process and the playbooks in 5.1 procedures are what implement it.'),
q('5.1', 'A policy requires threat modelling, code review and security testing at defined stages of application development. Which policy is this?',
  ['Change management', 'Software development lifecycle (SDLC)', 'Information security policies', 'Incident response'], 1,
  'The SDLC policy embeds security into how software is built. It is where the 4.1 application security controls — input validation, static analysis, code signing — are mandated.'),
q('5.1', 'A policy requires that every production change be assessed, approved and documented before implementation. Which policy is this?',
  ['Software development lifecycle (SDLC)', 'Change management', 'Acceptable use policy', 'Incident response'], 1,
  'Change management appears in 5.1 twice — once as a policy and once as a procedure. The policy states the requirement; the procedure gives the steps.'),
q('5.1', 'A step-by-step document describes exactly how to submit, assess and approve a change request. Which 5.1 element is this?',
  ['Change management policy', 'Change management procedure', 'Playbooks', 'Standards'], 1,
  'The objectives list change management under both Policies and Procedures. The policy says it must happen; the procedure says how — this pairing is deliberate.'),
q('5.1', 'A documented sequence covers account creation, equipment issue and training for a new joiner, and their reversal for a leaver. Which procedure is this?',
  ['Playbooks', 'Onboarding/offboarding', 'Change management', 'Standard operating procedure'], 1,
  'Onboarding/offboarding is the named 5.1 procedure. Its offboarding half is what prevents the dismissed-administrator scenario, linking directly to 4.6 de-provisioning.'),
q('5.1', 'The highest governing body of an organisation, with ultimate accountability for its risk posture, is which structure?',
  ['Committees', 'Boards', 'Government entities', 'Audit committee'], 1,
  'The board is the top governing body. A committee is convened by it for a purpose — the audit committee in 5.5 is an example of exactly that relationship.'),
q('5.1', 'A regulator or public authority that imposes security requirements on an industry is which governance structure?',
  ['Boards', 'Government entities', 'Committees', 'External considerations'], 1,
  'Government entities are named as a governance structure because they govern from OUTSIDE the organisation, unlike boards and committees which sit within it.'),
q('5.1', 'An organisation must decide whether one team sets security policy for all divisions or each division sets its own. Which governance structure question is this?',
  ['Boards', 'Committees', 'Centralized/decentralized', 'Government entities'], 2,
  'Centralized/decentralized is listed as a governance structure. It mirrors the same trade-off that appears in 3.1 as an architecture consideration: consistency against local autonomy.'),
q('5.1', 'Which role holds ultimate accountability for a specific system or dataset within the organisation?',
  ['Custodians/stewards', 'Owners', 'Processors', 'Controllers'], 1,
  'The owner is accountable and makes the decisions. Custodians and stewards provide day-to-day care but do not decide — accountability versus operation is the split.'),
q('5.1', 'A third-party payroll bureau handles employee data strictly according to its client\'s written instructions. Which role is this?',
  ['Controllers', 'Processors', 'Owners', 'Custodians/stewards'], 1,
  'The processor acts on instruction and does not decide the purpose. The controller decides why and how — that distinction determines where legal liability sits.'),
q('5.1', 'A database administration team maintains backups, applies patches and manages access on behalf of the business owner. Which role is this?',
  ['Owners', 'Custodians/stewards', 'Controllers', 'Processors'], 1,
  'Custodians and stewards provide day-to-day technical care under the owner\'s direction. They implement decisions rather than making them.'),

/* 5.2 */
q('5.2', 'A workshop is held to enumerate everything that could threaten a new service before any of it is scored. Which risk process element is this?',
  ['Risk assessment', 'Risk identification', 'Risk analysis', 'Risk register'], 1,
  'Identification is finding and naming the risks. Assessment and analysis then evaluate them — you cannot score what you have not first listed.'),
q('5.2', 'An organisation states it will accept up to 10% variance above its target risk level before intervening. Which concept is this?',
  ['Risk appetite', 'Risk tolerance', 'Risk threshold', 'Exposure factor'], 1,
  'Tolerance is the acceptable VARIANCE around the appetite. Appetite is the strategic level of risk deliberately sought — appetite sets the target, tolerance the band.'),
q('5.2', 'The security team produces a quarterly summary of the risk landscape and treatment progress for the board. Which risk process element is this?',
  ['Risk register', 'Risk reporting', 'Risk assessment', 'Compliance reporting'], 1,
  'Risk reporting communicates risk to decision-makers. The register is the underlying RECORD; the report is what is presented from it.'),
q('5.2', 'A risk assessment is performed because a major acquisition has just been announced, outside any schedule. Which cadence is this?',
  ['Recurring', 'Ad hoc', 'One-time', 'Continuous'], 1,
  'Ad hoc is triggered by an EVENT rather than a schedule. One-time is performed for a specific decision and not repeated — the trigger is what makes this ad hoc.'),
q('5.2', 'Risk assessments are scheduled every six months regardless of what has changed. Which cadence is this?',
  ['Ad hoc', 'Recurring', 'Continuous', 'One-time'], 1,
  'Recurring runs on a fixed SCHEDULE. Continuous runs constantly through automation; ad hoc runs when something triggers it.'),
q('5.2', 'A single risk assessment is commissioned to support a decision about entering a new market, and will not be repeated. Which cadence is this?',
  ['Recurring', 'One-time', 'Ad hoc', 'Continuous'], 1,
  'One-time is bounded to a specific decision with no intention to repeat. Ad hoc is also unscheduled but arises from an event rather than a defined purpose.'),
q('5.2', 'Risks are rated high, medium or low using expert judgement rather than monetary figures. Which analysis type is this?',
  ['Quantitative', 'Qualitative', 'Risk tolerance', 'Probability'], 1,
  'Qualitative uses relative judgement and descriptive scales. It is faster and works where reliable numbers do not exist, at the cost of comparability.'),
q('5.2', 'Risks are expressed in monetary terms using asset values, exposure factors and rates of occurrence. Which analysis type is this?',
  ['Qualitative', 'Quantitative', 'Likelihood', 'Impact'], 1,
  'Quantitative produces numbers you can compare with the cost of a control, which is what makes SLE, ALE and ARO worth calculating.'),
q('5.2', 'What does the term single loss expectancy represent?',
  ['The expected monetary loss from one occurrence of a risk event', 'The number of times per year the event occurs', 'The total annual expected loss', 'The proportion of the asset lost'], 0,
  'SLE is per EVENT and equals asset value x exposure factor. ALE is per YEAR and equals SLE x ARO — stopping at SLE is the most common calculation error.'),
q('5.2', 'What does the term annualized loss expectancy represent?',
  ['The loss from a single event', 'The expected total monetary loss per year from a risk', 'The number of occurrences per year', 'The organisation\'s risk appetite'], 1,
  'ALE = SLE x ARO and is the figure you compare against the annual cost of a control. If the control costs more than the ALE, the numbers do not justify it.'),
q('5.2', 'A flood is expected to affect a facility once every twenty years. What is the ARO?',
  ['20', '0.05', '5', '0.2'], 1,
  'ARO is occurrences per YEAR, so once in twenty years is 1/20 = 0.05. Entering 20 instead of 0.05 inflates the ALE by a factor of four hundred.'),
q('5.2', 'In qualitative risk analysis, the term describing how probable an event is judged to be, expressed descriptively, is:',
  ['Probability', 'Likelihood', 'Annualized rate of occurrence', 'Exposure factor'], 1,
  'The objectives list probability and likelihood separately. Probability is the mathematical value; likelihood is the descriptive judgement used in qualitative work.'),
q('5.2', 'A metric is defined that warns when a risk is trending toward its threshold, such as the count of overdue critical patches. What is this?',
  ['Risk threshold', 'Key risk indicators', 'Risk owners', 'Risk register'], 1,
  'Key risk indicators are leading measures that warn BEFORE the threshold is breached. The threshold is the line; the KRI is what tells you that you are approaching it.'),
q('5.2', 'Each entry in the risk register names the individual accountable for managing that risk. What is this person called?',
  ['Data owner', 'Risk owners', 'Custodian', 'Controller'], 1,
  'The risk owner is accountable for a specific RISK and its treatment. A data owner is accountable for a specific ASSET — related but distinct roles.'),
q('5.2', 'The level at which a risk must be escalated or treated rather than tolerated is called what?',
  ['Risk appetite', 'Risk threshold', 'Risk tolerance', 'Key risk indicator'], 1,
  'The threshold is the specific LINE recorded in the register that triggers action. Tolerance is the acceptable band; the threshold is where that band ends.'),
q('5.2', 'An organisation with a strongly risk-averse posture that prioritises stability over opportunity has which risk appetite?',
  ['Expansionary', 'Conservative', 'Neutral', 'Cautious'], 1,
  'The objectives give appetite exactly three values: expansionary, conservative and neutral. Any other adjective in an option is a distractor.'),
q('5.2', 'An organisation that balances risk and opportunity without leaning either way has which risk appetite?',
  ['Conservative', 'Neutral', 'Expansionary', 'Moderate'], 1,
  'Neutral is the middle of the three named values. "Moderate" is a plausible English word and is not on the list, which is precisely why it appears as a distractor.'),
q('5.2', 'A company purchases cyber insurance so that a third party bears the financial loss from a breach. Which risk strategy is this?',
  ['Accept', 'Transfer', 'Mitigate', 'Avoid'], 1,
  'Transfer moves the LOSS to another party through insurance or contract. It does not reduce the likelihood of the event — the breach can still happen.'),
q('5.2', 'A system is formally excused from a security standard permanently because it cannot technically comply. Which form of acceptance is this?',
  ['Exception', 'Exemption', 'Transfer', 'Mitigate'], 1,
  'The objectives nest exemption and exception beneath Accept. An exemption is a standing release from the requirement; an exception is a time-bound deviation.'),
q('5.2', 'A team is granted a six-month deviation from a patching standard while a replacement system is built. Which form of acceptance is this?',
  ['Exemption', 'Exception', 'Avoid', 'Transfer'], 1,
  'An exception is bounded and temporary, with an expiry. An exemption is a standing release — the fixed end date in the stem is the discriminator.'),
q('5.2', 'An organisation deploys MFA to reduce the likelihood of credential compromise. Which risk strategy is this?',
  ['Accept', 'Transfer', 'Mitigate', 'Avoid'], 2,
  'Mitigate REDUCES likelihood or impact while the activity continues. Avoid would mean stopping the activity; transfer would move the loss without reducing the risk.'),
q('5.2', 'A business impact analysis records that a failed server historically takes six hours to repair. Which metric is this?',
  ['Mean time between failures (MTBF)', 'Mean time to repair (MTTR)', 'Recovery time objective (RTO)', 'Recovery point objective (RPO)'], 1,
  'MTTR is an OBSERVED average of how long repair takes. RTO is a TARGET you set — one describes reality, the other states a requirement.'),
q('5.2', 'A component is expected to run for 40,000 hours before failing. Which metric is this?',
  ['Mean time to repair (MTTR)', 'Mean time between failures (MTBF)', 'Recovery time objective (RTO)', 'Annualized rate of occurrence'], 1,
  'MTBF measures reliability — how long it runs BETWEEN failures. MTTR measures how long the fix takes. Together they determine achievable availability.'),

/* 5.3 */
q('5.3', 'Before signing, a customer commissions an authorised test of a prospective vendor\'s externally facing systems. Which vendor assessment activity is this?',
  ['Independent assessments', 'Penetration testing', 'Right-to-audit clause', 'Supply chain analysis'], 1,
  'Penetration testing appears in 4.3, 5.3 and 5.5. Here it is a vendor ASSESSMENT method — testing someone else\'s environment before you rely on it.'),
q('5.3', 'A prospective vendor supplies the reports from its own internal audit function covering the last two years. Which vendor assessment element is this?',
  ['Independent assessments', 'Evidence of internal audits', 'Right-to-audit clause', 'Questionnaires'], 1,
  'Evidence of internal audits comes from the vendor\'s OWN audit function — useful but not independent, which is why the objectives list it separately.'),
q('5.3', 'A vendor provides a SOC 2 Type II report produced by an external audit firm. Which vendor assessment element is this?',
  ['Evidence of internal audits', 'Independent assessments', 'Right-to-audit clause', 'Vendor monitoring'], 1,
  'An independent assessment is performed by a THIRD PARTY, which is what gives it more weight than the vendor\'s own internal audit evidence.'),
q('5.3', 'An organisation maps its vendors\' own subcontractors to understand where a component actually originates. Which activity is this?',
  ['Due diligence', 'Supply chain analysis', 'Vendor monitoring', 'Questionnaires'], 1,
  'Supply chain analysis looks BEYOND the direct vendor to fourth parties and beyond. Due diligence investigates the direct vendor you are about to contract with.'),
q('5.3', 'A contract commits a provider to 99.9% uptime with service credits if it is not met. Which agreement type is this?',
  ['Master service agreement (MSA)', 'Service-level agreement (SLA)', 'Memorandum of understanding (MOU)', 'Business partners agreement (BPA)'], 1,
  'The SLA sets measurable PERFORMANCE commitments with consequences. The objectives list it first among the agreement types, and uptime is its signature content.'),
q('5.3', 'Two organisations sign a document setting out agreed responsibilities that is intended to be binding. Which agreement type is this?',
  ['Memorandum of understanding (MOU)', 'Memorandum of agreement (MOA)', 'Non-disclosure agreement (NDA)', 'Work order'], 1,
  'MOA sets out agreed RESPONSIBILITIES and is closer to binding. MOU expresses shared intent and generally is not — that is the whole distinction between the two.'),
q('5.3', 'A contract establishes standard commercial and legal terms that will govern all future engagements with a supplier. Which agreement type is this?',
  ['Statement of work', 'Master service agreement (MSA)', 'Service-level agreement (SLA)', 'Business partners agreement (BPA)'], 1,
  'The MSA is the umbrella covering many future jobs, negotiated once. Individual engagements are then issued as SOWs or work orders beneath it.'),
q('5.3', 'A document specifies the deliverables, milestones and acceptance criteria for one specific consulting engagement. Which agreement type is this?',
  ['Master service agreement (MSA)', 'Work order (WO)/statement of work (SOW)', 'Service-level agreement (SLA)', 'Rules of engagement'], 1,
  'The SOW or work order describes ONE engagement. The MSA is the standing framework — the stem\'s "one specific engagement" is the discriminator.'),
q('5.3', 'Before technical discussions begin, both parties sign a contract restricting disclosure of information shared. Which agreement type is this?',
  ['Business partners agreement (BPA)', 'Non-disclosure agreement (NDA)', 'Memorandum of understanding (MOU)', 'Master service agreement (MSA)'], 1,
  'The NDA governs CONFIDENTIALITY specifically. It is usually the first document signed because it must be in place before anything sensitive is discussed.'),
q('5.3', 'Two companies entering a joint venture sign a contract defining each party\'s contribution, share of profit and responsibilities. Which agreement type is this?',
  ['Master service agreement (MSA)', 'Business partners agreement (BPA)', 'Memorandum of agreement (MOA)', 'Service-level agreement (SLA)'], 1,
  'The BPA governs a PARTNERSHIP between businesses rather than a customer-supplier relationship — profit sharing in the stem is the tell.'),
q('5.3', 'After contract signature, a customer tracks a vendor\'s security posture, incidents and compliance status on an ongoing basis. Which activity is this?',
  ['Due diligence', 'Vendor monitoring', 'Questionnaires', 'Supply chain analysis'], 1,
  'Vendor monitoring is CONTINUOUS oversight after signing. Due diligence is the investigation BEFORE selection — the point in the relationship decides the word.'),

/* 5.4 */
q('5.4', 'A regulator imposes a monetary penalty for a data protection breach. Which consequence of non-compliance is this?',
  ['Sanctions', 'Fines', 'Contractual impacts', 'Loss of license'], 1,
  'Fines are direct monetary penalties. Sanctions are broader restrictions or punitive measures that may not involve money at all.'),
q('5.4', 'A government bars a company from bidding for public contracts following a serious compliance failure. Which consequence is this?',
  ['Fines', 'Sanctions', 'Reputational damage', 'Contractual impacts'], 1,
  'Sanctions are restrictions or punitive measures beyond a monetary fine. Being barred from a market is a sanction rather than a fine.'),
q('5.4', 'Media coverage of a breach causes customers to leave and the share price to fall. Which consequence is this?',
  ['Fines', 'Reputational damage', 'Sanctions', 'Loss of license'], 1,
  'Reputational damage is the indirect loss of trust and business. It is frequently the largest cost of a breach and the hardest to quantify.'),
q('5.4', 'A client terminates a contract early and claims damages after the supplier fails a required security standard. Which consequence is this?',
  ['Sanctions', 'Contractual impacts', 'Fines', 'Loss of license'], 1,
  'Contractual impacts flow from private agreements rather than regulators — penalties, termination or damages. PCI DSS consequences arrive this way rather than as government fines.'),
q('5.4', 'An organisation investigates its obligations thoroughly and then acts prudently on what it found. Which compliance monitoring element covers this pair?',
  ['Attestation and acknowledgement', 'Due diligence/care', 'Internal and external', 'Automation'], 1,
  'The objectives pair them in one bullet: diligence is the INVESTIGATING, care is the ACTING. Both are needed to rebut an allegation of negligence.'),
q('5.4', 'Compliance is monitored both by the organisation\'s own function and by an outside regulator or auditor. Which element does the objectives document name?',
  ['Compliance reporting', 'Internal and external', 'Attestation and acknowledgement', 'Automation'], 1,
  'Internal and external is a named element of compliance MONITORING. Compliance reporting has its own internal and external split — the objectives list both pairings.'),
q('5.4', 'Tooling continuously evaluates cloud configuration against a compliance standard and raises deviations without human effort. Which element is this?',
  ['Attestation', 'Automation', 'Due diligence/care', 'Compliance reporting'], 1,
  'Automation is named as a compliance monitoring element. It is what makes continuous compliance feasible at a scale periodic manual audits cannot cover.'),
q('5.4', 'Which privacy role decides the purposes for processing, as distinct from the party that merely carries out the processing?',
  ['Controller vs. processor', 'Data subject', 'Ownership', 'Custodian'], 0,
  'The objectives phrase this as the pairing "controller vs. processor". The controller decides purpose and means; the processor acts on instruction, and liability follows that split.'),
q('5.4', 'A dispute arises about whether a company or its cloud provider holds rights over derived analytics data. Which privacy consideration is this?',
  ['Data subject', 'Ownership', 'Right to be forgotten', 'Data inventory and retention'], 1,
  'Ownership determines who holds rights and obligations over data. It is separate from custody — a provider may hold the data without owning it.'),
q('5.4', 'An organisation catalogues every dataset it holds, where it lives and how long it must be kept. Which privacy element is this?',
  ['Right to be forgotten', 'Data inventory and retention', 'Ownership', 'Data subject'], 1,
  'Data inventory and retention is the named privacy element. Without an inventory you cannot honour an erasure request, because you cannot say where the data is.'),

/* 5.5 */
q('5.5', 'A formal signed statement declares that specified controls were in place and operating over a period. What is this?',
  ['Attestation', 'Assessment', 'Examination', 'Compliance report'], 0,
  'Attestation is a formal DECLARATION that something is true, made by a responsible party. An audit is the independent examination that may support it.'),
q('5.5', 'An internal team verifies that operations conform to the organisation\'s own policies and applicable regulations. Which internal audit function is this?',
  ['Self-assessments', 'Compliance', 'Audit committee', 'Attestation'], 1,
  'Compliance is named as an internal audit function in 5.5 — the standing function that checks conformity, distinct from a one-off self-assessment by the operating team.'),
q('5.5', 'A government body conducts a mandatory review of a bank\'s security controls under statutory powers. Which external audit type is this?',
  ['Independent third-party audit', 'Regulatory', 'Assessment', 'Examination'], 1,
  'Regulatory audits are conducted under legal authority and are not optional. An independent third-party audit is commissioned by the organisation itself.'),
q('5.5', 'A company engages an external audit firm to examine its controls and issue a report for its customers. Which audit type is this?',
  ['Regulatory', 'Independent third-party audit', 'Self-assessments', 'Compliance'], 1,
  'An independent third-party audit is commissioned BY the organisation from an outside firm. Its independence is what gives the resulting report value to customers.'),
q('5.5', 'A tester attempts to gain entry to a building by tailgating and testing door controls. Which penetration testing type is this?',
  ['Offensive', 'Physical', 'Integrated', 'Defensive'], 1,
  'Physical penetration testing targets buildings, locks and people rather than networks. It is listed as its own type alongside offensive, defensive and integrated.'),
q('5.5', 'A team simulates a real adversary, attempting to breach the organisation without the defenders knowing. Which penetration testing type is this?',
  ['Defensive', 'Offensive', 'Integrated', 'Physical'], 1,
  'Offensive is the attacking side — the red team. Defensive is the responding blue team, and integrated is the two working together with shared information.'),
q('5.5', 'A team focuses on detecting and responding to simulated attacks and improving its detection coverage. Which penetration testing type is this?',
  ['Offensive', 'Defensive', 'Integrated', 'Known environment'], 1,
  'Defensive is the blue team role. The objectives list offensive, defensive and integrated together because the exercise type determines what is actually being measured.'),
q('5.5', 'A tester is given no information whatsoever and must discover the environment from the outside. Which term describes this?',
  ['Known environment', 'Partially known environment', 'Unknown environment', 'Black box'], 2,
  'Unknown environment replaced the term black box in SY0-701. It most closely simulates an external attacker at the cost of spending budget on discovery.'),
q('5.5', 'A tester runs port scans and service fingerprinting directly against the target\'s address range. Which reconnaissance type is this?',
  ['Passive', 'Active', 'Unknown environment', 'Offensive'], 1,
  'Active reconnaissance sends traffic TO the target and can be detected. Passive uses only third-party and public sources — sending a single packet crosses the line.'),

/* 5.6 */
q('5.6', 'Training teaches staff to check sender addresses, hover over links and treat urgency as suspicious. Which 5.6 element is this?',
  ['Campaigns', 'Recognizing a phishing attempt', 'Responding to reported suspicious messages', 'Reporting and monitoring'], 1,
  'Recognising is the SKILL being built in the user. The campaign is the simulated test you run to measure whether the skill took hold.'),
q('5.6', 'A documented process governs how the security team triages, investigates and feeds back on user-reported emails. Which 5.6 element is this?',
  ['Campaigns', 'Recognizing a phishing attempt', 'Responding to reported suspicious messages', 'Anomalous behavior recognition'], 2,
  'This is the organisation\'s side of the loop. Without timely feedback users stop reporting, which is why the objectives name the response as well as the recognition.'),
q('5.6', 'A user who has never accessed HR systems suddenly begins browsing them, with no policy violation involved. Which category of anomalous behaviour is this?',
  ['Risky', 'Unexpected', 'Unintentional', 'Insider threat'], 1,
  'Unexpected is simply out of pattern for that user. Risky implies a knowing choice to bypass a control; unintentional implies a mistake.'),
q('5.6', 'An employee emails a spreadsheet to the wrong external recipient by mistake. Which category of anomalous behaviour is this?',
  ['Risky', 'Unexpected', 'Unintentional', 'Insider threat'], 2,
  'Unintentional is a genuine error with no intent. Risky would mean knowingly bypassing a control, and the appropriate response differs sharply between the two.'),
q('5.6', 'New joiners receive the staff handbook setting out their security obligations. Which 5.6 training topic is this?',
  ['Situational awareness', 'Policy/handbooks', 'Operational security', 'Insider threat'], 1,
  'Policy/handbooks is the named training topic covering the written rules staff are expected to follow. It is the documentary foundation the other topics build on.'),
q('5.6', 'Training teaches staff to notice and question an unfamiliar person following them through a secure door. Which topic is this?',
  ['Operational security', 'Situational awareness', 'Social engineering', 'Insider threat'], 1,
  'Situational awareness is noticing threats AROUND you. Operational security is not leaking your OWN information — the direction of the risk is the discriminator.'),
q('5.6', 'Staff are taught the warning signs of a colleague who may be preparing to steal data before leaving. Which training topic is this?',
  ['Situational awareness', 'Insider threat', 'Anomalous behavior recognition', 'Social engineering'], 1,
  'Insider threat is a named 5.6 training topic as well as a 2.1 threat actor. Here it is about equipping colleagues to recognise and report the indicators.'),
q('5.6', 'Training covers choosing unique passphrases and using the corporate password manager. Which training topic is this?',
  ['Policy/handbooks', 'Password management', 'Operational security', 'Social engineering'], 1,
  'Password management is a named 5.6 training topic. It is the user-facing counterpart of the 4.6 password concepts the systems enforce technically.'),
q('5.6', 'Training covers pretexting, impersonation and the manipulation techniques attackers use on people. Which topic is this?',
  ['Insider threat', 'Social engineering', 'Situational awareness', 'Phishing'], 1,
  'Social engineering is the broad named training topic covering human manipulation. Phishing is called out separately in 5.6 because of its volume.'),
q('5.6', 'Training covers securing home routers, avoiding public Wi-Fi for sensitive work and locking screens in shared spaces. Which topic is this?',
  ['Operational security', 'Hybrid/remote work environments', 'Situational awareness', 'Removable media and cables'], 1,
  'Hybrid/remote work environments is a named training topic added because the controls protecting an office do not follow the user home.'),
];
