// Build data/item-bank.json from the authored source files in tools/authored/.
//
// The source files carry a bare objective code ("2.4"); this expands it to the
// full label the app routes on, using objectives.md as the single source of
// those strings so a bank label can never drift from the objectives document.
//
// Everything here is a refusal to write a broken bank rather than a transform:
// the validations below have each caught a real authoring mistake.
//
//   node tools/build-bank.mjs

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const OBJECTIVES = path.join(ROOT, 'content', 'objectives.md');
// Two banks, same schema and same validation, built by the same script.
// The coverage bank is kept separate so the term-by-term audit that produced
// it stays auditable and the whole set stays deletable in one step.
const COVERAGE = process.argv.includes('--coverage');
const SRC = path.join(ROOT, 'tools', COVERAGE ? 'authored-coverage' : 'authored');
const OUT = path.join(ROOT, 'data', COVERAGE ? 'item-bank-coverage.json' : 'item-bank.json');
const PREFIX = COVERAGE ? 'SPC' : 'SP';

/* objective labels, straight from the objectives document */
const LABELS = new Map();
for (const line of fs.readFileSync(OBJECTIVES, 'utf8').split(/\r?\n/)) {
  const m = line.match(/^##\s+(\d\.\d)\s+(.*)$/);
  if (m) LABELS.set(m[1], `${m[1]} ${m[2].trim()}`);
}

/* ------------------------------------------------------------------ */

const files = fs.readdirSync(SRC).filter((f) => f.endsWith('.mjs')).sort();
const raw = [];
for (const f of files) {
  const mod = await import(new URL(`file://${path.join(SRC, f)}`).href);
  const items = mod.default ?? mod.ITEMS ?? [];
  for (const it of items) raw.push({ ...it, _file: f });
  console.log(`${f.padEnd(10)} ${items.length} items`);
}

const errors = [];
const seenStem = new Map();
const items = [];
const perCode = new Map();

raw.forEach((it, n) => {
  const where = `${it._file}#${n + 1}`;
  const code = String(it.objective ?? '').trim();

  if (!LABELS.has(code)) {
    errors.push(`${where}: objective "${code}" is not an SY0-701 objective code`);
    return;
  }
  if (!Array.isArray(it.options) || it.options.length < 3) {
    errors.push(`${where}: needs at least 3 options, got ${it.options?.length}`);
    return;
  }
  if (!Number.isInteger(it.answer) || it.answer < 0 || it.answer >= it.options.length) {
    errors.push(`${where}: answer index ${it.answer} out of range`);
    return;
  }
  if (new Set(it.options.map((o) => o.toLowerCase().trim())).size !== it.options.length) {
    errors.push(`${where}: duplicate options`);
    return;
  }
  // An explanation that only restates the answer teaches nothing. The whole
  // point of the authored bank is that it names the discriminator.
  if (!it.explanation || it.explanation.length < 60) {
    errors.push(`${where}: explanation missing or too short to name a discriminator`);
    return;
  }
  const key = it.stem.toLowerCase().replace(/\s+/g, ' ').trim();
  if (seenStem.has(key)) {
    errors.push(`${where}: duplicate stem, first seen at ${seenStem.get(key)}`);
    return;
  }
  seenStem.set(key, where);

  const seq = (perCode.get(code) ?? 0) + 1;
  perCode.set(code, seq);

  items.push({
    id: `${PREFIX}-${code.replace('.', '')}-${String(seq).padStart(3, '0')}`,
    objective: LABELS.get(code),
    domain: `${code[0]}.0`,
    stem: it.stem,
    options: it.options,
    answer: it.answer,
    explanation: it.explanation,
    source: COVERAGE ? 'authored-coverage' : 'authored',
    difficulty: it.difficulty ?? 'standard',
  });
});

if (errors.length) {
  console.error(`\n${errors.length} problem(s):`);
  for (const e of errors) console.error(`  ${e}`);
  process.exit(1);
}

const byDomain = {};
for (const it of items) byDomain[it.domain] = (byDomain[it.domain] ?? 0) + 1;

fs.writeFileSync(OUT, `${JSON.stringify({
  schema_version: 2,
  note: COVERAGE
    ? 'Gap-closing bank. One item per objective-list term that was not yet the '
      + 'credited answer of anything, found by tools/coverage-audit.mjs. Same trust '
      + 'level as the main authored bank, kept separate so the audit stays auditable. '
      + 'Generated by `node tools/build-bank.mjs --coverage` from tools/authored-coverage/.'
    : 'Authored Security+ SY0-701 questions. Every distractor is an adjacent '
      + 'objective-list term or a true-but-broader real-world word; every explanation '
      + 'names the discriminator rather than restating the definition. Generated by '
      + 'tools/build-bank.mjs from tools/authored/ — edit the source files, not this.',
  generated: new Date().toISOString(),
  items,
}, null, 1)}\n`);

console.log(`\n${items.length} items -> ${path.relative(ROOT, OUT)}`);
console.log('per domain:', byDomain);
